// Code generated by ent, DO NOT EDIT.

package freeoffer

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the freeoffer type in the database.
	Label = "free_offer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIdentity holds the string denoting the identity field in the database.
	FieldIdentity = "identity"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldEligible holds the string denoting the eligible field in the database.
	FieldEligible = "eligible"
	// FieldClosed holds the string denoting the closed field in the database.
	FieldClosed = "closed"
	// FieldGeneration holds the string denoting the generation field in the database.
	FieldGeneration = "generation"
	// FieldFirstSeenAt holds the string denoting the first_seen_at field in the database.
	FieldFirstSeenAt = "first_seen_at"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// Table holds the table name of the freeoffer in the database.
	Table = "free_offers"
)

// Columns holds all SQL columns for freeoffer fields.
var Columns = []string{
	FieldID,
	FieldIdentity,
	FieldSource,
	FieldPayload,
	FieldEligible,
	FieldClosed,
	FieldGeneration,
	FieldFirstSeenAt,
	FieldLastSeenAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultEligible holds the default value on creation for the "eligible" field.
	DefaultEligible bool
	// DefaultClosed holds the default value on creation for the "closed" field.
	DefaultClosed bool
	// DefaultGeneration holds the default value on creation for the "generation" field.
	DefaultGeneration int
	// GenerationValidator is a validator for the "generation" field. It is called by the builders before save.
	GenerationValidator func(int) error
	// DefaultFirstSeenAt holds the default value on creation for the "first_seen_at" field.
	DefaultFirstSeenAt func() time.Time
	// DefaultLastSeenAt holds the default value on creation for the "last_seen_at" field.
	DefaultLastSeenAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the FreeOffer queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIdentity orders the results by the identity field.
func ByIdentity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentity, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByEligible orders the results by the eligible field.
func ByEligible(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEligible, opts...).ToFunc()
}

// ByClosed orders the results by the closed field.
func ByClosed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosed, opts...).ToFunc()
}

// ByGeneration orders the results by the generation field.
func ByGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGeneration, opts...).ToFunc()
}

// ByFirstSeenAt orders the results by the first_seen_at field.
func ByFirstSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstSeenAt, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}
