// Code generated by ent, DO NOT EDIT.

package event

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/depthbomb/dealfox/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldID, id))
}

// RuleID applies equality check predicate on the "rule_id" field. It's identical to RuleIDEQ.
func RuleID(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRuleID, v))
}

// ObservationID applies equality check predicate on the "observation_id" field. It's identical to ObservationIDEQ.
func ObservationID(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldObservationID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCreatedAt, v))
}

// RuleIDEQ applies the EQ predicate on the "rule_id" field.
func RuleIDEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRuleID, v))
}

// RuleIDNEQ applies the NEQ predicate on the "rule_id" field.
func RuleIDNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldRuleID, v))
}

// RuleIDIn applies the In predicate on the "rule_id" field.
func RuleIDIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldRuleID, vs...))
}

// RuleIDNotIn applies the NotIn predicate on the "rule_id" field.
func RuleIDNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldRuleID, vs...))
}

// RuleIDGT applies the GT predicate on the "rule_id" field.
func RuleIDGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldRuleID, v))
}

// RuleIDGTE applies the GTE predicate on the "rule_id" field.
func RuleIDGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldRuleID, v))
}

// RuleIDLT applies the LT predicate on the "rule_id" field.
func RuleIDLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldRuleID, v))
}

// RuleIDLTE applies the LTE predicate on the "rule_id" field.
func RuleIDLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldRuleID, v))
}

// RuleIDContains applies the Contains predicate on the "rule_id" field.
func RuleIDContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldRuleID, v))
}

// RuleIDHasPrefix applies the HasPrefix predicate on the "rule_id" field.
func RuleIDHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldRuleID, v))
}

// RuleIDHasSuffix applies the HasSuffix predicate on the "rule_id" field.
func RuleIDHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldRuleID, v))
}

// RuleIDEqualFold applies the EqualFold predicate on the "rule_id" field.
func RuleIDEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldRuleID, v))
}

// RuleIDContainsFold applies the ContainsFold predicate on the "rule_id" field.
func RuleIDContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldRuleID, v))
}

// ObservationIDEQ applies the EQ predicate on the "observation_id" field.
func ObservationIDEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldObservationID, v))
}

// ObservationIDNEQ applies the NEQ predicate on the "observation_id" field.
func ObservationIDNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldObservationID, v))
}

// ObservationIDIn applies the In predicate on the "observation_id" field.
func ObservationIDIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldObservationID, vs...))
}

// ObservationIDNotIn applies the NotIn predicate on the "observation_id" field.
func ObservationIDNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldObservationID, vs...))
}

// ObservationIDGT applies the GT predicate on the "observation_id" field.
func ObservationIDGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldObservationID, v))
}

// ObservationIDGTE applies the GTE predicate on the "observation_id" field.
func ObservationIDGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldObservationID, v))
}

// ObservationIDLT applies the LT predicate on the "observation_id" field.
func ObservationIDLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldObservationID, v))
}

// ObservationIDLTE applies the LTE predicate on the "observation_id" field.
func ObservationIDLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldObservationID, v))
}

// ObservationIDContains applies the Contains predicate on the "observation_id" field.
func ObservationIDContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldObservationID, v))
}

// ObservationIDHasPrefix applies the HasPrefix predicate on the "observation_id" field.
func ObservationIDHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldObservationID, v))
}

// ObservationIDHasSuffix applies the HasSuffix predicate on the "observation_id" field.
func ObservationIDHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldObservationID, v))
}

// ObservationIDEqualFold applies the EqualFold predicate on the "observation_id" field.
func ObservationIDEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldObservationID, v))
}

// ObservationIDContainsFold applies the ContainsFold predicate on the "observation_id" field.
func ObservationIDContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldObservationID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldCreatedAt, v))
}

// HasRule applies the HasEdge predicate on the "rule" edge.
func HasRule() predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RuleTable, RuleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRuleWith applies the HasEdge predicate on the "rule" edge with a given conditions (other predicates).
func HasRuleWith(preds ...predicate.Rule) predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := newRuleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasObservation applies the HasEdge predicate on the "observation" edge.
func HasObservation() predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ObservationTable, ObservationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasObservationWith applies the HasEdge predicate on the "observation" edge with a given conditions (other predicates).
func HasObservationWith(preds ...predicate.Observation) predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := newObservationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeliveries applies the HasEdge predicate on the "deliveries" edge.
func HasDeliveries() predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DeliveriesTable, DeliveriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeliveriesWith applies the HasEdge predicate on the "deliveries" edge with a given conditions (other predicates).
func HasDeliveriesWith(preds ...predicate.Delivery) predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := newDeliveriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Event) predicate.Event {
	return predicate.Event(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Event) predicate.Event {
	return predicate.Event(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Event) predicate.Event {
	return predicate.Event(sql.NotPredicates(p))
}
