// Code generated by ent, DO NOT EDIT.

package freesubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/depthbomb/dealfox/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldContainsFold(FieldID, id))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldScope, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldSource, v))
}

// DestinationID applies equality check predicate on the "destination_id" field. It's identical to DestinationIDEQ.
func DestinationID(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldDestinationID, v))
}

// ManagedBy applies equality check predicate on the "managed_by" field. It's identical to ManagedByEQ.
func ManagedBy(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldManagedBy, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldContainsFold(FieldScope, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldContainsFold(FieldSource, v))
}

// DestinationKindEQ applies the EQ predicate on the "destination_kind" field.
func DestinationKindEQ(v DestinationKind) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldDestinationKind, v))
}

// DestinationKindNEQ applies the NEQ predicate on the "destination_kind" field.
func DestinationKindNEQ(v DestinationKind) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNEQ(FieldDestinationKind, v))
}

// DestinationKindIn applies the In predicate on the "destination_kind" field.
func DestinationKindIn(vs ...DestinationKind) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldIn(FieldDestinationKind, vs...))
}

// DestinationKindNotIn applies the NotIn predicate on the "destination_kind" field.
func DestinationKindNotIn(vs ...DestinationKind) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNotIn(FieldDestinationKind, vs...))
}

// DestinationIDEQ applies the EQ predicate on the "destination_id" field.
func DestinationIDEQ(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldDestinationID, v))
}

// DestinationIDNEQ applies the NEQ predicate on the "destination_id" field.
func DestinationIDNEQ(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNEQ(FieldDestinationID, v))
}

// DestinationIDIn applies the In predicate on the "destination_id" field.
func DestinationIDIn(vs ...string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldIn(FieldDestinationID, vs...))
}

// DestinationIDNotIn applies the NotIn predicate on the "destination_id" field.
func DestinationIDNotIn(vs ...string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNotIn(FieldDestinationID, vs...))
}

// DestinationIDGT applies the GT predicate on the "destination_id" field.
func DestinationIDGT(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGT(FieldDestinationID, v))
}

// DestinationIDGTE applies the GTE predicate on the "destination_id" field.
func DestinationIDGTE(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGTE(FieldDestinationID, v))
}

// DestinationIDLT applies the LT predicate on the "destination_id" field.
func DestinationIDLT(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLT(FieldDestinationID, v))
}

// DestinationIDLTE applies the LTE predicate on the "destination_id" field.
func DestinationIDLTE(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLTE(FieldDestinationID, v))
}

// DestinationIDContains applies the Contains predicate on the "destination_id" field.
func DestinationIDContains(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldContains(FieldDestinationID, v))
}

// DestinationIDHasPrefix applies the HasPrefix predicate on the "destination_id" field.
func DestinationIDHasPrefix(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldHasPrefix(FieldDestinationID, v))
}

// DestinationIDHasSuffix applies the HasSuffix predicate on the "destination_id" field.
func DestinationIDHasSuffix(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldHasSuffix(FieldDestinationID, v))
}

// DestinationIDEqualFold applies the EqualFold predicate on the "destination_id" field.
func DestinationIDEqualFold(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEqualFold(FieldDestinationID, v))
}

// DestinationIDContainsFold applies the ContainsFold predicate on the "destination_id" field.
func DestinationIDContainsFold(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldContainsFold(FieldDestinationID, v))
}

// ManagedByEQ applies the EQ predicate on the "managed_by" field.
func ManagedByEQ(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldManagedBy, v))
}

// ManagedByNEQ applies the NEQ predicate on the "managed_by" field.
func ManagedByNEQ(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNEQ(FieldManagedBy, v))
}

// ManagedByIn applies the In predicate on the "managed_by" field.
func ManagedByIn(vs ...string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldIn(FieldManagedBy, vs...))
}

// ManagedByNotIn applies the NotIn predicate on the "managed_by" field.
func ManagedByNotIn(vs ...string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNotIn(FieldManagedBy, vs...))
}

// ManagedByGT applies the GT predicate on the "managed_by" field.
func ManagedByGT(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGT(FieldManagedBy, v))
}

// ManagedByGTE applies the GTE predicate on the "managed_by" field.
func ManagedByGTE(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGTE(FieldManagedBy, v))
}

// ManagedByLT applies the LT predicate on the "managed_by" field.
func ManagedByLT(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLT(FieldManagedBy, v))
}

// ManagedByLTE applies the LTE predicate on the "managed_by" field.
func ManagedByLTE(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLTE(FieldManagedBy, v))
}

// ManagedByContains applies the Contains predicate on the "managed_by" field.
func ManagedByContains(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldContains(FieldManagedBy, v))
}

// ManagedByHasPrefix applies the HasPrefix predicate on the "managed_by" field.
func ManagedByHasPrefix(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldHasPrefix(FieldManagedBy, v))
}

// ManagedByHasSuffix applies the HasSuffix predicate on the "managed_by" field.
func ManagedByHasSuffix(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldHasSuffix(FieldManagedBy, v))
}

// ManagedByEqualFold applies the EqualFold predicate on the "managed_by" field.
func ManagedByEqualFold(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEqualFold(FieldManagedBy, v))
}

// ManagedByContainsFold applies the ContainsFold predicate on the "managed_by" field.
func ManagedByContainsFold(v string) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldContainsFold(FieldManagedBy, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FreeSubscription) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FreeSubscription) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FreeSubscription) predicate.FreeSubscription {
	return predicate.FreeSubscription(sql.NotPredicates(p))
}
