// Code generated by ent, DO NOT EDIT.

package freedelivery

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/depthbomb/dealfox/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldContainsFold(FieldID, id))
}

// OfferID applies equality check predicate on the "offer_id" field. It's identical to OfferIDEQ.
func OfferID(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldOfferID, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldSubscriptionID, v))
}

// OfferGeneration applies equality check predicate on the "offer_generation" field. It's identical to OfferGenerationEQ.
func OfferGeneration(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldOfferGeneration, v))
}

// DestinationID applies equality check predicate on the "destination_id" field. It's identical to DestinationIDEQ.
func DestinationID(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldDestinationID, v))
}

// AttemptCount applies equality check predicate on the "attempt_count" field. It's identical to AttemptCountEQ.
func AttemptCount(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldAttemptCount, v))
}

// NextAttemptAt applies equality check predicate on the "next_attempt_at" field. It's identical to NextAttemptAtEQ.
func NextAttemptAt(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldNextAttemptAt, v))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldMessageID, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldLastError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldUpdatedAt, v))
}

// OfferIDEQ applies the EQ predicate on the "offer_id" field.
func OfferIDEQ(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldOfferID, v))
}

// OfferIDNEQ applies the NEQ predicate on the "offer_id" field.
func OfferIDNEQ(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNEQ(FieldOfferID, v))
}

// OfferIDIn applies the In predicate on the "offer_id" field.
func OfferIDIn(vs ...string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldIn(FieldOfferID, vs...))
}

// OfferIDNotIn applies the NotIn predicate on the "offer_id" field.
func OfferIDNotIn(vs ...string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNotIn(FieldOfferID, vs...))
}

// OfferIDGT applies the GT predicate on the "offer_id" field.
func OfferIDGT(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGT(FieldOfferID, v))
}

// OfferIDGTE applies the GTE predicate on the "offer_id" field.
func OfferIDGTE(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGTE(FieldOfferID, v))
}

// OfferIDLT applies the LT predicate on the "offer_id" field.
func OfferIDLT(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLT(FieldOfferID, v))
}

// OfferIDLTE applies the LTE predicate on the "offer_id" field.
func OfferIDLTE(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLTE(FieldOfferID, v))
}

// OfferIDContains applies the Contains predicate on the "offer_id" field.
func OfferIDContains(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldContains(FieldOfferID, v))
}

// OfferIDHasPrefix applies the HasPrefix predicate on the "offer_id" field.
func OfferIDHasPrefix(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldHasPrefix(FieldOfferID, v))
}

// OfferIDHasSuffix applies the HasSuffix predicate on the "offer_id" field.
func OfferIDHasSuffix(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldHasSuffix(FieldOfferID, v))
}

// OfferIDEqualFold applies the EqualFold predicate on the "offer_id" field.
func OfferIDEqualFold(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEqualFold(FieldOfferID, v))
}

// OfferIDContainsFold applies the ContainsFold predicate on the "offer_id" field.
func OfferIDContainsFold(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldContainsFold(FieldOfferID, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDGT applies the GT predicate on the "subscription_id" field.
func SubscriptionIDGT(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGT(FieldSubscriptionID, v))
}

// SubscriptionIDGTE applies the GTE predicate on the "subscription_id" field.
func SubscriptionIDGTE(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGTE(FieldSubscriptionID, v))
}

// SubscriptionIDLT applies the LT predicate on the "subscription_id" field.
func SubscriptionIDLT(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLT(FieldSubscriptionID, v))
}

// SubscriptionIDLTE applies the LTE predicate on the "subscription_id" field.
func SubscriptionIDLTE(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLTE(FieldSubscriptionID, v))
}

// SubscriptionIDContains applies the Contains predicate on the "subscription_id" field.
func SubscriptionIDContains(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldContains(FieldSubscriptionID, v))
}

// SubscriptionIDHasPrefix applies the HasPrefix predicate on the "subscription_id" field.
func SubscriptionIDHasPrefix(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldHasPrefix(FieldSubscriptionID, v))
}

// SubscriptionIDHasSuffix applies the HasSuffix predicate on the "subscription_id" field.
func SubscriptionIDHasSuffix(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldHasSuffix(FieldSubscriptionID, v))
}

// SubscriptionIDEqualFold applies the EqualFold predicate on the "subscription_id" field.
func SubscriptionIDEqualFold(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEqualFold(FieldSubscriptionID, v))
}

// SubscriptionIDContainsFold applies the ContainsFold predicate on the "subscription_id" field.
func SubscriptionIDContainsFold(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldContainsFold(FieldSubscriptionID, v))
}

// OfferGenerationEQ applies the EQ predicate on the "offer_generation" field.
func OfferGenerationEQ(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldOfferGeneration, v))
}

// OfferGenerationNEQ applies the NEQ predicate on the "offer_generation" field.
func OfferGenerationNEQ(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNEQ(FieldOfferGeneration, v))
}

// OfferGenerationIn applies the In predicate on the "offer_generation" field.
func OfferGenerationIn(vs ...int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldIn(FieldOfferGeneration, vs...))
}

// OfferGenerationNotIn applies the NotIn predicate on the "offer_generation" field.
func OfferGenerationNotIn(vs ...int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNotIn(FieldOfferGeneration, vs...))
}

// OfferGenerationGT applies the GT predicate on the "offer_generation" field.
func OfferGenerationGT(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGT(FieldOfferGeneration, v))
}

// OfferGenerationGTE applies the GTE predicate on the "offer_generation" field.
func OfferGenerationGTE(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGTE(FieldOfferGeneration, v))
}

// OfferGenerationLT applies the LT predicate on the "offer_generation" field.
func OfferGenerationLT(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLT(FieldOfferGeneration, v))
}

// OfferGenerationLTE applies the LTE predicate on the "offer_generation" field.
func OfferGenerationLTE(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLTE(FieldOfferGeneration, v))
}

// DestinationKindEQ applies the EQ predicate on the "destination_kind" field.
func DestinationKindEQ(v DestinationKind) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldDestinationKind, v))
}

// DestinationKindNEQ applies the NEQ predicate on the "destination_kind" field.
func DestinationKindNEQ(v DestinationKind) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNEQ(FieldDestinationKind, v))
}

// DestinationKindIn applies the In predicate on the "destination_kind" field.
func DestinationKindIn(vs ...DestinationKind) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldIn(FieldDestinationKind, vs...))
}

// DestinationKindNotIn applies the NotIn predicate on the "destination_kind" field.
func DestinationKindNotIn(vs ...DestinationKind) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNotIn(FieldDestinationKind, vs...))
}

// DestinationIDEQ applies the EQ predicate on the "destination_id" field.
func DestinationIDEQ(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldDestinationID, v))
}

// DestinationIDNEQ applies the NEQ predicate on the "destination_id" field.
func DestinationIDNEQ(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNEQ(FieldDestinationID, v))
}

// DestinationIDIn applies the In predicate on the "destination_id" field.
func DestinationIDIn(vs ...string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldIn(FieldDestinationID, vs...))
}

// DestinationIDNotIn applies the NotIn predicate on the "destination_id" field.
func DestinationIDNotIn(vs ...string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNotIn(FieldDestinationID, vs...))
}

// DestinationIDGT applies the GT predicate on the "destination_id" field.
func DestinationIDGT(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGT(FieldDestinationID, v))
}

// DestinationIDGTE applies the GTE predicate on the "destination_id" field.
func DestinationIDGTE(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGTE(FieldDestinationID, v))
}

// DestinationIDLT applies the LT predicate on the "destination_id" field.
func DestinationIDLT(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLT(FieldDestinationID, v))
}

// DestinationIDLTE applies the LTE predicate on the "destination_id" field.
func DestinationIDLTE(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLTE(FieldDestinationID, v))
}

// DestinationIDContains applies the Contains predicate on the "destination_id" field.
func DestinationIDContains(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldContains(FieldDestinationID, v))
}

// DestinationIDHasPrefix applies the HasPrefix predicate on the "destination_id" field.
func DestinationIDHasPrefix(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldHasPrefix(FieldDestinationID, v))
}

// DestinationIDHasSuffix applies the HasSuffix predicate on the "destination_id" field.
func DestinationIDHasSuffix(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldHasSuffix(FieldDestinationID, v))
}

// DestinationIDEqualFold applies the EqualFold predicate on the "destination_id" field.
func DestinationIDEqualFold(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEqualFold(FieldDestinationID, v))
}

// DestinationIDContainsFold applies the ContainsFold predicate on the "destination_id" field.
func DestinationIDContainsFold(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldContainsFold(FieldDestinationID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNotIn(FieldStatus, vs...))
}

// AttemptCountEQ applies the EQ predicate on the "attempt_count" field.
func AttemptCountEQ(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attempt_count" field.
func AttemptCountNEQ(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attempt_count" field.
func AttemptCountIn(vs ...int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attempt_count" field.
func AttemptCountNotIn(vs ...int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attempt_count" field.
func AttemptCountGT(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attempt_count" field.
func AttemptCountGTE(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attempt_count" field.
func AttemptCountLT(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attempt_count" field.
func AttemptCountLTE(v int) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLTE(FieldAttemptCount, v))
}

// NextAttemptAtEQ applies the EQ predicate on the "next_attempt_at" field.
func NextAttemptAtEQ(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtNEQ applies the NEQ predicate on the "next_attempt_at" field.
func NextAttemptAtNEQ(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtIn applies the In predicate on the "next_attempt_at" field.
func NextAttemptAtIn(vs ...time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtNotIn applies the NotIn predicate on the "next_attempt_at" field.
func NextAttemptAtNotIn(vs ...time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNotIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtGT applies the GT predicate on the "next_attempt_at" field.
func NextAttemptAtGT(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGT(FieldNextAttemptAt, v))
}

// NextAttemptAtGTE applies the GTE predicate on the "next_attempt_at" field.
func NextAttemptAtGTE(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGTE(FieldNextAttemptAt, v))
}

// NextAttemptAtLT applies the LT predicate on the "next_attempt_at" field.
func NextAttemptAtLT(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLT(FieldNextAttemptAt, v))
}

// NextAttemptAtLTE applies the LTE predicate on the "next_attempt_at" field.
func NextAttemptAtLTE(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLTE(FieldNextAttemptAt, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDGT applies the GT predicate on the "message_id" field.
func MessageIDGT(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGT(FieldMessageID, v))
}

// MessageIDGTE applies the GTE predicate on the "message_id" field.
func MessageIDGTE(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGTE(FieldMessageID, v))
}

// MessageIDLT applies the LT predicate on the "message_id" field.
func MessageIDLT(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLT(FieldMessageID, v))
}

// MessageIDLTE applies the LTE predicate on the "message_id" field.
func MessageIDLTE(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLTE(FieldMessageID, v))
}

// MessageIDContains applies the Contains predicate on the "message_id" field.
func MessageIDContains(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldContains(FieldMessageID, v))
}

// MessageIDHasPrefix applies the HasPrefix predicate on the "message_id" field.
func MessageIDHasPrefix(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldHasPrefix(FieldMessageID, v))
}

// MessageIDHasSuffix applies the HasSuffix predicate on the "message_id" field.
func MessageIDHasSuffix(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldHasSuffix(FieldMessageID, v))
}

// MessageIDEqualFold applies the EqualFold predicate on the "message_id" field.
func MessageIDEqualFold(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEqualFold(FieldMessageID, v))
}

// MessageIDContainsFold applies the ContainsFold predicate on the "message_id" field.
func MessageIDContainsFold(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldContainsFold(FieldMessageID, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldContainsFold(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FreeDelivery) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FreeDelivery) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FreeDelivery) predicate.FreeDelivery {
	return predicate.FreeDelivery(sql.NotPredicates(p))
}
