// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppsColumns holds the columns for the "apps" table.
	AppsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "last_modified", Type: field.TypeInt64, Default: 0},
		{Name: "price_change_number", Type: field.TypeInt64, Default: 0},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AppsTable holds the schema information for the "apps" table.
	AppsTable = &schema.Table{
		Name:       "apps",
		Columns:    AppsColumns,
		PrimaryKey: []*schema.Column{AppsColumns[0]},
	}
	// DeliveriesColumns holds the columns for the "deliveries" table.
	DeliveriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 24},
		{Name: "destination_id", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "sending", "retry", "sent", "dead", "cancelled"}, Default: "pending"},
		{Name: "attempt_count", Type: field.TypeInt, Default: 0},
		{Name: "next_attempt_at", Type: field.TypeTime},
		{Name: "message_id", Type: field.TypeString, Default: ""},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "event_id", Type: field.TypeString, Size: 24},
	}
	// DeliveriesTable holds the schema information for the "deliveries" table.
	DeliveriesTable = &schema.Table{
		Name:       "deliveries",
		Columns:    DeliveriesColumns,
		PrimaryKey: []*schema.Column{DeliveriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "deliveries_events_deliveries",
				Columns:    []*schema.Column{DeliveriesColumns[9]},
				RefColumns: []*schema.Column{EventsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "delivery_status_next_attempt_at",
				Unique:  false,
				Columns: []*schema.Column{DeliveriesColumns[2], DeliveriesColumns[4]},
			},
			{
				Name:    "delivery_event_id",
				Unique:  true,
				Columns: []*schema.Column{DeliveriesColumns[9]},
			},
		},
	}
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 24},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "observation_id", Type: field.TypeString, Size: 24},
		{Name: "rule_id", Type: field.TypeString, Size: 24},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "events_observations_events",
				Columns:    []*schema.Column{EventsColumns[3]},
				RefColumns: []*schema.Column{ObservationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "events_rules_events",
				Columns:    []*schema.Column{EventsColumns[4]},
				RefColumns: []*schema.Column{RulesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "event_rule_id_observation_id",
				Unique:  true,
				Columns: []*schema.Column{EventsColumns[4], EventsColumns[3]},
			},
		},
	}
	// FreeDeliveriesColumns holds the columns for the "free_deliveries" table.
	FreeDeliveriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 24},
		{Name: "offer_id", Type: field.TypeString},
		{Name: "subscription_id", Type: field.TypeString},
		{Name: "offer_generation", Type: field.TypeInt, Default: 1},
		{Name: "destination_kind", Type: field.TypeEnum, Enums: []string{"dm", "channel"}},
		{Name: "destination_id", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "sending", "retry", "sent", "dead", "cancelled"}, Default: "pending"},
		{Name: "attempt_count", Type: field.TypeInt, Default: 0},
		{Name: "next_attempt_at", Type: field.TypeTime},
		{Name: "message_id", Type: field.TypeString, Default: ""},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// FreeDeliveriesTable holds the schema information for the "free_deliveries" table.
	FreeDeliveriesTable = &schema.Table{
		Name:       "free_deliveries",
		Columns:    FreeDeliveriesColumns,
		PrimaryKey: []*schema.Column{FreeDeliveriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "freedelivery_offer_id_offer_generation_subscription_id",
				Unique:  true,
				Columns: []*schema.Column{FreeDeliveriesColumns[1], FreeDeliveriesColumns[3], FreeDeliveriesColumns[2]},
			},
			{
				Name:    "freedelivery_status_next_attempt_at",
				Unique:  false,
				Columns: []*schema.Column{FreeDeliveriesColumns[7], FreeDeliveriesColumns[9]},
			},
		},
	}
	// FreeMonitorsColumns holds the columns for the "free_monitors" table.
	FreeMonitorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "checked_at", Type: field.TypeTime, Nullable: true},
		{Name: "next_check_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: "not checked"},
		{Name: "problems", Type: field.TypeJSON, Nullable: true},
		{Name: "failures", Type: field.TypeInt, Default: 0},
	}
	// FreeMonitorsTable holds the schema information for the "free_monitors" table.
	FreeMonitorsTable = &schema.Table{
		Name:       "free_monitors",
		Columns:    FreeMonitorsColumns,
		PrimaryKey: []*schema.Column{FreeMonitorsColumns[0]},
	}
	// FreeOffersColumns holds the columns for the "free_offers" table.
	FreeOffersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 24},
		{Name: "identity", Type: field.TypeString, Unique: true},
		{Name: "source", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "eligible", Type: field.TypeBool, Default: false},
		{Name: "closed", Type: field.TypeBool, Default: false},
		{Name: "generation", Type: field.TypeInt, Default: 1},
		{Name: "first_seen_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime},
	}
	// FreeOffersTable holds the schema information for the "free_offers" table.
	FreeOffersTable = &schema.Table{
		Name:       "free_offers",
		Columns:    FreeOffersColumns,
		PrimaryKey: []*schema.Column{FreeOffersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "freeoffer_source_eligible",
				Unique:  false,
				Columns: []*schema.Column{FreeOffersColumns[2], FreeOffersColumns[4]},
			},
		},
	}
	// FreeSubscriptionsColumns holds the columns for the "free_subscriptions" table.
	FreeSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 24},
		{Name: "scope", Type: field.TypeString},
		{Name: "source", Type: field.TypeString},
		{Name: "destination_kind", Type: field.TypeEnum, Enums: []string{"dm", "channel"}},
		{Name: "destination_id", Type: field.TypeString},
		{Name: "managed_by", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// FreeSubscriptionsTable holds the schema information for the "free_subscriptions" table.
	FreeSubscriptionsTable = &schema.Table{
		Name:       "free_subscriptions",
		Columns:    FreeSubscriptionsColumns,
		PrimaryKey: []*schema.Column{FreeSubscriptionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "freesubscription_scope_source",
				Unique:  true,
				Columns: []*schema.Column{FreeSubscriptionsColumns[1], FreeSubscriptionsColumns[2]},
			},
			{
				Name:    "freesubscription_source_enabled",
				Unique:  false,
				Columns: []*schema.Column{FreeSubscriptionsColumns[2], FreeSubscriptionsColumns[6]},
			},
		},
	}
	// ObservationsColumns holds the columns for the "observations" table.
	ObservationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 24},
		{Name: "observed_at", Type: field.TypeTime},
		{Name: "price", Type: field.TypeJSON},
		{Name: "target_id", Type: field.TypeString, Size: 24},
	}
	// ObservationsTable holds the schema information for the "observations" table.
	ObservationsTable = &schema.Table{
		Name:       "observations",
		Columns:    ObservationsColumns,
		PrimaryKey: []*schema.Column{ObservationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "observations_targets_observations",
				Columns:    []*schema.Column{ObservationsColumns[3]},
				RefColumns: []*schema.Column{TargetsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "observation_target_id_observed_at",
				Unique:  false,
				Columns: []*schema.Column{ObservationsColumns[3], ObservationsColumns[1]},
			},
			{
				Name:    "observation_observed_at",
				Unique:  false,
				Columns: []*schema.Column{ObservationsColumns[1]},
			},
		},
	}
	// RulesColumns holds the columns for the "rules" table.
	RulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 24},
		{Name: "owner_id", Type: field.TypeString},
		{Name: "request_id", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "condition", Type: field.TypeEnum, Enums: []string{"any_sale", "sale_under_budget"}},
		{Name: "budget_minor", Type: field.TypeInt64, Nullable: true},
		{Name: "budget_currency", Type: field.TypeString, Default: ""},
		{Name: "recurring", Type: field.TypeBool, Default: false},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "latched", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "target_id", Type: field.TypeString, Size: 24},
	}
	// RulesTable holds the schema information for the "rules" table.
	RulesTable = &schema.Table{
		Name:       "rules",
		Columns:    RulesColumns,
		PrimaryKey: []*schema.Column{RulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rules_targets_rules",
				Columns:    []*schema.Column{RulesColumns[11]},
				RefColumns: []*schema.Column{TargetsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "rule_owner_id_enabled",
				Unique:  false,
				Columns: []*schema.Column{RulesColumns[1], RulesColumns[7]},
			},
			{
				Name:    "rule_target_id_enabled",
				Unique:  false,
				Columns: []*schema.Column{RulesColumns[11], RulesColumns[7]},
			},
			{
				Name:    "rule_owner_id_target_id_condition",
				Unique:  true,
				Columns: []*schema.Column{RulesColumns[1], RulesColumns[11], RulesColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					Where: "enabled",
				},
			},
		},
	}
	// TargetsColumns holds the columns for the "targets" table.
	TargetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 24},
		{Name: "country", Type: field.TypeString, Size: 2},
		{Name: "next_due_at", Type: field.TypeTime},
		{Name: "last_observed_at", Type: field.TypeTime, Nullable: true},
		{Name: "failure_count", Type: field.TypeInt, Default: 0},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "app_id", Type: field.TypeInt64},
	}
	// TargetsTable holds the schema information for the "targets" table.
	TargetsTable = &schema.Table{
		Name:       "targets",
		Columns:    TargetsColumns,
		PrimaryKey: []*schema.Column{TargetsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "targets_apps_targets",
				Columns:    []*schema.Column{TargetsColumns[6]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "target_app_id_country",
				Unique:  true,
				Columns: []*schema.Column{TargetsColumns[6], TargetsColumns[1]},
			},
			{
				Name:    "target_next_due_at",
				Unique:  false,
				Columns: []*schema.Column{TargetsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppsTable,
		DeliveriesTable,
		EventsTable,
		FreeDeliveriesTable,
		FreeMonitorsTable,
		FreeOffersTable,
		FreeSubscriptionsTable,
		ObservationsTable,
		RulesTable,
		TargetsTable,
	}
)

func init() {
	DeliveriesTable.ForeignKeys[0].RefTable = EventsTable
	DeliveriesTable.Annotation = &entsql.Annotation{}
	DeliveriesTable.Annotation.Checks = map[string]string{
		"delivery_attempts": "attempt_count >= 0",
		"delivery_status":   "status IN ('pending', 'sending', 'retry', 'sent', 'dead', 'cancelled')",
	}
	EventsTable.ForeignKeys[0].RefTable = ObservationsTable
	EventsTable.ForeignKeys[1].RefTable = RulesTable
	ObservationsTable.ForeignKeys[0].RefTable = TargetsTable
	RulesTable.ForeignKeys[0].RefTable = TargetsTable
	RulesTable.Annotation = &entsql.Annotation{}
	RulesTable.Annotation.Checks = map[string]string{
		"rule_budget": "(condition = 'any_sale' AND budget_minor IS NULL AND budget_currency = '') OR (condition = 'sale_under_budget' AND budget_minor IS NOT NULL AND budget_minor >= 0 AND budget_currency ~ '^[A-Z]{3}$')",
	}
	TargetsTable.ForeignKeys[0].RefTable = AppsTable
	TargetsTable.Annotation = &entsql.Annotation{}
	TargetsTable.Annotation.Checks = map[string]string{
		"target_country":  "country ~ '^[A-Z]{2}$'",
		"target_failures": "failure_count >= 0",
	}
}
