// Code generated by ent, DO NOT EDIT.

package freemonitor

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the freemonitor type in the database.
	Label = "free_monitor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCheckedAt holds the string denoting the checked_at field in the database.
	FieldCheckedAt = "checked_at"
	// FieldNextCheckAt holds the string denoting the next_check_at field in the database.
	FieldNextCheckAt = "next_check_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProblems holds the string denoting the problems field in the database.
	FieldProblems = "problems"
	// FieldFailures holds the string denoting the failures field in the database.
	FieldFailures = "failures"
	// Table holds the table name of the freemonitor in the database.
	Table = "free_monitors"
)

// Columns holds all SQL columns for freemonitor fields.
var Columns = []string{
	FieldID,
	FieldCheckedAt,
	FieldNextCheckAt,
	FieldStatus,
	FieldProblems,
	FieldFailures,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNextCheckAt holds the default value on creation for the "next_check_at" field.
	DefaultNextCheckAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultFailures holds the default value on creation for the "failures" field.
	DefaultFailures int
)

// OrderOption defines the ordering options for the FreeMonitor queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCheckedAt orders the results by the checked_at field.
func ByCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckedAt, opts...).ToFunc()
}

// ByNextCheckAt orders the results by the next_check_at field.
func ByNextCheckAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextCheckAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFailures orders the results by the failures field.
func ByFailures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailures, opts...).ToFunc()
}
