// Code generated by ent, DO NOT EDIT.

package freemonitor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/depthbomb/dealfox/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldContainsFold(FieldID, id))
}

// CheckedAt applies equality check predicate on the "checked_at" field. It's identical to CheckedAtEQ.
func CheckedAt(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldEQ(FieldCheckedAt, v))
}

// NextCheckAt applies equality check predicate on the "next_check_at" field. It's identical to NextCheckAtEQ.
func NextCheckAt(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldEQ(FieldNextCheckAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldEQ(FieldStatus, v))
}

// Failures applies equality check predicate on the "failures" field. It's identical to FailuresEQ.
func Failures(v int) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldEQ(FieldFailures, v))
}

// CheckedAtEQ applies the EQ predicate on the "checked_at" field.
func CheckedAtEQ(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldEQ(FieldCheckedAt, v))
}

// CheckedAtNEQ applies the NEQ predicate on the "checked_at" field.
func CheckedAtNEQ(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldNEQ(FieldCheckedAt, v))
}

// CheckedAtIn applies the In predicate on the "checked_at" field.
func CheckedAtIn(vs ...time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldIn(FieldCheckedAt, vs...))
}

// CheckedAtNotIn applies the NotIn predicate on the "checked_at" field.
func CheckedAtNotIn(vs ...time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldNotIn(FieldCheckedAt, vs...))
}

// CheckedAtGT applies the GT predicate on the "checked_at" field.
func CheckedAtGT(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldGT(FieldCheckedAt, v))
}

// CheckedAtGTE applies the GTE predicate on the "checked_at" field.
func CheckedAtGTE(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldGTE(FieldCheckedAt, v))
}

// CheckedAtLT applies the LT predicate on the "checked_at" field.
func CheckedAtLT(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldLT(FieldCheckedAt, v))
}

// CheckedAtLTE applies the LTE predicate on the "checked_at" field.
func CheckedAtLTE(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldLTE(FieldCheckedAt, v))
}

// CheckedAtIsNil applies the IsNil predicate on the "checked_at" field.
func CheckedAtIsNil() predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldIsNull(FieldCheckedAt))
}

// CheckedAtNotNil applies the NotNil predicate on the "checked_at" field.
func CheckedAtNotNil() predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldNotNull(FieldCheckedAt))
}

// NextCheckAtEQ applies the EQ predicate on the "next_check_at" field.
func NextCheckAtEQ(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldEQ(FieldNextCheckAt, v))
}

// NextCheckAtNEQ applies the NEQ predicate on the "next_check_at" field.
func NextCheckAtNEQ(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldNEQ(FieldNextCheckAt, v))
}

// NextCheckAtIn applies the In predicate on the "next_check_at" field.
func NextCheckAtIn(vs ...time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldIn(FieldNextCheckAt, vs...))
}

// NextCheckAtNotIn applies the NotIn predicate on the "next_check_at" field.
func NextCheckAtNotIn(vs ...time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldNotIn(FieldNextCheckAt, vs...))
}

// NextCheckAtGT applies the GT predicate on the "next_check_at" field.
func NextCheckAtGT(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldGT(FieldNextCheckAt, v))
}

// NextCheckAtGTE applies the GTE predicate on the "next_check_at" field.
func NextCheckAtGTE(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldGTE(FieldNextCheckAt, v))
}

// NextCheckAtLT applies the LT predicate on the "next_check_at" field.
func NextCheckAtLT(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldLT(FieldNextCheckAt, v))
}

// NextCheckAtLTE applies the LTE predicate on the "next_check_at" field.
func NextCheckAtLTE(v time.Time) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldLTE(FieldNextCheckAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldContainsFold(FieldStatus, v))
}

// ProblemsIsNil applies the IsNil predicate on the "problems" field.
func ProblemsIsNil() predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldIsNull(FieldProblems))
}

// ProblemsNotNil applies the NotNil predicate on the "problems" field.
func ProblemsNotNil() predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldNotNull(FieldProblems))
}

// FailuresEQ applies the EQ predicate on the "failures" field.
func FailuresEQ(v int) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldEQ(FieldFailures, v))
}

// FailuresNEQ applies the NEQ predicate on the "failures" field.
func FailuresNEQ(v int) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldNEQ(FieldFailures, v))
}

// FailuresIn applies the In predicate on the "failures" field.
func FailuresIn(vs ...int) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldIn(FieldFailures, vs...))
}

// FailuresNotIn applies the NotIn predicate on the "failures" field.
func FailuresNotIn(vs ...int) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldNotIn(FieldFailures, vs...))
}

// FailuresGT applies the GT predicate on the "failures" field.
func FailuresGT(v int) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldGT(FieldFailures, v))
}

// FailuresGTE applies the GTE predicate on the "failures" field.
func FailuresGTE(v int) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldGTE(FieldFailures, v))
}

// FailuresLT applies the LT predicate on the "failures" field.
func FailuresLT(v int) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldLT(FieldFailures, v))
}

// FailuresLTE applies the LTE predicate on the "failures" field.
func FailuresLTE(v int) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.FieldLTE(FieldFailures, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FreeMonitor) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FreeMonitor) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FreeMonitor) predicate.FreeMonitor {
	return predicate.FreeMonitor(sql.NotPredicates(p))
}
