// Code generated by argon/helpgen. DO NOT EDIT.
// Use go test -count=1 in CI to check generator inputs without test caching.

package main

import (
	"os/exec"
	"testing"
)

func TestArgonGeneratedHelp_generatedHelp(t *testing.T) {
	command := exec.CommandContext(t.Context(), "go", "run", "./internal/genhelp", "-check")
	command.Dir = "."
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("generated help check: %v\n%s", err, output)
	}
}
