// Code generated by argon/helpgen. DO NOT EDIT.

package main

const generatedHelp_91c104e3c1907cc8 = `Usage: dealfox [command] [options]

Steam sale alerts and free-to-keep game notifications

Configuration uses envschema. Set DATABASE_PATH (local SQLite file path), BOT_TOKEN, and STEAM_WEB_API_KEY for serve. Process environment overrides .env and .env.local next to the executable.

Commands:
  help                     Show command help
  catalog                  Maintain the Steam game and DLC catalog
  commands                 Compare slash commands, or replace the selected scope with --confirm
  database                 Create the database, apply SQLite migrations, or verify migration history
  deliveries               Inspect and administer notification delivery failures
  freegames                Inspect free-game sources and maintain their delivery queue
  serve                    Start the Discord bot and background workers

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
`

const generatedHelp_bd89b58a935ad837 = `Usage: dealfox catalog [command] [options]

Maintain the Steam game and DLC catalog

Commands:
  sync                     Synchronize the Steam catalog

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
`

const generatedHelp_cb6c8723beb5f240 = `Usage: dealfox catalog sync [options]

Synchronize the Steam catalog

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
`

const generatedHelp_0a05246458349451 = `Usage: dealfox commands [options]

Compare slash commands, or replace the selected scope with --confirm

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
  --guild VALUE                Development guild ID; omit for global commands
  --confirm, --no-confirm      Replace all commands in the selected scope [default: false]
`

const generatedHelp_fd8a0e617dc5058f = `Usage: dealfox database [command] [options]

Create the database, apply SQLite migrations, or verify migration history

Commands:
  create                   Create the configured SQLite database file if absent
  migrate                  Apply embedded versioned migrations using Nook
  status                   Verify applied migration versions and checksums

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
`

const generatedHelp_67c890f3f62c5a29 = `Usage: dealfox database create [options]

Create the configured SQLite database file if absent

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
`

const generatedHelp_c1f14fda198f37fb = `Usage: dealfox database migrate [options]

Apply embedded versioned migrations using Nook

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
`

const generatedHelp_c9d21a03723929d7 = `Usage: dealfox database status [options]

Verify applied migration versions and checksums

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
`

const generatedHelp_facaa4717c7f10f8 = `Usage: dealfox deliveries [command] [options]

Inspect and administer notification delivery failures

Commands:
  cancel                   Cancel a pending, retrying, or dead delivery
  list-dead                List dead-letter deliveries
  retry                    Retry a dead delivery

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
`

const generatedHelp_b836f4fbd94e80c5 = `Usage: dealfox deliveries cancel [options]

Cancel a pending, retrying, or dead delivery

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
  --id VALUE                   Delivery CUID (required)
`

const generatedHelp_f9e89e4bd847d298 = `Usage: dealfox deliveries list-dead [options]

List dead-letter deliveries

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
  --limit N                    Maximum number to list (1-1000) [default: 50]
`

const generatedHelp_21d59f7be40c5fd0 = `Usage: dealfox deliveries retry [options]

Retry a dead delivery

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
  --id VALUE                   Delivery CUID (required)
`

const generatedHelp_02d8811327b7bb23 = `Usage: dealfox freegames [command] [options]

Inspect free-game sources and maintain their delivery queue

Commands:
  delivery                 Retry or cancel one free-game delivery
  scan                     Check first-party sources without saving offers or sending notifications
  status                   Show source health, quarantined candidates, and failed deliveries

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
`

const generatedHelp_606fd190f80941a5 = `Usage: dealfox freegames delivery [options]

Retry or cancel one free-game delivery

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
  --id VALUE                    (required)
  --retry, --no-retry          Retry a dead delivery; otherwise cancel it [default: false]
`

const generatedHelp_c77c919915eaebcb = `Usage: dealfox freegames scan [options]

Check first-party sources without saving offers or sending notifications

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
  --sources VALUE              steam, epic, gog, ubisoft, comma-separated selection, or all [default: all]
`

const generatedHelp_861b92c8dcb615f8 = `Usage: dealfox freegames status [options]

Show source health, quarantined candidates, and failed deliveries

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
`

const generatedHelp_7208b59e1c47c489 = `Usage: dealfox serve [options]

Start the Discord bot and background workers

Options:
  --config-dir VALUE           Directory containing .env and .env.local; defaults to the executable directory (inherited)
  --help, -h, --no-help        Show help (inherited) [default: false]
`

func generatedHelp(path string) (string, bool) {
	switch path {
	case "dealfox":
		return generatedHelp_91c104e3c1907cc8, true
	case "dealfox catalog":
		return generatedHelp_bd89b58a935ad837, true
	case "dealfox catalog sync":
		return generatedHelp_cb6c8723beb5f240, true
	case "dealfox commands":
		return generatedHelp_0a05246458349451, true
	case "dealfox database":
		return generatedHelp_fd8a0e617dc5058f, true
	case "dealfox database create":
		return generatedHelp_67c890f3f62c5a29, true
	case "dealfox database migrate":
		return generatedHelp_c1f14fda198f37fb, true
	case "dealfox database status":
		return generatedHelp_c9d21a03723929d7, true
	case "dealfox deliveries":
		return generatedHelp_facaa4717c7f10f8, true
	case "dealfox deliveries cancel":
		return generatedHelp_b836f4fbd94e80c5, true
	case "dealfox deliveries list-dead":
		return generatedHelp_f9e89e4bd847d298, true
	case "dealfox deliveries retry":
		return generatedHelp_21d59f7be40c5fd0, true
	case "dealfox freegames":
		return generatedHelp_02d8811327b7bb23, true
	case "dealfox freegames delivery":
		return generatedHelp_606fd190f80941a5, true
	case "dealfox freegames scan":
		return generatedHelp_c77c919915eaebcb, true
	case "dealfox freegames status":
		return generatedHelp_861b92c8dcb615f8, true
	case "dealfox serve":
		return generatedHelp_7208b59e1c47c489, true
	}

	return "", false
}
