// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/depthbomb/dealfox/ent/app"
	"github.com/depthbomb/dealfox/ent/predicate"
	"github.com/depthbomb/dealfox/ent/target"
)

// AppUpdate is the builder for updating App entities.
type AppUpdate struct {
	config
	hooks    []Hook
	mutation *AppMutation
}

// Where appends a list predicates to the AppUpdate builder.
func (_u *AppUpdate) Where(ps ...predicate.App) *AppUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AppUpdate) SetName(v string) *AppUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppUpdate) SetNillableName(v *string) *AppUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AppUpdate) SetType(v string) *AppUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AppUpdate) SetNillableType(v *string) *AppUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetLastModified sets the "last_modified" field.
func (_u *AppUpdate) SetLastModified(v int64) *AppUpdate {
	_u.mutation.ResetLastModified()
	_u.mutation.SetLastModified(v)
	return _u
}

// SetNillableLastModified sets the "last_modified" field if the given value is not nil.
func (_u *AppUpdate) SetNillableLastModified(v *int64) *AppUpdate {
	if v != nil {
		_u.SetLastModified(*v)
	}
	return _u
}

// AddLastModified adds value to the "last_modified" field.
func (_u *AppUpdate) AddLastModified(v int64) *AppUpdate {
	_u.mutation.AddLastModified(v)
	return _u
}

// SetPriceChangeNumber sets the "price_change_number" field.
func (_u *AppUpdate) SetPriceChangeNumber(v int64) *AppUpdate {
	_u.mutation.ResetPriceChangeNumber()
	_u.mutation.SetPriceChangeNumber(v)
	return _u
}

// SetNillablePriceChangeNumber sets the "price_change_number" field if the given value is not nil.
func (_u *AppUpdate) SetNillablePriceChangeNumber(v *int64) *AppUpdate {
	if v != nil {
		_u.SetPriceChangeNumber(*v)
	}
	return _u
}

// AddPriceChangeNumber adds value to the "price_change_number" field.
func (_u *AppUpdate) AddPriceChangeNumber(v int64) *AppUpdate {
	_u.mutation.AddPriceChangeNumber(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppUpdate) SetUpdatedAt(v time.Time) *AppUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTargetIDs adds the "targets" edge to the Target entity by IDs.
func (_u *AppUpdate) AddTargetIDs(ids ...string) *AppUpdate {
	_u.mutation.AddTargetIDs(ids...)
	return _u
}

// AddTargets adds the "targets" edges to the Target entity.
func (_u *AppUpdate) AddTargets(v ...*Target) *AppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTargetIDs(ids...)
}

// Mutation returns the AppMutation object of the builder.
func (_u *AppUpdate) Mutation() *AppMutation {
	return _u.mutation
}

// ClearTargets clears all "targets" edges to the Target entity.
func (_u *AppUpdate) ClearTargets() *AppUpdate {
	_u.mutation.ClearTargets()
	return _u
}

// RemoveTargetIDs removes the "targets" edge to Target entities by IDs.
func (_u *AppUpdate) RemoveTargetIDs(ids ...string) *AppUpdate {
	_u.mutation.RemoveTargetIDs(ids...)
	return _u
}

// RemoveTargets removes "targets" edges to Target entities.
func (_u *AppUpdate) RemoveTargets(v ...*Target) *AppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTargetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := app.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := app.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "App.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AppUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(app.Table, app.Columns, sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(app.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(app.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastModified(); ok {
		_spec.SetField(app.FieldLastModified, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastModified(); ok {
		_spec.AddField(app.FieldLastModified, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PriceChangeNumber(); ok {
		_spec.SetField(app.FieldPriceChangeNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceChangeNumber(); ok {
		_spec.AddField(app.FieldPriceChangeNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(app.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.TargetsTable,
			Columns: []string{app.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTargetsIDs(); len(nodes) > 0 && !_u.mutation.TargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.TargetsTable,
			Columns: []string{app.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.TargetsTable,
			Columns: []string{app.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{app.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppUpdateOne is the builder for updating a single App entity.
type AppUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppMutation
}

// SetName sets the "name" field.
func (_u *AppUpdateOne) SetName(v string) *AppUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableName(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AppUpdateOne) SetType(v string) *AppUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableType(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetLastModified sets the "last_modified" field.
func (_u *AppUpdateOne) SetLastModified(v int64) *AppUpdateOne {
	_u.mutation.ResetLastModified()
	_u.mutation.SetLastModified(v)
	return _u
}

// SetNillableLastModified sets the "last_modified" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableLastModified(v *int64) *AppUpdateOne {
	if v != nil {
		_u.SetLastModified(*v)
	}
	return _u
}

// AddLastModified adds value to the "last_modified" field.
func (_u *AppUpdateOne) AddLastModified(v int64) *AppUpdateOne {
	_u.mutation.AddLastModified(v)
	return _u
}

// SetPriceChangeNumber sets the "price_change_number" field.
func (_u *AppUpdateOne) SetPriceChangeNumber(v int64) *AppUpdateOne {
	_u.mutation.ResetPriceChangeNumber()
	_u.mutation.SetPriceChangeNumber(v)
	return _u
}

// SetNillablePriceChangeNumber sets the "price_change_number" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillablePriceChangeNumber(v *int64) *AppUpdateOne {
	if v != nil {
		_u.SetPriceChangeNumber(*v)
	}
	return _u
}

// AddPriceChangeNumber adds value to the "price_change_number" field.
func (_u *AppUpdateOne) AddPriceChangeNumber(v int64) *AppUpdateOne {
	_u.mutation.AddPriceChangeNumber(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppUpdateOne) SetUpdatedAt(v time.Time) *AppUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTargetIDs adds the "targets" edge to the Target entity by IDs.
func (_u *AppUpdateOne) AddTargetIDs(ids ...string) *AppUpdateOne {
	_u.mutation.AddTargetIDs(ids...)
	return _u
}

// AddTargets adds the "targets" edges to the Target entity.
func (_u *AppUpdateOne) AddTargets(v ...*Target) *AppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTargetIDs(ids...)
}

// Mutation returns the AppMutation object of the builder.
func (_u *AppUpdateOne) Mutation() *AppMutation {
	return _u.mutation
}

// ClearTargets clears all "targets" edges to the Target entity.
func (_u *AppUpdateOne) ClearTargets() *AppUpdateOne {
	_u.mutation.ClearTargets()
	return _u
}

// RemoveTargetIDs removes the "targets" edge to Target entities by IDs.
func (_u *AppUpdateOne) RemoveTargetIDs(ids ...string) *AppUpdateOne {
	_u.mutation.RemoveTargetIDs(ids...)
	return _u
}

// RemoveTargets removes "targets" edges to Target entities.
func (_u *AppUpdateOne) RemoveTargets(v ...*Target) *AppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTargetIDs(ids...)
}

// Where appends a list predicates to the AppUpdate builder.
func (_u *AppUpdateOne) Where(ps ...predicate.App) *AppUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppUpdateOne) Select(field string, fields ...string) *AppUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated App entity.
func (_u *AppUpdateOne) Save(ctx context.Context) (*App, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppUpdateOne) SaveX(ctx context.Context) *App {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := app.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := app.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "App.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AppUpdateOne) sqlSave(ctx context.Context) (_node *App, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(app.Table, app.Columns, sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "App.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, app.FieldID)
		for _, f := range fields {
			if !app.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != app.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(app.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(app.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastModified(); ok {
		_spec.SetField(app.FieldLastModified, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastModified(); ok {
		_spec.AddField(app.FieldLastModified, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PriceChangeNumber(); ok {
		_spec.SetField(app.FieldPriceChangeNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceChangeNumber(); ok {
		_spec.AddField(app.FieldPriceChangeNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(app.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.TargetsTable,
			Columns: []string{app.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTargetsIDs(); len(nodes) > 0 && !_u.mutation.TargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.TargetsTable,
			Columns: []string{app.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.TargetsTable,
			Columns: []string{app.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &App{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{app.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
