// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/depthbomb/dealfox/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/depthbomb/dealfox/ent/app"
	"github.com/depthbomb/dealfox/ent/delivery"
	"github.com/depthbomb/dealfox/ent/event"
	"github.com/depthbomb/dealfox/ent/freedelivery"
	"github.com/depthbomb/dealfox/ent/freemonitor"
	"github.com/depthbomb/dealfox/ent/freeoffer"
	"github.com/depthbomb/dealfox/ent/freesubscription"
	"github.com/depthbomb/dealfox/ent/observation"
	"github.com/depthbomb/dealfox/ent/rule"
	"github.com/depthbomb/dealfox/ent/target"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// App is the client for interacting with the App builders.
	App *AppClient
	// Delivery is the client for interacting with the Delivery builders.
	Delivery *DeliveryClient
	// Event is the client for interacting with the Event builders.
	Event *EventClient
	// FreeDelivery is the client for interacting with the FreeDelivery builders.
	FreeDelivery *FreeDeliveryClient
	// FreeMonitor is the client for interacting with the FreeMonitor builders.
	FreeMonitor *FreeMonitorClient
	// FreeOffer is the client for interacting with the FreeOffer builders.
	FreeOffer *FreeOfferClient
	// FreeSubscription is the client for interacting with the FreeSubscription builders.
	FreeSubscription *FreeSubscriptionClient
	// Observation is the client for interacting with the Observation builders.
	Observation *ObservationClient
	// Rule is the client for interacting with the Rule builders.
	Rule *RuleClient
	// Target is the client for interacting with the Target builders.
	Target *TargetClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.App = NewAppClient(c.config)
	c.Delivery = NewDeliveryClient(c.config)
	c.Event = NewEventClient(c.config)
	c.FreeDelivery = NewFreeDeliveryClient(c.config)
	c.FreeMonitor = NewFreeMonitorClient(c.config)
	c.FreeOffer = NewFreeOfferClient(c.config)
	c.FreeSubscription = NewFreeSubscriptionClient(c.config)
	c.Observation = NewObservationClient(c.config)
	c.Rule = NewRuleClient(c.config)
	c.Target = NewTargetClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		App:              NewAppClient(cfg),
		Delivery:         NewDeliveryClient(cfg),
		Event:            NewEventClient(cfg),
		FreeDelivery:     NewFreeDeliveryClient(cfg),
		FreeMonitor:      NewFreeMonitorClient(cfg),
		FreeOffer:        NewFreeOfferClient(cfg),
		FreeSubscription: NewFreeSubscriptionClient(cfg),
		Observation:      NewObservationClient(cfg),
		Rule:             NewRuleClient(cfg),
		Target:           NewTargetClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		App:              NewAppClient(cfg),
		Delivery:         NewDeliveryClient(cfg),
		Event:            NewEventClient(cfg),
		FreeDelivery:     NewFreeDeliveryClient(cfg),
		FreeMonitor:      NewFreeMonitorClient(cfg),
		FreeOffer:        NewFreeOfferClient(cfg),
		FreeSubscription: NewFreeSubscriptionClient(cfg),
		Observation:      NewObservationClient(cfg),
		Rule:             NewRuleClient(cfg),
		Target:           NewTargetClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		App.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.App, c.Delivery, c.Event, c.FreeDelivery, c.FreeMonitor, c.FreeOffer,
		c.FreeSubscription, c.Observation, c.Rule, c.Target,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.App, c.Delivery, c.Event, c.FreeDelivery, c.FreeMonitor, c.FreeOffer,
		c.FreeSubscription, c.Observation, c.Rule, c.Target,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AppMutation:
		return c.App.mutate(ctx, m)
	case *DeliveryMutation:
		return c.Delivery.mutate(ctx, m)
	case *EventMutation:
		return c.Event.mutate(ctx, m)
	case *FreeDeliveryMutation:
		return c.FreeDelivery.mutate(ctx, m)
	case *FreeMonitorMutation:
		return c.FreeMonitor.mutate(ctx, m)
	case *FreeOfferMutation:
		return c.FreeOffer.mutate(ctx, m)
	case *FreeSubscriptionMutation:
		return c.FreeSubscription.mutate(ctx, m)
	case *ObservationMutation:
		return c.Observation.mutate(ctx, m)
	case *RuleMutation:
		return c.Rule.mutate(ctx, m)
	case *TargetMutation:
		return c.Target.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AppClient is a client for the App schema.
type AppClient struct {
	config
}

// NewAppClient returns a client for the App from the given config.
func NewAppClient(c config) *AppClient {
	return &AppClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `app.Hooks(f(g(h())))`.
func (c *AppClient) Use(hooks ...Hook) {
	c.hooks.App = append(c.hooks.App, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `app.Intercept(f(g(h())))`.
func (c *AppClient) Intercept(interceptors ...Interceptor) {
	c.inters.App = append(c.inters.App, interceptors...)
}

// Create returns a builder for creating a App entity.
func (c *AppClient) Create() *AppCreate {
	mutation := newAppMutation(c.config, OpCreate)
	return &AppCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of App entities.
func (c *AppClient) CreateBulk(builders ...*AppCreate) *AppCreateBulk {
	return &AppCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AppClient) MapCreateBulk(slice any, setFunc func(*AppCreate, int)) *AppCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AppCreateBulk{err: fmt.Errorf("calling to AppClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AppCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AppCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for App.
func (c *AppClient) Update() *AppUpdate {
	mutation := newAppMutation(c.config, OpUpdate)
	return &AppUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppClient) UpdateOne(_m *App) *AppUpdateOne {
	mutation := newAppMutation(c.config, OpUpdateOne, withApp(_m))
	return &AppUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppClient) UpdateOneID(id int64) *AppUpdateOne {
	mutation := newAppMutation(c.config, OpUpdateOne, withAppID(id))
	return &AppUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for App.
func (c *AppClient) Delete() *AppDelete {
	mutation := newAppMutation(c.config, OpDelete)
	return &AppDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AppClient) DeleteOne(_m *App) *AppDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AppClient) DeleteOneID(id int64) *AppDeleteOne {
	builder := c.Delete().Where(app.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppDeleteOne{builder}
}

// Query returns a query builder for App.
func (c *AppClient) Query() *AppQuery {
	return &AppQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeApp},
		inters: c.Interceptors(),
	}
}

// Get returns a App entity by its id.
func (c *AppClient) Get(ctx context.Context, id int64) (*App, error) {
	return c.Query().Where(app.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppClient) GetX(ctx context.Context, id int64) *App {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTargets queries the targets edge of a App.
func (c *AppClient) QueryTargets(_m *App) *TargetQuery {
	query := (&TargetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(app.Table, app.FieldID, id),
			sqlgraph.To(target.Table, target.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, app.TargetsTable, app.TargetsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AppClient) Hooks() []Hook {
	return c.hooks.App
}

// Interceptors returns the client interceptors.
func (c *AppClient) Interceptors() []Interceptor {
	return c.inters.App
}

func (c *AppClient) mutate(ctx context.Context, m *AppMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AppCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AppUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AppUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AppDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown App mutation op: %q", m.Op())
	}
}

// DeliveryClient is a client for the Delivery schema.
type DeliveryClient struct {
	config
}

// NewDeliveryClient returns a client for the Delivery from the given config.
func NewDeliveryClient(c config) *DeliveryClient {
	return &DeliveryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `delivery.Hooks(f(g(h())))`.
func (c *DeliveryClient) Use(hooks ...Hook) {
	c.hooks.Delivery = append(c.hooks.Delivery, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `delivery.Intercept(f(g(h())))`.
func (c *DeliveryClient) Intercept(interceptors ...Interceptor) {
	c.inters.Delivery = append(c.inters.Delivery, interceptors...)
}

// Create returns a builder for creating a Delivery entity.
func (c *DeliveryClient) Create() *DeliveryCreate {
	mutation := newDeliveryMutation(c.config, OpCreate)
	return &DeliveryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Delivery entities.
func (c *DeliveryClient) CreateBulk(builders ...*DeliveryCreate) *DeliveryCreateBulk {
	return &DeliveryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DeliveryClient) MapCreateBulk(slice any, setFunc func(*DeliveryCreate, int)) *DeliveryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DeliveryCreateBulk{err: fmt.Errorf("calling to DeliveryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DeliveryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DeliveryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Delivery.
func (c *DeliveryClient) Update() *DeliveryUpdate {
	mutation := newDeliveryMutation(c.config, OpUpdate)
	return &DeliveryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DeliveryClient) UpdateOne(_m *Delivery) *DeliveryUpdateOne {
	mutation := newDeliveryMutation(c.config, OpUpdateOne, withDelivery(_m))
	return &DeliveryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DeliveryClient) UpdateOneID(id string) *DeliveryUpdateOne {
	mutation := newDeliveryMutation(c.config, OpUpdateOne, withDeliveryID(id))
	return &DeliveryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Delivery.
func (c *DeliveryClient) Delete() *DeliveryDelete {
	mutation := newDeliveryMutation(c.config, OpDelete)
	return &DeliveryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DeliveryClient) DeleteOne(_m *Delivery) *DeliveryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DeliveryClient) DeleteOneID(id string) *DeliveryDeleteOne {
	builder := c.Delete().Where(delivery.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DeliveryDeleteOne{builder}
}

// Query returns a query builder for Delivery.
func (c *DeliveryClient) Query() *DeliveryQuery {
	return &DeliveryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDelivery},
		inters: c.Interceptors(),
	}
}

// Get returns a Delivery entity by its id.
func (c *DeliveryClient) Get(ctx context.Context, id string) (*Delivery, error) {
	return c.Query().Where(delivery.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DeliveryClient) GetX(ctx context.Context, id string) *Delivery {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEvent queries the event edge of a Delivery.
func (c *DeliveryClient) QueryEvent(_m *Delivery) *EventQuery {
	query := (&EventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(delivery.Table, delivery.FieldID, id),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, delivery.EventTable, delivery.EventColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DeliveryClient) Hooks() []Hook {
	return c.hooks.Delivery
}

// Interceptors returns the client interceptors.
func (c *DeliveryClient) Interceptors() []Interceptor {
	return c.inters.Delivery
}

func (c *DeliveryClient) mutate(ctx context.Context, m *DeliveryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DeliveryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DeliveryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DeliveryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DeliveryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Delivery mutation op: %q", m.Op())
	}
}

// EventClient is a client for the Event schema.
type EventClient struct {
	config
}

// NewEventClient returns a client for the Event from the given config.
func NewEventClient(c config) *EventClient {
	return &EventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `event.Hooks(f(g(h())))`.
func (c *EventClient) Use(hooks ...Hook) {
	c.hooks.Event = append(c.hooks.Event, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `event.Intercept(f(g(h())))`.
func (c *EventClient) Intercept(interceptors ...Interceptor) {
	c.inters.Event = append(c.inters.Event, interceptors...)
}

// Create returns a builder for creating a Event entity.
func (c *EventClient) Create() *EventCreate {
	mutation := newEventMutation(c.config, OpCreate)
	return &EventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Event entities.
func (c *EventClient) CreateBulk(builders ...*EventCreate) *EventCreateBulk {
	return &EventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EventClient) MapCreateBulk(slice any, setFunc func(*EventCreate, int)) *EventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EventCreateBulk{err: fmt.Errorf("calling to EventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Event.
func (c *EventClient) Update() *EventUpdate {
	mutation := newEventMutation(c.config, OpUpdate)
	return &EventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EventClient) UpdateOne(_m *Event) *EventUpdateOne {
	mutation := newEventMutation(c.config, OpUpdateOne, withEvent(_m))
	return &EventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EventClient) UpdateOneID(id string) *EventUpdateOne {
	mutation := newEventMutation(c.config, OpUpdateOne, withEventID(id))
	return &EventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Event.
func (c *EventClient) Delete() *EventDelete {
	mutation := newEventMutation(c.config, OpDelete)
	return &EventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EventClient) DeleteOne(_m *Event) *EventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EventClient) DeleteOneID(id string) *EventDeleteOne {
	builder := c.Delete().Where(event.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EventDeleteOne{builder}
}

// Query returns a query builder for Event.
func (c *EventClient) Query() *EventQuery {
	return &EventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a Event entity by its id.
func (c *EventClient) Get(ctx context.Context, id string) (*Event, error) {
	return c.Query().Where(event.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EventClient) GetX(ctx context.Context, id string) *Event {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRule queries the rule edge of a Event.
func (c *EventClient) QueryRule(_m *Event) *RuleQuery {
	query := (&RuleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, id),
			sqlgraph.To(rule.Table, rule.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, event.RuleTable, event.RuleColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryObservation queries the observation edge of a Event.
func (c *EventClient) QueryObservation(_m *Event) *ObservationQuery {
	query := (&ObservationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, id),
			sqlgraph.To(observation.Table, observation.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, event.ObservationTable, event.ObservationColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDeliveries queries the deliveries edge of a Event.
func (c *EventClient) QueryDeliveries(_m *Event) *DeliveryQuery {
	query := (&DeliveryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, id),
			sqlgraph.To(delivery.Table, delivery.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, event.DeliveriesTable, event.DeliveriesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EventClient) Hooks() []Hook {
	return c.hooks.Event
}

// Interceptors returns the client interceptors.
func (c *EventClient) Interceptors() []Interceptor {
	return c.inters.Event
}

func (c *EventClient) mutate(ctx context.Context, m *EventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Event mutation op: %q", m.Op())
	}
}

// FreeDeliveryClient is a client for the FreeDelivery schema.
type FreeDeliveryClient struct {
	config
}

// NewFreeDeliveryClient returns a client for the FreeDelivery from the given config.
func NewFreeDeliveryClient(c config) *FreeDeliveryClient {
	return &FreeDeliveryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `freedelivery.Hooks(f(g(h())))`.
func (c *FreeDeliveryClient) Use(hooks ...Hook) {
	c.hooks.FreeDelivery = append(c.hooks.FreeDelivery, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `freedelivery.Intercept(f(g(h())))`.
func (c *FreeDeliveryClient) Intercept(interceptors ...Interceptor) {
	c.inters.FreeDelivery = append(c.inters.FreeDelivery, interceptors...)
}

// Create returns a builder for creating a FreeDelivery entity.
func (c *FreeDeliveryClient) Create() *FreeDeliveryCreate {
	mutation := newFreeDeliveryMutation(c.config, OpCreate)
	return &FreeDeliveryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FreeDelivery entities.
func (c *FreeDeliveryClient) CreateBulk(builders ...*FreeDeliveryCreate) *FreeDeliveryCreateBulk {
	return &FreeDeliveryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FreeDeliveryClient) MapCreateBulk(slice any, setFunc func(*FreeDeliveryCreate, int)) *FreeDeliveryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FreeDeliveryCreateBulk{err: fmt.Errorf("calling to FreeDeliveryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FreeDeliveryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FreeDeliveryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FreeDelivery.
func (c *FreeDeliveryClient) Update() *FreeDeliveryUpdate {
	mutation := newFreeDeliveryMutation(c.config, OpUpdate)
	return &FreeDeliveryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FreeDeliveryClient) UpdateOne(_m *FreeDelivery) *FreeDeliveryUpdateOne {
	mutation := newFreeDeliveryMutation(c.config, OpUpdateOne, withFreeDelivery(_m))
	return &FreeDeliveryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FreeDeliveryClient) UpdateOneID(id string) *FreeDeliveryUpdateOne {
	mutation := newFreeDeliveryMutation(c.config, OpUpdateOne, withFreeDeliveryID(id))
	return &FreeDeliveryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FreeDelivery.
func (c *FreeDeliveryClient) Delete() *FreeDeliveryDelete {
	mutation := newFreeDeliveryMutation(c.config, OpDelete)
	return &FreeDeliveryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FreeDeliveryClient) DeleteOne(_m *FreeDelivery) *FreeDeliveryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FreeDeliveryClient) DeleteOneID(id string) *FreeDeliveryDeleteOne {
	builder := c.Delete().Where(freedelivery.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FreeDeliveryDeleteOne{builder}
}

// Query returns a query builder for FreeDelivery.
func (c *FreeDeliveryClient) Query() *FreeDeliveryQuery {
	return &FreeDeliveryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFreeDelivery},
		inters: c.Interceptors(),
	}
}

// Get returns a FreeDelivery entity by its id.
func (c *FreeDeliveryClient) Get(ctx context.Context, id string) (*FreeDelivery, error) {
	return c.Query().Where(freedelivery.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FreeDeliveryClient) GetX(ctx context.Context, id string) *FreeDelivery {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FreeDeliveryClient) Hooks() []Hook {
	return c.hooks.FreeDelivery
}

// Interceptors returns the client interceptors.
func (c *FreeDeliveryClient) Interceptors() []Interceptor {
	return c.inters.FreeDelivery
}

func (c *FreeDeliveryClient) mutate(ctx context.Context, m *FreeDeliveryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FreeDeliveryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FreeDeliveryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FreeDeliveryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FreeDeliveryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FreeDelivery mutation op: %q", m.Op())
	}
}

// FreeMonitorClient is a client for the FreeMonitor schema.
type FreeMonitorClient struct {
	config
}

// NewFreeMonitorClient returns a client for the FreeMonitor from the given config.
func NewFreeMonitorClient(c config) *FreeMonitorClient {
	return &FreeMonitorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `freemonitor.Hooks(f(g(h())))`.
func (c *FreeMonitorClient) Use(hooks ...Hook) {
	c.hooks.FreeMonitor = append(c.hooks.FreeMonitor, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `freemonitor.Intercept(f(g(h())))`.
func (c *FreeMonitorClient) Intercept(interceptors ...Interceptor) {
	c.inters.FreeMonitor = append(c.inters.FreeMonitor, interceptors...)
}

// Create returns a builder for creating a FreeMonitor entity.
func (c *FreeMonitorClient) Create() *FreeMonitorCreate {
	mutation := newFreeMonitorMutation(c.config, OpCreate)
	return &FreeMonitorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FreeMonitor entities.
func (c *FreeMonitorClient) CreateBulk(builders ...*FreeMonitorCreate) *FreeMonitorCreateBulk {
	return &FreeMonitorCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FreeMonitorClient) MapCreateBulk(slice any, setFunc func(*FreeMonitorCreate, int)) *FreeMonitorCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FreeMonitorCreateBulk{err: fmt.Errorf("calling to FreeMonitorClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FreeMonitorCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FreeMonitorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FreeMonitor.
func (c *FreeMonitorClient) Update() *FreeMonitorUpdate {
	mutation := newFreeMonitorMutation(c.config, OpUpdate)
	return &FreeMonitorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FreeMonitorClient) UpdateOne(_m *FreeMonitor) *FreeMonitorUpdateOne {
	mutation := newFreeMonitorMutation(c.config, OpUpdateOne, withFreeMonitor(_m))
	return &FreeMonitorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FreeMonitorClient) UpdateOneID(id string) *FreeMonitorUpdateOne {
	mutation := newFreeMonitorMutation(c.config, OpUpdateOne, withFreeMonitorID(id))
	return &FreeMonitorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FreeMonitor.
func (c *FreeMonitorClient) Delete() *FreeMonitorDelete {
	mutation := newFreeMonitorMutation(c.config, OpDelete)
	return &FreeMonitorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FreeMonitorClient) DeleteOne(_m *FreeMonitor) *FreeMonitorDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FreeMonitorClient) DeleteOneID(id string) *FreeMonitorDeleteOne {
	builder := c.Delete().Where(freemonitor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FreeMonitorDeleteOne{builder}
}

// Query returns a query builder for FreeMonitor.
func (c *FreeMonitorClient) Query() *FreeMonitorQuery {
	return &FreeMonitorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFreeMonitor},
		inters: c.Interceptors(),
	}
}

// Get returns a FreeMonitor entity by its id.
func (c *FreeMonitorClient) Get(ctx context.Context, id string) (*FreeMonitor, error) {
	return c.Query().Where(freemonitor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FreeMonitorClient) GetX(ctx context.Context, id string) *FreeMonitor {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FreeMonitorClient) Hooks() []Hook {
	return c.hooks.FreeMonitor
}

// Interceptors returns the client interceptors.
func (c *FreeMonitorClient) Interceptors() []Interceptor {
	return c.inters.FreeMonitor
}

func (c *FreeMonitorClient) mutate(ctx context.Context, m *FreeMonitorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FreeMonitorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FreeMonitorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FreeMonitorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FreeMonitorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FreeMonitor mutation op: %q", m.Op())
	}
}

// FreeOfferClient is a client for the FreeOffer schema.
type FreeOfferClient struct {
	config
}

// NewFreeOfferClient returns a client for the FreeOffer from the given config.
func NewFreeOfferClient(c config) *FreeOfferClient {
	return &FreeOfferClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `freeoffer.Hooks(f(g(h())))`.
func (c *FreeOfferClient) Use(hooks ...Hook) {
	c.hooks.FreeOffer = append(c.hooks.FreeOffer, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `freeoffer.Intercept(f(g(h())))`.
func (c *FreeOfferClient) Intercept(interceptors ...Interceptor) {
	c.inters.FreeOffer = append(c.inters.FreeOffer, interceptors...)
}

// Create returns a builder for creating a FreeOffer entity.
func (c *FreeOfferClient) Create() *FreeOfferCreate {
	mutation := newFreeOfferMutation(c.config, OpCreate)
	return &FreeOfferCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FreeOffer entities.
func (c *FreeOfferClient) CreateBulk(builders ...*FreeOfferCreate) *FreeOfferCreateBulk {
	return &FreeOfferCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FreeOfferClient) MapCreateBulk(slice any, setFunc func(*FreeOfferCreate, int)) *FreeOfferCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FreeOfferCreateBulk{err: fmt.Errorf("calling to FreeOfferClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FreeOfferCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FreeOfferCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FreeOffer.
func (c *FreeOfferClient) Update() *FreeOfferUpdate {
	mutation := newFreeOfferMutation(c.config, OpUpdate)
	return &FreeOfferUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FreeOfferClient) UpdateOne(_m *FreeOffer) *FreeOfferUpdateOne {
	mutation := newFreeOfferMutation(c.config, OpUpdateOne, withFreeOffer(_m))
	return &FreeOfferUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FreeOfferClient) UpdateOneID(id string) *FreeOfferUpdateOne {
	mutation := newFreeOfferMutation(c.config, OpUpdateOne, withFreeOfferID(id))
	return &FreeOfferUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FreeOffer.
func (c *FreeOfferClient) Delete() *FreeOfferDelete {
	mutation := newFreeOfferMutation(c.config, OpDelete)
	return &FreeOfferDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FreeOfferClient) DeleteOne(_m *FreeOffer) *FreeOfferDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FreeOfferClient) DeleteOneID(id string) *FreeOfferDeleteOne {
	builder := c.Delete().Where(freeoffer.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FreeOfferDeleteOne{builder}
}

// Query returns a query builder for FreeOffer.
func (c *FreeOfferClient) Query() *FreeOfferQuery {
	return &FreeOfferQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFreeOffer},
		inters: c.Interceptors(),
	}
}

// Get returns a FreeOffer entity by its id.
func (c *FreeOfferClient) Get(ctx context.Context, id string) (*FreeOffer, error) {
	return c.Query().Where(freeoffer.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FreeOfferClient) GetX(ctx context.Context, id string) *FreeOffer {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FreeOfferClient) Hooks() []Hook {
	return c.hooks.FreeOffer
}

// Interceptors returns the client interceptors.
func (c *FreeOfferClient) Interceptors() []Interceptor {
	return c.inters.FreeOffer
}

func (c *FreeOfferClient) mutate(ctx context.Context, m *FreeOfferMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FreeOfferCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FreeOfferUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FreeOfferUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FreeOfferDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FreeOffer mutation op: %q", m.Op())
	}
}

// FreeSubscriptionClient is a client for the FreeSubscription schema.
type FreeSubscriptionClient struct {
	config
}

// NewFreeSubscriptionClient returns a client for the FreeSubscription from the given config.
func NewFreeSubscriptionClient(c config) *FreeSubscriptionClient {
	return &FreeSubscriptionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `freesubscription.Hooks(f(g(h())))`.
func (c *FreeSubscriptionClient) Use(hooks ...Hook) {
	c.hooks.FreeSubscription = append(c.hooks.FreeSubscription, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `freesubscription.Intercept(f(g(h())))`.
func (c *FreeSubscriptionClient) Intercept(interceptors ...Interceptor) {
	c.inters.FreeSubscription = append(c.inters.FreeSubscription, interceptors...)
}

// Create returns a builder for creating a FreeSubscription entity.
func (c *FreeSubscriptionClient) Create() *FreeSubscriptionCreate {
	mutation := newFreeSubscriptionMutation(c.config, OpCreate)
	return &FreeSubscriptionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FreeSubscription entities.
func (c *FreeSubscriptionClient) CreateBulk(builders ...*FreeSubscriptionCreate) *FreeSubscriptionCreateBulk {
	return &FreeSubscriptionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FreeSubscriptionClient) MapCreateBulk(slice any, setFunc func(*FreeSubscriptionCreate, int)) *FreeSubscriptionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FreeSubscriptionCreateBulk{err: fmt.Errorf("calling to FreeSubscriptionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FreeSubscriptionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FreeSubscriptionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FreeSubscription.
func (c *FreeSubscriptionClient) Update() *FreeSubscriptionUpdate {
	mutation := newFreeSubscriptionMutation(c.config, OpUpdate)
	return &FreeSubscriptionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FreeSubscriptionClient) UpdateOne(_m *FreeSubscription) *FreeSubscriptionUpdateOne {
	mutation := newFreeSubscriptionMutation(c.config, OpUpdateOne, withFreeSubscription(_m))
	return &FreeSubscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FreeSubscriptionClient) UpdateOneID(id string) *FreeSubscriptionUpdateOne {
	mutation := newFreeSubscriptionMutation(c.config, OpUpdateOne, withFreeSubscriptionID(id))
	return &FreeSubscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FreeSubscription.
func (c *FreeSubscriptionClient) Delete() *FreeSubscriptionDelete {
	mutation := newFreeSubscriptionMutation(c.config, OpDelete)
	return &FreeSubscriptionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FreeSubscriptionClient) DeleteOne(_m *FreeSubscription) *FreeSubscriptionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FreeSubscriptionClient) DeleteOneID(id string) *FreeSubscriptionDeleteOne {
	builder := c.Delete().Where(freesubscription.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FreeSubscriptionDeleteOne{builder}
}

// Query returns a query builder for FreeSubscription.
func (c *FreeSubscriptionClient) Query() *FreeSubscriptionQuery {
	return &FreeSubscriptionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFreeSubscription},
		inters: c.Interceptors(),
	}
}

// Get returns a FreeSubscription entity by its id.
func (c *FreeSubscriptionClient) Get(ctx context.Context, id string) (*FreeSubscription, error) {
	return c.Query().Where(freesubscription.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FreeSubscriptionClient) GetX(ctx context.Context, id string) *FreeSubscription {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FreeSubscriptionClient) Hooks() []Hook {
	return c.hooks.FreeSubscription
}

// Interceptors returns the client interceptors.
func (c *FreeSubscriptionClient) Interceptors() []Interceptor {
	return c.inters.FreeSubscription
}

func (c *FreeSubscriptionClient) mutate(ctx context.Context, m *FreeSubscriptionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FreeSubscriptionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FreeSubscriptionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FreeSubscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FreeSubscriptionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FreeSubscription mutation op: %q", m.Op())
	}
}

// ObservationClient is a client for the Observation schema.
type ObservationClient struct {
	config
}

// NewObservationClient returns a client for the Observation from the given config.
func NewObservationClient(c config) *ObservationClient {
	return &ObservationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `observation.Hooks(f(g(h())))`.
func (c *ObservationClient) Use(hooks ...Hook) {
	c.hooks.Observation = append(c.hooks.Observation, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `observation.Intercept(f(g(h())))`.
func (c *ObservationClient) Intercept(interceptors ...Interceptor) {
	c.inters.Observation = append(c.inters.Observation, interceptors...)
}

// Create returns a builder for creating a Observation entity.
func (c *ObservationClient) Create() *ObservationCreate {
	mutation := newObservationMutation(c.config, OpCreate)
	return &ObservationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Observation entities.
func (c *ObservationClient) CreateBulk(builders ...*ObservationCreate) *ObservationCreateBulk {
	return &ObservationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ObservationClient) MapCreateBulk(slice any, setFunc func(*ObservationCreate, int)) *ObservationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ObservationCreateBulk{err: fmt.Errorf("calling to ObservationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ObservationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ObservationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Observation.
func (c *ObservationClient) Update() *ObservationUpdate {
	mutation := newObservationMutation(c.config, OpUpdate)
	return &ObservationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ObservationClient) UpdateOne(_m *Observation) *ObservationUpdateOne {
	mutation := newObservationMutation(c.config, OpUpdateOne, withObservation(_m))
	return &ObservationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ObservationClient) UpdateOneID(id string) *ObservationUpdateOne {
	mutation := newObservationMutation(c.config, OpUpdateOne, withObservationID(id))
	return &ObservationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Observation.
func (c *ObservationClient) Delete() *ObservationDelete {
	mutation := newObservationMutation(c.config, OpDelete)
	return &ObservationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ObservationClient) DeleteOne(_m *Observation) *ObservationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ObservationClient) DeleteOneID(id string) *ObservationDeleteOne {
	builder := c.Delete().Where(observation.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ObservationDeleteOne{builder}
}

// Query returns a query builder for Observation.
func (c *ObservationClient) Query() *ObservationQuery {
	return &ObservationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeObservation},
		inters: c.Interceptors(),
	}
}

// Get returns a Observation entity by its id.
func (c *ObservationClient) Get(ctx context.Context, id string) (*Observation, error) {
	return c.Query().Where(observation.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ObservationClient) GetX(ctx context.Context, id string) *Observation {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTarget queries the target edge of a Observation.
func (c *ObservationClient) QueryTarget(_m *Observation) *TargetQuery {
	query := (&TargetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(observation.Table, observation.FieldID, id),
			sqlgraph.To(target.Table, target.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, observation.TargetTable, observation.TargetColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvents queries the events edge of a Observation.
func (c *ObservationClient) QueryEvents(_m *Observation) *EventQuery {
	query := (&EventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(observation.Table, observation.FieldID, id),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, observation.EventsTable, observation.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ObservationClient) Hooks() []Hook {
	return c.hooks.Observation
}

// Interceptors returns the client interceptors.
func (c *ObservationClient) Interceptors() []Interceptor {
	return c.inters.Observation
}

func (c *ObservationClient) mutate(ctx context.Context, m *ObservationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ObservationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ObservationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ObservationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ObservationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Observation mutation op: %q", m.Op())
	}
}

// RuleClient is a client for the Rule schema.
type RuleClient struct {
	config
}

// NewRuleClient returns a client for the Rule from the given config.
func NewRuleClient(c config) *RuleClient {
	return &RuleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `rule.Hooks(f(g(h())))`.
func (c *RuleClient) Use(hooks ...Hook) {
	c.hooks.Rule = append(c.hooks.Rule, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `rule.Intercept(f(g(h())))`.
func (c *RuleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Rule = append(c.inters.Rule, interceptors...)
}

// Create returns a builder for creating a Rule entity.
func (c *RuleClient) Create() *RuleCreate {
	mutation := newRuleMutation(c.config, OpCreate)
	return &RuleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Rule entities.
func (c *RuleClient) CreateBulk(builders ...*RuleCreate) *RuleCreateBulk {
	return &RuleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RuleClient) MapCreateBulk(slice any, setFunc func(*RuleCreate, int)) *RuleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RuleCreateBulk{err: fmt.Errorf("calling to RuleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RuleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RuleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Rule.
func (c *RuleClient) Update() *RuleUpdate {
	mutation := newRuleMutation(c.config, OpUpdate)
	return &RuleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RuleClient) UpdateOne(_m *Rule) *RuleUpdateOne {
	mutation := newRuleMutation(c.config, OpUpdateOne, withRule(_m))
	return &RuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RuleClient) UpdateOneID(id string) *RuleUpdateOne {
	mutation := newRuleMutation(c.config, OpUpdateOne, withRuleID(id))
	return &RuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Rule.
func (c *RuleClient) Delete() *RuleDelete {
	mutation := newRuleMutation(c.config, OpDelete)
	return &RuleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RuleClient) DeleteOne(_m *Rule) *RuleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RuleClient) DeleteOneID(id string) *RuleDeleteOne {
	builder := c.Delete().Where(rule.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RuleDeleteOne{builder}
}

// Query returns a query builder for Rule.
func (c *RuleClient) Query() *RuleQuery {
	return &RuleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRule},
		inters: c.Interceptors(),
	}
}

// Get returns a Rule entity by its id.
func (c *RuleClient) Get(ctx context.Context, id string) (*Rule, error) {
	return c.Query().Where(rule.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RuleClient) GetX(ctx context.Context, id string) *Rule {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTarget queries the target edge of a Rule.
func (c *RuleClient) QueryTarget(_m *Rule) *TargetQuery {
	query := (&TargetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(rule.Table, rule.FieldID, id),
			sqlgraph.To(target.Table, target.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, rule.TargetTable, rule.TargetColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvents queries the events edge of a Rule.
func (c *RuleClient) QueryEvents(_m *Rule) *EventQuery {
	query := (&EventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(rule.Table, rule.FieldID, id),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, rule.EventsTable, rule.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RuleClient) Hooks() []Hook {
	return c.hooks.Rule
}

// Interceptors returns the client interceptors.
func (c *RuleClient) Interceptors() []Interceptor {
	return c.inters.Rule
}

func (c *RuleClient) mutate(ctx context.Context, m *RuleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RuleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RuleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RuleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Rule mutation op: %q", m.Op())
	}
}

// TargetClient is a client for the Target schema.
type TargetClient struct {
	config
}

// NewTargetClient returns a client for the Target from the given config.
func NewTargetClient(c config) *TargetClient {
	return &TargetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `target.Hooks(f(g(h())))`.
func (c *TargetClient) Use(hooks ...Hook) {
	c.hooks.Target = append(c.hooks.Target, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `target.Intercept(f(g(h())))`.
func (c *TargetClient) Intercept(interceptors ...Interceptor) {
	c.inters.Target = append(c.inters.Target, interceptors...)
}

// Create returns a builder for creating a Target entity.
func (c *TargetClient) Create() *TargetCreate {
	mutation := newTargetMutation(c.config, OpCreate)
	return &TargetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Target entities.
func (c *TargetClient) CreateBulk(builders ...*TargetCreate) *TargetCreateBulk {
	return &TargetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TargetClient) MapCreateBulk(slice any, setFunc func(*TargetCreate, int)) *TargetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TargetCreateBulk{err: fmt.Errorf("calling to TargetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TargetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TargetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Target.
func (c *TargetClient) Update() *TargetUpdate {
	mutation := newTargetMutation(c.config, OpUpdate)
	return &TargetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TargetClient) UpdateOne(_m *Target) *TargetUpdateOne {
	mutation := newTargetMutation(c.config, OpUpdateOne, withTarget(_m))
	return &TargetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TargetClient) UpdateOneID(id string) *TargetUpdateOne {
	mutation := newTargetMutation(c.config, OpUpdateOne, withTargetID(id))
	return &TargetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Target.
func (c *TargetClient) Delete() *TargetDelete {
	mutation := newTargetMutation(c.config, OpDelete)
	return &TargetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TargetClient) DeleteOne(_m *Target) *TargetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TargetClient) DeleteOneID(id string) *TargetDeleteOne {
	builder := c.Delete().Where(target.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TargetDeleteOne{builder}
}

// Query returns a query builder for Target.
func (c *TargetClient) Query() *TargetQuery {
	return &TargetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTarget},
		inters: c.Interceptors(),
	}
}

// Get returns a Target entity by its id.
func (c *TargetClient) Get(ctx context.Context, id string) (*Target, error) {
	return c.Query().Where(target.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TargetClient) GetX(ctx context.Context, id string) *Target {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryApp queries the app edge of a Target.
func (c *TargetClient) QueryApp(_m *Target) *AppQuery {
	query := (&AppClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(target.Table, target.FieldID, id),
			sqlgraph.To(app.Table, app.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, target.AppTable, target.AppColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRules queries the rules edge of a Target.
func (c *TargetClient) QueryRules(_m *Target) *RuleQuery {
	query := (&RuleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(target.Table, target.FieldID, id),
			sqlgraph.To(rule.Table, rule.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, target.RulesTable, target.RulesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryObservations queries the observations edge of a Target.
func (c *TargetClient) QueryObservations(_m *Target) *ObservationQuery {
	query := (&ObservationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(target.Table, target.FieldID, id),
			sqlgraph.To(observation.Table, observation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, target.ObservationsTable, target.ObservationsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TargetClient) Hooks() []Hook {
	return c.hooks.Target
}

// Interceptors returns the client interceptors.
func (c *TargetClient) Interceptors() []Interceptor {
	return c.inters.Target
}

func (c *TargetClient) mutate(ctx context.Context, m *TargetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TargetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TargetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TargetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TargetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Target mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		App, Delivery, Event, FreeDelivery, FreeMonitor, FreeOffer, FreeSubscription,
		Observation, Rule, Target []ent.Hook
	}
	inters struct {
		App, Delivery, Event, FreeDelivery, FreeMonitor, FreeOffer, FreeSubscription,
		Observation, Rule, Target []ent.Interceptor
	}
)
