// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/depthbomb/dealfox/ent/freedelivery"
	"github.com/depthbomb/dealfox/ent/predicate"
)

// FreeDeliveryDelete is the builder for deleting a FreeDelivery entity.
type FreeDeliveryDelete struct {
	config
	hooks    []Hook
	mutation *FreeDeliveryMutation
}

// Where appends a list predicates to the FreeDeliveryDelete builder.
func (_d *FreeDeliveryDelete) Where(ps ...predicate.FreeDelivery) *FreeDeliveryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FreeDeliveryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FreeDeliveryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FreeDeliveryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(freedelivery.Table, sqlgraph.NewFieldSpec(freedelivery.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FreeDeliveryDeleteOne is the builder for deleting a single FreeDelivery entity.
type FreeDeliveryDeleteOne struct {
	_d *FreeDeliveryDelete
}

// Where appends a list predicates to the FreeDeliveryDelete builder.
func (_d *FreeDeliveryDeleteOne) Where(ps ...predicate.FreeDelivery) *FreeDeliveryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FreeDeliveryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{freedelivery.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FreeDeliveryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
