// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/depthbomb/dealfox/ent/freedelivery"
	"github.com/depthbomb/dealfox/internal/freegames"
)

// FreeDelivery is the model entity for the FreeDelivery schema.
type FreeDelivery struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OfferID holds the value of the "offer_id" field.
	OfferID string `json:"offer_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID string `json:"subscription_id,omitempty"`
	// OfferGeneration holds the value of the "offer_generation" field.
	OfferGeneration int `json:"offer_generation,omitempty"`
	// DestinationKind holds the value of the "destination_kind" field.
	DestinationKind freedelivery.DestinationKind `json:"destination_kind,omitempty"`
	// DestinationID holds the value of the "destination_id" field.
	DestinationID string `json:"destination_id,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload freegames.Offer `json:"payload,omitempty"`
	// Status holds the value of the "status" field.
	Status freedelivery.Status `json:"status,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// NextAttemptAt holds the value of the "next_attempt_at" field.
	NextAttemptAt time.Time `json:"next_attempt_at,omitempty"`
	// MessageID holds the value of the "message_id" field.
	MessageID string `json:"message_id,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FreeDelivery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case freedelivery.FieldPayload:
			values[i] = new([]byte)
		case freedelivery.FieldOfferGeneration, freedelivery.FieldAttemptCount:
			values[i] = new(sql.NullInt64)
		case freedelivery.FieldID, freedelivery.FieldOfferID, freedelivery.FieldSubscriptionID, freedelivery.FieldDestinationKind, freedelivery.FieldDestinationID, freedelivery.FieldStatus, freedelivery.FieldMessageID, freedelivery.FieldLastError:
			values[i] = new(sql.NullString)
		case freedelivery.FieldNextAttemptAt, freedelivery.FieldCreatedAt, freedelivery.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FreeDelivery fields.
func (_m *FreeDelivery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case freedelivery.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case freedelivery.FieldOfferID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field offer_id", values[i])
			} else if value.Valid {
				_m.OfferID = value.String
			}
		case freedelivery.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = value.String
			}
		case freedelivery.FieldOfferGeneration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field offer_generation", values[i])
			} else if value.Valid {
				_m.OfferGeneration = int(value.Int64)
			}
		case freedelivery.FieldDestinationKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field destination_kind", values[i])
			} else if value.Valid {
				_m.DestinationKind = freedelivery.DestinationKind(value.String)
			}
		case freedelivery.FieldDestinationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field destination_id", values[i])
			} else if value.Valid {
				_m.DestinationID = value.String
			}
		case freedelivery.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case freedelivery.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = freedelivery.Status(value.String)
			}
		case freedelivery.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case freedelivery.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				_m.NextAttemptAt = value.Time
			}
		case freedelivery.FieldMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = value.String
			}
		case freedelivery.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case freedelivery.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case freedelivery.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FreeDelivery.
// This includes values selected through modifiers, order, etc.
func (_m *FreeDelivery) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FreeDelivery.
// Note that you need to call FreeDelivery.Unwrap() before calling this method if this FreeDelivery
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FreeDelivery) Update() *FreeDeliveryUpdateOne {
	return NewFreeDeliveryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FreeDelivery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FreeDelivery) Unwrap() *FreeDelivery {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FreeDelivery is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FreeDelivery) String() string {
	var builder strings.Builder
	builder.WriteString("FreeDelivery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("offer_id=")
	builder.WriteString(_m.OfferID)
	builder.WriteString(", ")
	builder.WriteString("subscription_id=")
	builder.WriteString(_m.SubscriptionID)
	builder.WriteString(", ")
	builder.WriteString("offer_generation=")
	builder.WriteString(fmt.Sprintf("%v", _m.OfferGeneration))
	builder.WriteString(", ")
	builder.WriteString("destination_kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.DestinationKind))
	builder.WriteString(", ")
	builder.WriteString("destination_id=")
	builder.WriteString(_m.DestinationID)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	builder.WriteString("next_attempt_at=")
	builder.WriteString(_m.NextAttemptAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("message_id=")
	builder.WriteString(_m.MessageID)
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FreeDeliveries is a parsable slice of FreeDelivery.
type FreeDeliveries []*FreeDelivery
