// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/depthbomb/dealfox/ent/freedelivery"
	"github.com/depthbomb/dealfox/ent/predicate"
	"github.com/depthbomb/dealfox/internal/freegames"
)

// FreeDeliveryUpdate is the builder for updating FreeDelivery entities.
type FreeDeliveryUpdate struct {
	config
	hooks    []Hook
	mutation *FreeDeliveryMutation
}

// Where appends a list predicates to the FreeDeliveryUpdate builder.
func (_u *FreeDeliveryUpdate) Where(ps ...predicate.FreeDelivery) *FreeDeliveryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOfferID sets the "offer_id" field.
func (_u *FreeDeliveryUpdate) SetOfferID(v string) *FreeDeliveryUpdate {
	_u.mutation.SetOfferID(v)
	return _u
}

// SetNillableOfferID sets the "offer_id" field if the given value is not nil.
func (_u *FreeDeliveryUpdate) SetNillableOfferID(v *string) *FreeDeliveryUpdate {
	if v != nil {
		_u.SetOfferID(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *FreeDeliveryUpdate) SetSubscriptionID(v string) *FreeDeliveryUpdate {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *FreeDeliveryUpdate) SetNillableSubscriptionID(v *string) *FreeDeliveryUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetOfferGeneration sets the "offer_generation" field.
func (_u *FreeDeliveryUpdate) SetOfferGeneration(v int) *FreeDeliveryUpdate {
	_u.mutation.ResetOfferGeneration()
	_u.mutation.SetOfferGeneration(v)
	return _u
}

// SetNillableOfferGeneration sets the "offer_generation" field if the given value is not nil.
func (_u *FreeDeliveryUpdate) SetNillableOfferGeneration(v *int) *FreeDeliveryUpdate {
	if v != nil {
		_u.SetOfferGeneration(*v)
	}
	return _u
}

// AddOfferGeneration adds value to the "offer_generation" field.
func (_u *FreeDeliveryUpdate) AddOfferGeneration(v int) *FreeDeliveryUpdate {
	_u.mutation.AddOfferGeneration(v)
	return _u
}

// SetDestinationKind sets the "destination_kind" field.
func (_u *FreeDeliveryUpdate) SetDestinationKind(v freedelivery.DestinationKind) *FreeDeliveryUpdate {
	_u.mutation.SetDestinationKind(v)
	return _u
}

// SetNillableDestinationKind sets the "destination_kind" field if the given value is not nil.
func (_u *FreeDeliveryUpdate) SetNillableDestinationKind(v *freedelivery.DestinationKind) *FreeDeliveryUpdate {
	if v != nil {
		_u.SetDestinationKind(*v)
	}
	return _u
}

// SetDestinationID sets the "destination_id" field.
func (_u *FreeDeliveryUpdate) SetDestinationID(v string) *FreeDeliveryUpdate {
	_u.mutation.SetDestinationID(v)
	return _u
}

// SetNillableDestinationID sets the "destination_id" field if the given value is not nil.
func (_u *FreeDeliveryUpdate) SetNillableDestinationID(v *string) *FreeDeliveryUpdate {
	if v != nil {
		_u.SetDestinationID(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *FreeDeliveryUpdate) SetPayload(v freegames.Offer) *FreeDeliveryUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *FreeDeliveryUpdate) SetNillablePayload(v *freegames.Offer) *FreeDeliveryUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FreeDeliveryUpdate) SetStatus(v freedelivery.Status) *FreeDeliveryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FreeDeliveryUpdate) SetNillableStatus(v *freedelivery.Status) *FreeDeliveryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *FreeDeliveryUpdate) SetAttemptCount(v int) *FreeDeliveryUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *FreeDeliveryUpdate) SetNillableAttemptCount(v *int) *FreeDeliveryUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *FreeDeliveryUpdate) AddAttemptCount(v int) *FreeDeliveryUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *FreeDeliveryUpdate) SetNextAttemptAt(v time.Time) *FreeDeliveryUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *FreeDeliveryUpdate) SetNillableNextAttemptAt(v *time.Time) *FreeDeliveryUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *FreeDeliveryUpdate) SetMessageID(v string) *FreeDeliveryUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *FreeDeliveryUpdate) SetNillableMessageID(v *string) *FreeDeliveryUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *FreeDeliveryUpdate) SetLastError(v string) *FreeDeliveryUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *FreeDeliveryUpdate) SetNillableLastError(v *string) *FreeDeliveryUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FreeDeliveryUpdate) SetUpdatedAt(v time.Time) *FreeDeliveryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FreeDeliveryMutation object of the builder.
func (_u *FreeDeliveryUpdate) Mutation() *FreeDeliveryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FreeDeliveryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FreeDeliveryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FreeDeliveryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FreeDeliveryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FreeDeliveryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := freedelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FreeDeliveryUpdate) check() error {
	if v, ok := _u.mutation.OfferID(); ok {
		if err := freedelivery.OfferIDValidator(v); err != nil {
			return &ValidationError{Name: "offer_id", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.offer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubscriptionID(); ok {
		if err := freedelivery.SubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "subscription_id", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.subscription_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OfferGeneration(); ok {
		if err := freedelivery.OfferGenerationValidator(v); err != nil {
			return &ValidationError{Name: "offer_generation", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.offer_generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DestinationKind(); ok {
		if err := freedelivery.DestinationKindValidator(v); err != nil {
			return &ValidationError{Name: "destination_kind", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.destination_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DestinationID(); ok {
		if err := freedelivery.DestinationIDValidator(v); err != nil {
			return &ValidationError{Name: "destination_id", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.destination_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := freedelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptCount(); ok {
		if err := freedelivery.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.attempt_count": %w`, err)}
		}
	}
	return nil
}

func (_u *FreeDeliveryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(freedelivery.Table, freedelivery.Columns, sqlgraph.NewFieldSpec(freedelivery.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OfferID(); ok {
		_spec.SetField(freedelivery.FieldOfferID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(freedelivery.FieldSubscriptionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OfferGeneration(); ok {
		_spec.SetField(freedelivery.FieldOfferGeneration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOfferGeneration(); ok {
		_spec.AddField(freedelivery.FieldOfferGeneration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DestinationKind(); ok {
		_spec.SetField(freedelivery.FieldDestinationKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DestinationID(); ok {
		_spec.SetField(freedelivery.FieldDestinationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(freedelivery.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(freedelivery.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(freedelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(freedelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(freedelivery.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(freedelivery.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(freedelivery.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(freedelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{freedelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FreeDeliveryUpdateOne is the builder for updating a single FreeDelivery entity.
type FreeDeliveryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FreeDeliveryMutation
}

// SetOfferID sets the "offer_id" field.
func (_u *FreeDeliveryUpdateOne) SetOfferID(v string) *FreeDeliveryUpdateOne {
	_u.mutation.SetOfferID(v)
	return _u
}

// SetNillableOfferID sets the "offer_id" field if the given value is not nil.
func (_u *FreeDeliveryUpdateOne) SetNillableOfferID(v *string) *FreeDeliveryUpdateOne {
	if v != nil {
		_u.SetOfferID(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *FreeDeliveryUpdateOne) SetSubscriptionID(v string) *FreeDeliveryUpdateOne {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *FreeDeliveryUpdateOne) SetNillableSubscriptionID(v *string) *FreeDeliveryUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetOfferGeneration sets the "offer_generation" field.
func (_u *FreeDeliveryUpdateOne) SetOfferGeneration(v int) *FreeDeliveryUpdateOne {
	_u.mutation.ResetOfferGeneration()
	_u.mutation.SetOfferGeneration(v)
	return _u
}

// SetNillableOfferGeneration sets the "offer_generation" field if the given value is not nil.
func (_u *FreeDeliveryUpdateOne) SetNillableOfferGeneration(v *int) *FreeDeliveryUpdateOne {
	if v != nil {
		_u.SetOfferGeneration(*v)
	}
	return _u
}

// AddOfferGeneration adds value to the "offer_generation" field.
func (_u *FreeDeliveryUpdateOne) AddOfferGeneration(v int) *FreeDeliveryUpdateOne {
	_u.mutation.AddOfferGeneration(v)
	return _u
}

// SetDestinationKind sets the "destination_kind" field.
func (_u *FreeDeliveryUpdateOne) SetDestinationKind(v freedelivery.DestinationKind) *FreeDeliveryUpdateOne {
	_u.mutation.SetDestinationKind(v)
	return _u
}

// SetNillableDestinationKind sets the "destination_kind" field if the given value is not nil.
func (_u *FreeDeliveryUpdateOne) SetNillableDestinationKind(v *freedelivery.DestinationKind) *FreeDeliveryUpdateOne {
	if v != nil {
		_u.SetDestinationKind(*v)
	}
	return _u
}

// SetDestinationID sets the "destination_id" field.
func (_u *FreeDeliveryUpdateOne) SetDestinationID(v string) *FreeDeliveryUpdateOne {
	_u.mutation.SetDestinationID(v)
	return _u
}

// SetNillableDestinationID sets the "destination_id" field if the given value is not nil.
func (_u *FreeDeliveryUpdateOne) SetNillableDestinationID(v *string) *FreeDeliveryUpdateOne {
	if v != nil {
		_u.SetDestinationID(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *FreeDeliveryUpdateOne) SetPayload(v freegames.Offer) *FreeDeliveryUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *FreeDeliveryUpdateOne) SetNillablePayload(v *freegames.Offer) *FreeDeliveryUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FreeDeliveryUpdateOne) SetStatus(v freedelivery.Status) *FreeDeliveryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FreeDeliveryUpdateOne) SetNillableStatus(v *freedelivery.Status) *FreeDeliveryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *FreeDeliveryUpdateOne) SetAttemptCount(v int) *FreeDeliveryUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *FreeDeliveryUpdateOne) SetNillableAttemptCount(v *int) *FreeDeliveryUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *FreeDeliveryUpdateOne) AddAttemptCount(v int) *FreeDeliveryUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *FreeDeliveryUpdateOne) SetNextAttemptAt(v time.Time) *FreeDeliveryUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *FreeDeliveryUpdateOne) SetNillableNextAttemptAt(v *time.Time) *FreeDeliveryUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *FreeDeliveryUpdateOne) SetMessageID(v string) *FreeDeliveryUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *FreeDeliveryUpdateOne) SetNillableMessageID(v *string) *FreeDeliveryUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *FreeDeliveryUpdateOne) SetLastError(v string) *FreeDeliveryUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *FreeDeliveryUpdateOne) SetNillableLastError(v *string) *FreeDeliveryUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FreeDeliveryUpdateOne) SetUpdatedAt(v time.Time) *FreeDeliveryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FreeDeliveryMutation object of the builder.
func (_u *FreeDeliveryUpdateOne) Mutation() *FreeDeliveryMutation {
	return _u.mutation
}

// Where appends a list predicates to the FreeDeliveryUpdate builder.
func (_u *FreeDeliveryUpdateOne) Where(ps ...predicate.FreeDelivery) *FreeDeliveryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FreeDeliveryUpdateOne) Select(field string, fields ...string) *FreeDeliveryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FreeDelivery entity.
func (_u *FreeDeliveryUpdateOne) Save(ctx context.Context) (*FreeDelivery, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FreeDeliveryUpdateOne) SaveX(ctx context.Context) *FreeDelivery {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FreeDeliveryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FreeDeliveryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FreeDeliveryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := freedelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FreeDeliveryUpdateOne) check() error {
	if v, ok := _u.mutation.OfferID(); ok {
		if err := freedelivery.OfferIDValidator(v); err != nil {
			return &ValidationError{Name: "offer_id", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.offer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubscriptionID(); ok {
		if err := freedelivery.SubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "subscription_id", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.subscription_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OfferGeneration(); ok {
		if err := freedelivery.OfferGenerationValidator(v); err != nil {
			return &ValidationError{Name: "offer_generation", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.offer_generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DestinationKind(); ok {
		if err := freedelivery.DestinationKindValidator(v); err != nil {
			return &ValidationError{Name: "destination_kind", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.destination_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DestinationID(); ok {
		if err := freedelivery.DestinationIDValidator(v); err != nil {
			return &ValidationError{Name: "destination_id", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.destination_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := freedelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptCount(); ok {
		if err := freedelivery.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "FreeDelivery.attempt_count": %w`, err)}
		}
	}
	return nil
}

func (_u *FreeDeliveryUpdateOne) sqlSave(ctx context.Context) (_node *FreeDelivery, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(freedelivery.Table, freedelivery.Columns, sqlgraph.NewFieldSpec(freedelivery.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FreeDelivery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, freedelivery.FieldID)
		for _, f := range fields {
			if !freedelivery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != freedelivery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OfferID(); ok {
		_spec.SetField(freedelivery.FieldOfferID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(freedelivery.FieldSubscriptionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OfferGeneration(); ok {
		_spec.SetField(freedelivery.FieldOfferGeneration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOfferGeneration(); ok {
		_spec.AddField(freedelivery.FieldOfferGeneration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DestinationKind(); ok {
		_spec.SetField(freedelivery.FieldDestinationKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DestinationID(); ok {
		_spec.SetField(freedelivery.FieldDestinationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(freedelivery.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(freedelivery.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(freedelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(freedelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(freedelivery.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(freedelivery.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(freedelivery.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(freedelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &FreeDelivery{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{freedelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
