// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/depthbomb/dealfox/ent/freemonitor"
	"github.com/depthbomb/dealfox/ent/predicate"
)

// FreeMonitorUpdate is the builder for updating FreeMonitor entities.
type FreeMonitorUpdate struct {
	config
	hooks    []Hook
	mutation *FreeMonitorMutation
}

// Where appends a list predicates to the FreeMonitorUpdate builder.
func (_u *FreeMonitorUpdate) Where(ps ...predicate.FreeMonitor) *FreeMonitorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCheckedAt sets the "checked_at" field.
func (_u *FreeMonitorUpdate) SetCheckedAt(v time.Time) *FreeMonitorUpdate {
	_u.mutation.SetCheckedAt(v)
	return _u
}

// SetNillableCheckedAt sets the "checked_at" field if the given value is not nil.
func (_u *FreeMonitorUpdate) SetNillableCheckedAt(v *time.Time) *FreeMonitorUpdate {
	if v != nil {
		_u.SetCheckedAt(*v)
	}
	return _u
}

// ClearCheckedAt clears the value of the "checked_at" field.
func (_u *FreeMonitorUpdate) ClearCheckedAt() *FreeMonitorUpdate {
	_u.mutation.ClearCheckedAt()
	return _u
}

// SetNextCheckAt sets the "next_check_at" field.
func (_u *FreeMonitorUpdate) SetNextCheckAt(v time.Time) *FreeMonitorUpdate {
	_u.mutation.SetNextCheckAt(v)
	return _u
}

// SetNillableNextCheckAt sets the "next_check_at" field if the given value is not nil.
func (_u *FreeMonitorUpdate) SetNillableNextCheckAt(v *time.Time) *FreeMonitorUpdate {
	if v != nil {
		_u.SetNextCheckAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FreeMonitorUpdate) SetStatus(v string) *FreeMonitorUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FreeMonitorUpdate) SetNillableStatus(v *string) *FreeMonitorUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProblems sets the "problems" field.
func (_u *FreeMonitorUpdate) SetProblems(v []string) *FreeMonitorUpdate {
	_u.mutation.SetProblems(v)
	return _u
}

// AppendProblems appends value to the "problems" field.
func (_u *FreeMonitorUpdate) AppendProblems(v []string) *FreeMonitorUpdate {
	_u.mutation.AppendProblems(v)
	return _u
}

// ClearProblems clears the value of the "problems" field.
func (_u *FreeMonitorUpdate) ClearProblems() *FreeMonitorUpdate {
	_u.mutation.ClearProblems()
	return _u
}

// SetFailures sets the "failures" field.
func (_u *FreeMonitorUpdate) SetFailures(v int) *FreeMonitorUpdate {
	_u.mutation.ResetFailures()
	_u.mutation.SetFailures(v)
	return _u
}

// SetNillableFailures sets the "failures" field if the given value is not nil.
func (_u *FreeMonitorUpdate) SetNillableFailures(v *int) *FreeMonitorUpdate {
	if v != nil {
		_u.SetFailures(*v)
	}
	return _u
}

// AddFailures adds value to the "failures" field.
func (_u *FreeMonitorUpdate) AddFailures(v int) *FreeMonitorUpdate {
	_u.mutation.AddFailures(v)
	return _u
}

// Mutation returns the FreeMonitorMutation object of the builder.
func (_u *FreeMonitorUpdate) Mutation() *FreeMonitorMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FreeMonitorUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FreeMonitorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FreeMonitorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FreeMonitorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FreeMonitorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(freemonitor.Table, freemonitor.Columns, sqlgraph.NewFieldSpec(freemonitor.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CheckedAt(); ok {
		_spec.SetField(freemonitor.FieldCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.CheckedAtCleared() {
		_spec.ClearField(freemonitor.FieldCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextCheckAt(); ok {
		_spec.SetField(freemonitor.FieldNextCheckAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(freemonitor.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Problems(); ok {
		_spec.SetField(freemonitor.FieldProblems, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProblems(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, freemonitor.FieldProblems, value)
		})
	}
	if _u.mutation.ProblemsCleared() {
		_spec.ClearField(freemonitor.FieldProblems, field.TypeJSON)
	}
	if value, ok := _u.mutation.Failures(); ok {
		_spec.SetField(freemonitor.FieldFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailures(); ok {
		_spec.AddField(freemonitor.FieldFailures, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{freemonitor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FreeMonitorUpdateOne is the builder for updating a single FreeMonitor entity.
type FreeMonitorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FreeMonitorMutation
}

// SetCheckedAt sets the "checked_at" field.
func (_u *FreeMonitorUpdateOne) SetCheckedAt(v time.Time) *FreeMonitorUpdateOne {
	_u.mutation.SetCheckedAt(v)
	return _u
}

// SetNillableCheckedAt sets the "checked_at" field if the given value is not nil.
func (_u *FreeMonitorUpdateOne) SetNillableCheckedAt(v *time.Time) *FreeMonitorUpdateOne {
	if v != nil {
		_u.SetCheckedAt(*v)
	}
	return _u
}

// ClearCheckedAt clears the value of the "checked_at" field.
func (_u *FreeMonitorUpdateOne) ClearCheckedAt() *FreeMonitorUpdateOne {
	_u.mutation.ClearCheckedAt()
	return _u
}

// SetNextCheckAt sets the "next_check_at" field.
func (_u *FreeMonitorUpdateOne) SetNextCheckAt(v time.Time) *FreeMonitorUpdateOne {
	_u.mutation.SetNextCheckAt(v)
	return _u
}

// SetNillableNextCheckAt sets the "next_check_at" field if the given value is not nil.
func (_u *FreeMonitorUpdateOne) SetNillableNextCheckAt(v *time.Time) *FreeMonitorUpdateOne {
	if v != nil {
		_u.SetNextCheckAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FreeMonitorUpdateOne) SetStatus(v string) *FreeMonitorUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FreeMonitorUpdateOne) SetNillableStatus(v *string) *FreeMonitorUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProblems sets the "problems" field.
func (_u *FreeMonitorUpdateOne) SetProblems(v []string) *FreeMonitorUpdateOne {
	_u.mutation.SetProblems(v)
	return _u
}

// AppendProblems appends value to the "problems" field.
func (_u *FreeMonitorUpdateOne) AppendProblems(v []string) *FreeMonitorUpdateOne {
	_u.mutation.AppendProblems(v)
	return _u
}

// ClearProblems clears the value of the "problems" field.
func (_u *FreeMonitorUpdateOne) ClearProblems() *FreeMonitorUpdateOne {
	_u.mutation.ClearProblems()
	return _u
}

// SetFailures sets the "failures" field.
func (_u *FreeMonitorUpdateOne) SetFailures(v int) *FreeMonitorUpdateOne {
	_u.mutation.ResetFailures()
	_u.mutation.SetFailures(v)
	return _u
}

// SetNillableFailures sets the "failures" field if the given value is not nil.
func (_u *FreeMonitorUpdateOne) SetNillableFailures(v *int) *FreeMonitorUpdateOne {
	if v != nil {
		_u.SetFailures(*v)
	}
	return _u
}

// AddFailures adds value to the "failures" field.
func (_u *FreeMonitorUpdateOne) AddFailures(v int) *FreeMonitorUpdateOne {
	_u.mutation.AddFailures(v)
	return _u
}

// Mutation returns the FreeMonitorMutation object of the builder.
func (_u *FreeMonitorUpdateOne) Mutation() *FreeMonitorMutation {
	return _u.mutation
}

// Where appends a list predicates to the FreeMonitorUpdate builder.
func (_u *FreeMonitorUpdateOne) Where(ps ...predicate.FreeMonitor) *FreeMonitorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FreeMonitorUpdateOne) Select(field string, fields ...string) *FreeMonitorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FreeMonitor entity.
func (_u *FreeMonitorUpdateOne) Save(ctx context.Context) (*FreeMonitor, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FreeMonitorUpdateOne) SaveX(ctx context.Context) *FreeMonitor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FreeMonitorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FreeMonitorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FreeMonitorUpdateOne) sqlSave(ctx context.Context) (_node *FreeMonitor, err error) {
	_spec := sqlgraph.NewUpdateSpec(freemonitor.Table, freemonitor.Columns, sqlgraph.NewFieldSpec(freemonitor.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FreeMonitor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, freemonitor.FieldID)
		for _, f := range fields {
			if !freemonitor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != freemonitor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CheckedAt(); ok {
		_spec.SetField(freemonitor.FieldCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.CheckedAtCleared() {
		_spec.ClearField(freemonitor.FieldCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextCheckAt(); ok {
		_spec.SetField(freemonitor.FieldNextCheckAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(freemonitor.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Problems(); ok {
		_spec.SetField(freemonitor.FieldProblems, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProblems(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, freemonitor.FieldProblems, value)
		})
	}
	if _u.mutation.ProblemsCleared() {
		_spec.ClearField(freemonitor.FieldProblems, field.TypeJSON)
	}
	if value, ok := _u.mutation.Failures(); ok {
		_spec.SetField(freemonitor.FieldFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailures(); ok {
		_spec.AddField(freemonitor.FieldFailures, field.TypeInt, value)
	}
	_node = &FreeMonitor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{freemonitor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
