// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/depthbomb/dealfox/ent/freemonitor"
	"github.com/depthbomb/dealfox/ent/predicate"
)

// FreeMonitorDelete is the builder for deleting a FreeMonitor entity.
type FreeMonitorDelete struct {
	config
	hooks    []Hook
	mutation *FreeMonitorMutation
}

// Where appends a list predicates to the FreeMonitorDelete builder.
func (_d *FreeMonitorDelete) Where(ps ...predicate.FreeMonitor) *FreeMonitorDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FreeMonitorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FreeMonitorDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FreeMonitorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(freemonitor.Table, sqlgraph.NewFieldSpec(freemonitor.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FreeMonitorDeleteOne is the builder for deleting a single FreeMonitor entity.
type FreeMonitorDeleteOne struct {
	_d *FreeMonitorDelete
}

// Where appends a list predicates to the FreeMonitorDelete builder.
func (_d *FreeMonitorDeleteOne) Where(ps ...predicate.FreeMonitor) *FreeMonitorDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FreeMonitorDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{freemonitor.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FreeMonitorDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
