// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/depthbomb/dealfox/ent/freemonitor"
)

// FreeMonitorCreate is the builder for creating a FreeMonitor entity.
type FreeMonitorCreate struct {
	config
	mutation *FreeMonitorMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCheckedAt sets the "checked_at" field.
func (_c *FreeMonitorCreate) SetCheckedAt(v time.Time) *FreeMonitorCreate {
	_c.mutation.SetCheckedAt(v)
	return _c
}

// SetNillableCheckedAt sets the "checked_at" field if the given value is not nil.
func (_c *FreeMonitorCreate) SetNillableCheckedAt(v *time.Time) *FreeMonitorCreate {
	if v != nil {
		_c.SetCheckedAt(*v)
	}
	return _c
}

// SetNextCheckAt sets the "next_check_at" field.
func (_c *FreeMonitorCreate) SetNextCheckAt(v time.Time) *FreeMonitorCreate {
	_c.mutation.SetNextCheckAt(v)
	return _c
}

// SetNillableNextCheckAt sets the "next_check_at" field if the given value is not nil.
func (_c *FreeMonitorCreate) SetNillableNextCheckAt(v *time.Time) *FreeMonitorCreate {
	if v != nil {
		_c.SetNextCheckAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *FreeMonitorCreate) SetStatus(v string) *FreeMonitorCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *FreeMonitorCreate) SetNillableStatus(v *string) *FreeMonitorCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProblems sets the "problems" field.
func (_c *FreeMonitorCreate) SetProblems(v []string) *FreeMonitorCreate {
	_c.mutation.SetProblems(v)
	return _c
}

// SetFailures sets the "failures" field.
func (_c *FreeMonitorCreate) SetFailures(v int) *FreeMonitorCreate {
	_c.mutation.SetFailures(v)
	return _c
}

// SetNillableFailures sets the "failures" field if the given value is not nil.
func (_c *FreeMonitorCreate) SetNillableFailures(v *int) *FreeMonitorCreate {
	if v != nil {
		_c.SetFailures(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FreeMonitorCreate) SetID(v string) *FreeMonitorCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the FreeMonitorMutation object of the builder.
func (_c *FreeMonitorCreate) Mutation() *FreeMonitorMutation {
	return _c.mutation
}

// Save creates the FreeMonitor in the database.
func (_c *FreeMonitorCreate) Save(ctx context.Context) (*FreeMonitor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FreeMonitorCreate) SaveX(ctx context.Context) *FreeMonitor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FreeMonitorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FreeMonitorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FreeMonitorCreate) defaults() {
	if _, ok := _c.mutation.NextCheckAt(); !ok {
		v := freemonitor.DefaultNextCheckAt()
		_c.mutation.SetNextCheckAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := freemonitor.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Failures(); !ok {
		v := freemonitor.DefaultFailures
		_c.mutation.SetFailures(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FreeMonitorCreate) check() error {
	if _, ok := _c.mutation.NextCheckAt(); !ok {
		return &ValidationError{Name: "next_check_at", err: errors.New(`ent: missing required field "FreeMonitor.next_check_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "FreeMonitor.status"`)}
	}
	if _, ok := _c.mutation.Failures(); !ok {
		return &ValidationError{Name: "failures", err: errors.New(`ent: missing required field "FreeMonitor.failures"`)}
	}
	return nil
}

func (_c *FreeMonitorCreate) sqlSave(ctx context.Context) (*FreeMonitor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected FreeMonitor.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FreeMonitorCreate) createSpec() (*FreeMonitor, *sqlgraph.CreateSpec) {
	var (
		_node = &FreeMonitor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(freemonitor.Table, sqlgraph.NewFieldSpec(freemonitor.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CheckedAt(); ok {
		_spec.SetField(freemonitor.FieldCheckedAt, field.TypeTime, value)
		_node.CheckedAt = &value
	}
	if value, ok := _c.mutation.NextCheckAt(); ok {
		_spec.SetField(freemonitor.FieldNextCheckAt, field.TypeTime, value)
		_node.NextCheckAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(freemonitor.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Problems(); ok {
		_spec.SetField(freemonitor.FieldProblems, field.TypeJSON, value)
		_node.Problems = value
	}
	if value, ok := _c.mutation.Failures(); ok {
		_spec.SetField(freemonitor.FieldFailures, field.TypeInt, value)
		_node.Failures = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FreeMonitor.Create().
//		SetCheckedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FreeMonitorUpsert) {
//			SetCheckedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FreeMonitorCreate) OnConflict(opts ...sql.ConflictOption) *FreeMonitorUpsertOne {
	_c.conflict = opts
	return &FreeMonitorUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FreeMonitor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FreeMonitorCreate) OnConflictColumns(columns ...string) *FreeMonitorUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FreeMonitorUpsertOne{
		create: _c,
	}
}

type (
	// FreeMonitorUpsertOne is the builder for "upsert"-ing
	//  one FreeMonitor node.
	FreeMonitorUpsertOne struct {
		create *FreeMonitorCreate
	}

	// FreeMonitorUpsert is the "OnConflict" setter.
	FreeMonitorUpsert struct {
		*sql.UpdateSet
	}
)

// SetCheckedAt sets the "checked_at" field.
func (u *FreeMonitorUpsert) SetCheckedAt(v time.Time) *FreeMonitorUpsert {
	u.Set(freemonitor.FieldCheckedAt, v)
	return u
}

// UpdateCheckedAt sets the "checked_at" field to the value that was provided on create.
func (u *FreeMonitorUpsert) UpdateCheckedAt() *FreeMonitorUpsert {
	u.SetExcluded(freemonitor.FieldCheckedAt)
	return u
}

// ClearCheckedAt clears the value of the "checked_at" field.
func (u *FreeMonitorUpsert) ClearCheckedAt() *FreeMonitorUpsert {
	u.SetNull(freemonitor.FieldCheckedAt)
	return u
}

// SetNextCheckAt sets the "next_check_at" field.
func (u *FreeMonitorUpsert) SetNextCheckAt(v time.Time) *FreeMonitorUpsert {
	u.Set(freemonitor.FieldNextCheckAt, v)
	return u
}

// UpdateNextCheckAt sets the "next_check_at" field to the value that was provided on create.
func (u *FreeMonitorUpsert) UpdateNextCheckAt() *FreeMonitorUpsert {
	u.SetExcluded(freemonitor.FieldNextCheckAt)
	return u
}

// SetStatus sets the "status" field.
func (u *FreeMonitorUpsert) SetStatus(v string) *FreeMonitorUpsert {
	u.Set(freemonitor.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FreeMonitorUpsert) UpdateStatus() *FreeMonitorUpsert {
	u.SetExcluded(freemonitor.FieldStatus)
	return u
}

// SetProblems sets the "problems" field.
func (u *FreeMonitorUpsert) SetProblems(v []string) *FreeMonitorUpsert {
	u.Set(freemonitor.FieldProblems, v)
	return u
}

// UpdateProblems sets the "problems" field to the value that was provided on create.
func (u *FreeMonitorUpsert) UpdateProblems() *FreeMonitorUpsert {
	u.SetExcluded(freemonitor.FieldProblems)
	return u
}

// ClearProblems clears the value of the "problems" field.
func (u *FreeMonitorUpsert) ClearProblems() *FreeMonitorUpsert {
	u.SetNull(freemonitor.FieldProblems)
	return u
}

// SetFailures sets the "failures" field.
func (u *FreeMonitorUpsert) SetFailures(v int) *FreeMonitorUpsert {
	u.Set(freemonitor.FieldFailures, v)
	return u
}

// UpdateFailures sets the "failures" field to the value that was provided on create.
func (u *FreeMonitorUpsert) UpdateFailures() *FreeMonitorUpsert {
	u.SetExcluded(freemonitor.FieldFailures)
	return u
}

// AddFailures adds v to the "failures" field.
func (u *FreeMonitorUpsert) AddFailures(v int) *FreeMonitorUpsert {
	u.Add(freemonitor.FieldFailures, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.FreeMonitor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(freemonitor.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FreeMonitorUpsertOne) UpdateNewValues() *FreeMonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(freemonitor.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FreeMonitor.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FreeMonitorUpsertOne) Ignore() *FreeMonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FreeMonitorUpsertOne) DoNothing() *FreeMonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FreeMonitorCreate.OnConflict
// documentation for more info.
func (u *FreeMonitorUpsertOne) Update(set func(*FreeMonitorUpsert)) *FreeMonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FreeMonitorUpsert{UpdateSet: update})
	}))
	return u
}

// SetCheckedAt sets the "checked_at" field.
func (u *FreeMonitorUpsertOne) SetCheckedAt(v time.Time) *FreeMonitorUpsertOne {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.SetCheckedAt(v)
	})
}

// UpdateCheckedAt sets the "checked_at" field to the value that was provided on create.
func (u *FreeMonitorUpsertOne) UpdateCheckedAt() *FreeMonitorUpsertOne {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.UpdateCheckedAt()
	})
}

// ClearCheckedAt clears the value of the "checked_at" field.
func (u *FreeMonitorUpsertOne) ClearCheckedAt() *FreeMonitorUpsertOne {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.ClearCheckedAt()
	})
}

// SetNextCheckAt sets the "next_check_at" field.
func (u *FreeMonitorUpsertOne) SetNextCheckAt(v time.Time) *FreeMonitorUpsertOne {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.SetNextCheckAt(v)
	})
}

// UpdateNextCheckAt sets the "next_check_at" field to the value that was provided on create.
func (u *FreeMonitorUpsertOne) UpdateNextCheckAt() *FreeMonitorUpsertOne {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.UpdateNextCheckAt()
	})
}

// SetStatus sets the "status" field.
func (u *FreeMonitorUpsertOne) SetStatus(v string) *FreeMonitorUpsertOne {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FreeMonitorUpsertOne) UpdateStatus() *FreeMonitorUpsertOne {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.UpdateStatus()
	})
}

// SetProblems sets the "problems" field.
func (u *FreeMonitorUpsertOne) SetProblems(v []string) *FreeMonitorUpsertOne {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.SetProblems(v)
	})
}

// UpdateProblems sets the "problems" field to the value that was provided on create.
func (u *FreeMonitorUpsertOne) UpdateProblems() *FreeMonitorUpsertOne {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.UpdateProblems()
	})
}

// ClearProblems clears the value of the "problems" field.
func (u *FreeMonitorUpsertOne) ClearProblems() *FreeMonitorUpsertOne {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.ClearProblems()
	})
}

// SetFailures sets the "failures" field.
func (u *FreeMonitorUpsertOne) SetFailures(v int) *FreeMonitorUpsertOne {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.SetFailures(v)
	})
}

// AddFailures adds v to the "failures" field.
func (u *FreeMonitorUpsertOne) AddFailures(v int) *FreeMonitorUpsertOne {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.AddFailures(v)
	})
}

// UpdateFailures sets the "failures" field to the value that was provided on create.
func (u *FreeMonitorUpsertOne) UpdateFailures() *FreeMonitorUpsertOne {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.UpdateFailures()
	})
}

// Exec executes the query.
func (u *FreeMonitorUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FreeMonitorCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FreeMonitorUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FreeMonitorUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: FreeMonitorUpsertOne.ID is not supported by MySQL driver. Use FreeMonitorUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FreeMonitorUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FreeMonitorCreateBulk is the builder for creating many FreeMonitor entities in bulk.
type FreeMonitorCreateBulk struct {
	config
	err      error
	builders []*FreeMonitorCreate
	conflict []sql.ConflictOption
}

// Save creates the FreeMonitor entities in the database.
func (_c *FreeMonitorCreateBulk) Save(ctx context.Context) ([]*FreeMonitor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FreeMonitor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FreeMonitorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FreeMonitorCreateBulk) SaveX(ctx context.Context) []*FreeMonitor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FreeMonitorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FreeMonitorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FreeMonitor.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FreeMonitorUpsert) {
//			SetCheckedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FreeMonitorCreateBulk) OnConflict(opts ...sql.ConflictOption) *FreeMonitorUpsertBulk {
	_c.conflict = opts
	return &FreeMonitorUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FreeMonitor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FreeMonitorCreateBulk) OnConflictColumns(columns ...string) *FreeMonitorUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FreeMonitorUpsertBulk{
		create: _c,
	}
}

// FreeMonitorUpsertBulk is the builder for "upsert"-ing
// a bulk of FreeMonitor nodes.
type FreeMonitorUpsertBulk struct {
	create *FreeMonitorCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FreeMonitor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(freemonitor.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FreeMonitorUpsertBulk) UpdateNewValues() *FreeMonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(freemonitor.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FreeMonitor.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FreeMonitorUpsertBulk) Ignore() *FreeMonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FreeMonitorUpsertBulk) DoNothing() *FreeMonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FreeMonitorCreateBulk.OnConflict
// documentation for more info.
func (u *FreeMonitorUpsertBulk) Update(set func(*FreeMonitorUpsert)) *FreeMonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FreeMonitorUpsert{UpdateSet: update})
	}))
	return u
}

// SetCheckedAt sets the "checked_at" field.
func (u *FreeMonitorUpsertBulk) SetCheckedAt(v time.Time) *FreeMonitorUpsertBulk {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.SetCheckedAt(v)
	})
}

// UpdateCheckedAt sets the "checked_at" field to the value that was provided on create.
func (u *FreeMonitorUpsertBulk) UpdateCheckedAt() *FreeMonitorUpsertBulk {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.UpdateCheckedAt()
	})
}

// ClearCheckedAt clears the value of the "checked_at" field.
func (u *FreeMonitorUpsertBulk) ClearCheckedAt() *FreeMonitorUpsertBulk {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.ClearCheckedAt()
	})
}

// SetNextCheckAt sets the "next_check_at" field.
func (u *FreeMonitorUpsertBulk) SetNextCheckAt(v time.Time) *FreeMonitorUpsertBulk {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.SetNextCheckAt(v)
	})
}

// UpdateNextCheckAt sets the "next_check_at" field to the value that was provided on create.
func (u *FreeMonitorUpsertBulk) UpdateNextCheckAt() *FreeMonitorUpsertBulk {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.UpdateNextCheckAt()
	})
}

// SetStatus sets the "status" field.
func (u *FreeMonitorUpsertBulk) SetStatus(v string) *FreeMonitorUpsertBulk {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FreeMonitorUpsertBulk) UpdateStatus() *FreeMonitorUpsertBulk {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.UpdateStatus()
	})
}

// SetProblems sets the "problems" field.
func (u *FreeMonitorUpsertBulk) SetProblems(v []string) *FreeMonitorUpsertBulk {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.SetProblems(v)
	})
}

// UpdateProblems sets the "problems" field to the value that was provided on create.
func (u *FreeMonitorUpsertBulk) UpdateProblems() *FreeMonitorUpsertBulk {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.UpdateProblems()
	})
}

// ClearProblems clears the value of the "problems" field.
func (u *FreeMonitorUpsertBulk) ClearProblems() *FreeMonitorUpsertBulk {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.ClearProblems()
	})
}

// SetFailures sets the "failures" field.
func (u *FreeMonitorUpsertBulk) SetFailures(v int) *FreeMonitorUpsertBulk {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.SetFailures(v)
	})
}

// AddFailures adds v to the "failures" field.
func (u *FreeMonitorUpsertBulk) AddFailures(v int) *FreeMonitorUpsertBulk {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.AddFailures(v)
	})
}

// UpdateFailures sets the "failures" field to the value that was provided on create.
func (u *FreeMonitorUpsertBulk) UpdateFailures() *FreeMonitorUpsertBulk {
	return u.Update(func(s *FreeMonitorUpsert) {
		s.UpdateFailures()
	})
}

// Exec executes the query.
func (u *FreeMonitorUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FreeMonitorCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FreeMonitorCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FreeMonitorUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
