// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/depthbomb/dealfox/ent/freesubscription"
	"github.com/depthbomb/dealfox/ent/predicate"
)

// FreeSubscriptionDelete is the builder for deleting a FreeSubscription entity.
type FreeSubscriptionDelete struct {
	config
	hooks    []Hook
	mutation *FreeSubscriptionMutation
}

// Where appends a list predicates to the FreeSubscriptionDelete builder.
func (_d *FreeSubscriptionDelete) Where(ps ...predicate.FreeSubscription) *FreeSubscriptionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FreeSubscriptionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FreeSubscriptionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FreeSubscriptionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(freesubscription.Table, sqlgraph.NewFieldSpec(freesubscription.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FreeSubscriptionDeleteOne is the builder for deleting a single FreeSubscription entity.
type FreeSubscriptionDeleteOne struct {
	_d *FreeSubscriptionDelete
}

// Where appends a list predicates to the FreeSubscriptionDelete builder.
func (_d *FreeSubscriptionDeleteOne) Where(ps ...predicate.FreeSubscription) *FreeSubscriptionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FreeSubscriptionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{freesubscription.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FreeSubscriptionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
