// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/depthbomb/dealfox/ent/event"
	"github.com/depthbomb/dealfox/ent/rule"
	"github.com/depthbomb/dealfox/ent/target"
)

// RuleCreate is the builder for creating a Rule entity.
type RuleCreate struct {
	config
	mutation *RuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTargetID sets the "target_id" field.
func (_c *RuleCreate) SetTargetID(v string) *RuleCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *RuleCreate) SetOwnerID(v string) *RuleCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *RuleCreate) SetRequestID(v string) *RuleCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *RuleCreate) SetNillableRequestID(v *string) *RuleCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetCondition sets the "condition" field.
func (_c *RuleCreate) SetCondition(v rule.Condition) *RuleCreate {
	_c.mutation.SetCondition(v)
	return _c
}

// SetBudgetMinor sets the "budget_minor" field.
func (_c *RuleCreate) SetBudgetMinor(v int64) *RuleCreate {
	_c.mutation.SetBudgetMinor(v)
	return _c
}

// SetNillableBudgetMinor sets the "budget_minor" field if the given value is not nil.
func (_c *RuleCreate) SetNillableBudgetMinor(v *int64) *RuleCreate {
	if v != nil {
		_c.SetBudgetMinor(*v)
	}
	return _c
}

// SetBudgetCurrency sets the "budget_currency" field.
func (_c *RuleCreate) SetBudgetCurrency(v string) *RuleCreate {
	_c.mutation.SetBudgetCurrency(v)
	return _c
}

// SetNillableBudgetCurrency sets the "budget_currency" field if the given value is not nil.
func (_c *RuleCreate) SetNillableBudgetCurrency(v *string) *RuleCreate {
	if v != nil {
		_c.SetBudgetCurrency(*v)
	}
	return _c
}

// SetRecurring sets the "recurring" field.
func (_c *RuleCreate) SetRecurring(v bool) *RuleCreate {
	_c.mutation.SetRecurring(v)
	return _c
}

// SetNillableRecurring sets the "recurring" field if the given value is not nil.
func (_c *RuleCreate) SetNillableRecurring(v *bool) *RuleCreate {
	if v != nil {
		_c.SetRecurring(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *RuleCreate) SetEnabled(v bool) *RuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *RuleCreate) SetNillableEnabled(v *bool) *RuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetLatched sets the "latched" field.
func (_c *RuleCreate) SetLatched(v bool) *RuleCreate {
	_c.mutation.SetLatched(v)
	return _c
}

// SetNillableLatched sets the "latched" field if the given value is not nil.
func (_c *RuleCreate) SetNillableLatched(v *bool) *RuleCreate {
	if v != nil {
		_c.SetLatched(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RuleCreate) SetCreatedAt(v time.Time) *RuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RuleCreate) SetNillableCreatedAt(v *time.Time) *RuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RuleCreate) SetUpdatedAt(v time.Time) *RuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RuleCreate) SetNillableUpdatedAt(v *time.Time) *RuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RuleCreate) SetID(v string) *RuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RuleCreate) SetNillableID(v *string) *RuleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTarget sets the "target" edge to the Target entity.
func (_c *RuleCreate) SetTarget(v *Target) *RuleCreate {
	return _c.SetTargetID(v.ID)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_c *RuleCreate) AddEventIDs(ids ...string) *RuleCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the Event entity.
func (_c *RuleCreate) AddEvents(v ...*Event) *RuleCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// Mutation returns the RuleMutation object of the builder.
func (_c *RuleCreate) Mutation() *RuleMutation {
	return _c.mutation
}

// Save creates the Rule in the database.
func (_c *RuleCreate) Save(ctx context.Context) (*Rule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RuleCreate) SaveX(ctx context.Context) *Rule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RuleCreate) defaults() {
	if _, ok := _c.mutation.BudgetCurrency(); !ok {
		v := rule.DefaultBudgetCurrency
		_c.mutation.SetBudgetCurrency(v)
	}
	if _, ok := _c.mutation.Recurring(); !ok {
		v := rule.DefaultRecurring
		_c.mutation.SetRecurring(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := rule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Latched(); !ok {
		v := rule.DefaultLatched
		_c.mutation.SetLatched(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := rule.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RuleCreate) check() error {
	if _, ok := _c.mutation.TargetID(); !ok {
		return &ValidationError{Name: "target_id", err: errors.New(`ent: missing required field "Rule.target_id"`)}
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Rule.owner_id"`)}
	}
	if v, ok := _c.mutation.OwnerID(); ok {
		if err := rule.OwnerIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_id", err: fmt.Errorf(`ent: validator failed for field "Rule.owner_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Condition(); !ok {
		return &ValidationError{Name: "condition", err: errors.New(`ent: missing required field "Rule.condition"`)}
	}
	if v, ok := _c.mutation.Condition(); ok {
		if err := rule.ConditionValidator(v); err != nil {
			return &ValidationError{Name: "condition", err: fmt.Errorf(`ent: validator failed for field "Rule.condition": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BudgetMinor(); ok {
		if err := rule.BudgetMinorValidator(v); err != nil {
			return &ValidationError{Name: "budget_minor", err: fmt.Errorf(`ent: validator failed for field "Rule.budget_minor": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BudgetCurrency(); !ok {
		return &ValidationError{Name: "budget_currency", err: errors.New(`ent: missing required field "Rule.budget_currency"`)}
	}
	if _, ok := _c.mutation.Recurring(); !ok {
		return &ValidationError{Name: "recurring", err: errors.New(`ent: missing required field "Rule.recurring"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Rule.enabled"`)}
	}
	if _, ok := _c.mutation.Latched(); !ok {
		return &ValidationError{Name: "latched", err: errors.New(`ent: missing required field "Rule.latched"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Rule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Rule.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := rule.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Rule.id": %w`, err)}
		}
	}
	if len(_c.mutation.TargetIDs()) == 0 {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required edge "Rule.target"`)}
	}
	return nil
}

func (_c *RuleCreate) sqlSave(ctx context.Context) (*Rule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Rule.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RuleCreate) createSpec() (*Rule, *sqlgraph.CreateSpec) {
	var (
		_node = &Rule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rule.Table, sqlgraph.NewFieldSpec(rule.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(rule.FieldOwnerID, field.TypeString, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(rule.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.Condition(); ok {
		_spec.SetField(rule.FieldCondition, field.TypeEnum, value)
		_node.Condition = value
	}
	if value, ok := _c.mutation.BudgetMinor(); ok {
		_spec.SetField(rule.FieldBudgetMinor, field.TypeInt64, value)
		_node.BudgetMinor = &value
	}
	if value, ok := _c.mutation.BudgetCurrency(); ok {
		_spec.SetField(rule.FieldBudgetCurrency, field.TypeString, value)
		_node.BudgetCurrency = value
	}
	if value, ok := _c.mutation.Recurring(); ok {
		_spec.SetField(rule.FieldRecurring, field.TypeBool, value)
		_node.Recurring = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(rule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Latched(); ok {
		_spec.SetField(rule.FieldLatched, field.TypeBool, value)
		_node.Latched = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.TargetTable,
			Columns: []string{rule.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TargetID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rule.EventsTable,
			Columns: []string{rule.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Rule.Create().
//		SetTargetID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RuleUpsert) {
//			SetTargetID(v+v).
//		}).
//		Exec(ctx)
func (_c *RuleCreate) OnConflict(opts ...sql.ConflictOption) *RuleUpsertOne {
	_c.conflict = opts
	return &RuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RuleCreate) OnConflictColumns(columns ...string) *RuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RuleUpsertOne{
		create: _c,
	}
}

type (
	// RuleUpsertOne is the builder for "upsert"-ing
	//  one Rule node.
	RuleUpsertOne struct {
		create *RuleCreate
	}

	// RuleUpsert is the "OnConflict" setter.
	RuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetTargetID sets the "target_id" field.
func (u *RuleUpsert) SetTargetID(v string) *RuleUpsert {
	u.Set(rule.FieldTargetID, v)
	return u
}

// UpdateTargetID sets the "target_id" field to the value that was provided on create.
func (u *RuleUpsert) UpdateTargetID() *RuleUpsert {
	u.SetExcluded(rule.FieldTargetID)
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *RuleUpsert) SetOwnerID(v string) *RuleUpsert {
	u.Set(rule.FieldOwnerID, v)
	return u
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *RuleUpsert) UpdateOwnerID() *RuleUpsert {
	u.SetExcluded(rule.FieldOwnerID)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *RuleUpsert) SetRequestID(v string) *RuleUpsert {
	u.Set(rule.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RuleUpsert) UpdateRequestID() *RuleUpsert {
	u.SetExcluded(rule.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RuleUpsert) ClearRequestID() *RuleUpsert {
	u.SetNull(rule.FieldRequestID)
	return u
}

// SetCondition sets the "condition" field.
func (u *RuleUpsert) SetCondition(v rule.Condition) *RuleUpsert {
	u.Set(rule.FieldCondition, v)
	return u
}

// UpdateCondition sets the "condition" field to the value that was provided on create.
func (u *RuleUpsert) UpdateCondition() *RuleUpsert {
	u.SetExcluded(rule.FieldCondition)
	return u
}

// SetBudgetMinor sets the "budget_minor" field.
func (u *RuleUpsert) SetBudgetMinor(v int64) *RuleUpsert {
	u.Set(rule.FieldBudgetMinor, v)
	return u
}

// UpdateBudgetMinor sets the "budget_minor" field to the value that was provided on create.
func (u *RuleUpsert) UpdateBudgetMinor() *RuleUpsert {
	u.SetExcluded(rule.FieldBudgetMinor)
	return u
}

// AddBudgetMinor adds v to the "budget_minor" field.
func (u *RuleUpsert) AddBudgetMinor(v int64) *RuleUpsert {
	u.Add(rule.FieldBudgetMinor, v)
	return u
}

// ClearBudgetMinor clears the value of the "budget_minor" field.
func (u *RuleUpsert) ClearBudgetMinor() *RuleUpsert {
	u.SetNull(rule.FieldBudgetMinor)
	return u
}

// SetBudgetCurrency sets the "budget_currency" field.
func (u *RuleUpsert) SetBudgetCurrency(v string) *RuleUpsert {
	u.Set(rule.FieldBudgetCurrency, v)
	return u
}

// UpdateBudgetCurrency sets the "budget_currency" field to the value that was provided on create.
func (u *RuleUpsert) UpdateBudgetCurrency() *RuleUpsert {
	u.SetExcluded(rule.FieldBudgetCurrency)
	return u
}

// SetRecurring sets the "recurring" field.
func (u *RuleUpsert) SetRecurring(v bool) *RuleUpsert {
	u.Set(rule.FieldRecurring, v)
	return u
}

// UpdateRecurring sets the "recurring" field to the value that was provided on create.
func (u *RuleUpsert) UpdateRecurring() *RuleUpsert {
	u.SetExcluded(rule.FieldRecurring)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *RuleUpsert) SetEnabled(v bool) *RuleUpsert {
	u.Set(rule.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RuleUpsert) UpdateEnabled() *RuleUpsert {
	u.SetExcluded(rule.FieldEnabled)
	return u
}

// SetLatched sets the "latched" field.
func (u *RuleUpsert) SetLatched(v bool) *RuleUpsert {
	u.Set(rule.FieldLatched, v)
	return u
}

// UpdateLatched sets the "latched" field to the value that was provided on create.
func (u *RuleUpsert) UpdateLatched() *RuleUpsert {
	u.SetExcluded(rule.FieldLatched)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RuleUpsert) SetUpdatedAt(v time.Time) *RuleUpsert {
	u.Set(rule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RuleUpsert) UpdateUpdatedAt() *RuleUpsert {
	u.SetExcluded(rule.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RuleUpsertOne) UpdateNewValues() *RuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(rule.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(rule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Rule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RuleUpsertOne) Ignore() *RuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RuleUpsertOne) DoNothing() *RuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RuleCreate.OnConflict
// documentation for more info.
func (u *RuleUpsertOne) Update(set func(*RuleUpsert)) *RuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetTargetID sets the "target_id" field.
func (u *RuleUpsertOne) SetTargetID(v string) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetTargetID(v)
	})
}

// UpdateTargetID sets the "target_id" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateTargetID() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateTargetID()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *RuleUpsertOne) SetOwnerID(v string) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateOwnerID() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateOwnerID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *RuleUpsertOne) SetRequestID(v string) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateRequestID() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RuleUpsertOne) ClearRequestID() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.ClearRequestID()
	})
}

// SetCondition sets the "condition" field.
func (u *RuleUpsertOne) SetCondition(v rule.Condition) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetCondition(v)
	})
}

// UpdateCondition sets the "condition" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateCondition() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateCondition()
	})
}

// SetBudgetMinor sets the "budget_minor" field.
func (u *RuleUpsertOne) SetBudgetMinor(v int64) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetBudgetMinor(v)
	})
}

// AddBudgetMinor adds v to the "budget_minor" field.
func (u *RuleUpsertOne) AddBudgetMinor(v int64) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.AddBudgetMinor(v)
	})
}

// UpdateBudgetMinor sets the "budget_minor" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateBudgetMinor() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateBudgetMinor()
	})
}

// ClearBudgetMinor clears the value of the "budget_minor" field.
func (u *RuleUpsertOne) ClearBudgetMinor() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.ClearBudgetMinor()
	})
}

// SetBudgetCurrency sets the "budget_currency" field.
func (u *RuleUpsertOne) SetBudgetCurrency(v string) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetBudgetCurrency(v)
	})
}

// UpdateBudgetCurrency sets the "budget_currency" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateBudgetCurrency() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateBudgetCurrency()
	})
}

// SetRecurring sets the "recurring" field.
func (u *RuleUpsertOne) SetRecurring(v bool) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetRecurring(v)
	})
}

// UpdateRecurring sets the "recurring" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateRecurring() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateRecurring()
	})
}

// SetEnabled sets the "enabled" field.
func (u *RuleUpsertOne) SetEnabled(v bool) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateEnabled() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetLatched sets the "latched" field.
func (u *RuleUpsertOne) SetLatched(v bool) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetLatched(v)
	})
}

// UpdateLatched sets the "latched" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateLatched() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateLatched()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RuleUpsertOne) SetUpdatedAt(v time.Time) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateUpdatedAt() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RuleUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RuleUpsertOne.ID is not supported by MySQL driver. Use RuleUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RuleUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RuleCreateBulk is the builder for creating many Rule entities in bulk.
type RuleCreateBulk struct {
	config
	err      error
	builders []*RuleCreate
	conflict []sql.ConflictOption
}

// Save creates the Rule entities in the database.
func (_c *RuleCreateBulk) Save(ctx context.Context) ([]*Rule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Rule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RuleCreateBulk) SaveX(ctx context.Context) []*Rule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Rule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RuleUpsert) {
//			SetTargetID(v+v).
//		}).
//		Exec(ctx)
func (_c *RuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *RuleUpsertBulk {
	_c.conflict = opts
	return &RuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RuleCreateBulk) OnConflictColumns(columns ...string) *RuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RuleUpsertBulk{
		create: _c,
	}
}

// RuleUpsertBulk is the builder for "upsert"-ing
// a bulk of Rule nodes.
type RuleUpsertBulk struct {
	create *RuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RuleUpsertBulk) UpdateNewValues() *RuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(rule.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(rule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RuleUpsertBulk) Ignore() *RuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RuleUpsertBulk) DoNothing() *RuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RuleCreateBulk.OnConflict
// documentation for more info.
func (u *RuleUpsertBulk) Update(set func(*RuleUpsert)) *RuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetTargetID sets the "target_id" field.
func (u *RuleUpsertBulk) SetTargetID(v string) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetTargetID(v)
	})
}

// UpdateTargetID sets the "target_id" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateTargetID() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateTargetID()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *RuleUpsertBulk) SetOwnerID(v string) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateOwnerID() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateOwnerID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *RuleUpsertBulk) SetRequestID(v string) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateRequestID() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RuleUpsertBulk) ClearRequestID() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.ClearRequestID()
	})
}

// SetCondition sets the "condition" field.
func (u *RuleUpsertBulk) SetCondition(v rule.Condition) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetCondition(v)
	})
}

// UpdateCondition sets the "condition" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateCondition() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateCondition()
	})
}

// SetBudgetMinor sets the "budget_minor" field.
func (u *RuleUpsertBulk) SetBudgetMinor(v int64) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetBudgetMinor(v)
	})
}

// AddBudgetMinor adds v to the "budget_minor" field.
func (u *RuleUpsertBulk) AddBudgetMinor(v int64) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.AddBudgetMinor(v)
	})
}

// UpdateBudgetMinor sets the "budget_minor" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateBudgetMinor() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateBudgetMinor()
	})
}

// ClearBudgetMinor clears the value of the "budget_minor" field.
func (u *RuleUpsertBulk) ClearBudgetMinor() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.ClearBudgetMinor()
	})
}

// SetBudgetCurrency sets the "budget_currency" field.
func (u *RuleUpsertBulk) SetBudgetCurrency(v string) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetBudgetCurrency(v)
	})
}

// UpdateBudgetCurrency sets the "budget_currency" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateBudgetCurrency() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateBudgetCurrency()
	})
}

// SetRecurring sets the "recurring" field.
func (u *RuleUpsertBulk) SetRecurring(v bool) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetRecurring(v)
	})
}

// UpdateRecurring sets the "recurring" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateRecurring() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateRecurring()
	})
}

// SetEnabled sets the "enabled" field.
func (u *RuleUpsertBulk) SetEnabled(v bool) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateEnabled() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetLatched sets the "latched" field.
func (u *RuleUpsertBulk) SetLatched(v bool) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetLatched(v)
	})
}

// UpdateLatched sets the "latched" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateLatched() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateLatched()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RuleUpsertBulk) SetUpdatedAt(v time.Time) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateUpdatedAt() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
