// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/depthbomb/dealfox/ent/rule"
	"github.com/depthbomb/dealfox/ent/target"
)

// Rule is the model entity for the Rule schema.
type Rule struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TargetID holds the value of the "target_id" field.
	TargetID string `json:"target_id,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID string `json:"owner_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *string `json:"request_id,omitempty"`
	// Condition holds the value of the "condition" field.
	Condition rule.Condition `json:"condition,omitempty"`
	// BudgetMinor holds the value of the "budget_minor" field.
	BudgetMinor *int64 `json:"budget_minor,omitempty"`
	// BudgetCurrency holds the value of the "budget_currency" field.
	BudgetCurrency string `json:"budget_currency,omitempty"`
	// Recurring holds the value of the "recurring" field.
	Recurring bool `json:"recurring,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Latched holds the value of the "latched" field.
	Latched bool `json:"latched,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RuleQuery when eager-loading is set.
	Edges        RuleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RuleEdges holds the relations/edges for other nodes in the graph.
type RuleEdges struct {
	// Target holds the value of the target edge.
	Target *Target `json:"target,omitempty"`
	// Events holds the value of the events edge.
	Events []*Event `json:"events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TargetOrErr returns the Target value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RuleEdges) TargetOrErr() (*Target, error) {
	if e.Target != nil {
		return e.Target, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: target.Label}
	}
	return nil, &NotLoadedError{edge: "target"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e RuleEdges) EventsOrErr() ([]*Event, error) {
	if e.loadedTypes[1] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Rule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rule.FieldRecurring, rule.FieldEnabled, rule.FieldLatched:
			values[i] = new(sql.NullBool)
		case rule.FieldBudgetMinor:
			values[i] = new(sql.NullInt64)
		case rule.FieldID, rule.FieldTargetID, rule.FieldOwnerID, rule.FieldRequestID, rule.FieldCondition, rule.FieldBudgetCurrency:
			values[i] = new(sql.NullString)
		case rule.FieldCreatedAt, rule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Rule fields.
func (_m *Rule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rule.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case rule.FieldTargetID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				_m.TargetID = value.String
			}
		case rule.FieldOwnerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				_m.OwnerID = value.String
			}
		case rule.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case rule.FieldCondition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field condition", values[i])
			} else if value.Valid {
				_m.Condition = rule.Condition(value.String)
			}
		case rule.FieldBudgetMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field budget_minor", values[i])
			} else if value.Valid {
				_m.BudgetMinor = new(int64)
				*_m.BudgetMinor = value.Int64
			}
		case rule.FieldBudgetCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field budget_currency", values[i])
			} else if value.Valid {
				_m.BudgetCurrency = value.String
			}
		case rule.FieldRecurring:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field recurring", values[i])
			} else if value.Valid {
				_m.Recurring = value.Bool
			}
		case rule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case rule.FieldLatched:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field latched", values[i])
			} else if value.Valid {
				_m.Latched = value.Bool
			}
		case rule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Rule.
// This includes values selected through modifiers, order, etc.
func (_m *Rule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTarget queries the "target" edge of the Rule entity.
func (_m *Rule) QueryTarget() *TargetQuery {
	return NewRuleClient(_m.config).QueryTarget(_m)
}

// QueryEvents queries the "events" edge of the Rule entity.
func (_m *Rule) QueryEvents() *EventQuery {
	return NewRuleClient(_m.config).QueryEvents(_m)
}

// Update returns a builder for updating this Rule.
// Note that you need to call Rule.Unwrap() before calling this method if this Rule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Rule) Update() *RuleUpdateOne {
	return NewRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Rule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Rule) Unwrap() *Rule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Rule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Rule) String() string {
	var builder strings.Builder
	builder.WriteString("Rule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("target_id=")
	builder.WriteString(_m.TargetID)
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(_m.OwnerID)
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("condition=")
	builder.WriteString(fmt.Sprintf("%v", _m.Condition))
	builder.WriteString(", ")
	if v := _m.BudgetMinor; v != nil {
		builder.WriteString("budget_minor=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("budget_currency=")
	builder.WriteString(_m.BudgetCurrency)
	builder.WriteString(", ")
	builder.WriteString("recurring=")
	builder.WriteString(fmt.Sprintf("%v", _m.Recurring))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("latched=")
	builder.WriteString(fmt.Sprintf("%v", _m.Latched))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Rules is a parsable slice of Rule.
type Rules []*Rule
