// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/depthbomb/dealfox/ent/event"
	"github.com/depthbomb/dealfox/ent/predicate"
	"github.com/depthbomb/dealfox/ent/rule"
	"github.com/depthbomb/dealfox/ent/target"
)

// RuleUpdate is the builder for updating Rule entities.
type RuleUpdate struct {
	config
	hooks    []Hook
	mutation *RuleMutation
}

// Where appends a list predicates to the RuleUpdate builder.
func (_u *RuleUpdate) Where(ps ...predicate.Rule) *RuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *RuleUpdate) SetTargetID(v string) *RuleUpdate {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableTargetID(v *string) *RuleUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *RuleUpdate) SetOwnerID(v string) *RuleUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableOwnerID(v *string) *RuleUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RuleUpdate) SetRequestID(v string) *RuleUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableRequestID(v *string) *RuleUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *RuleUpdate) ClearRequestID() *RuleUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetCondition sets the "condition" field.
func (_u *RuleUpdate) SetCondition(v rule.Condition) *RuleUpdate {
	_u.mutation.SetCondition(v)
	return _u
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableCondition(v *rule.Condition) *RuleUpdate {
	if v != nil {
		_u.SetCondition(*v)
	}
	return _u
}

// SetBudgetMinor sets the "budget_minor" field.
func (_u *RuleUpdate) SetBudgetMinor(v int64) *RuleUpdate {
	_u.mutation.ResetBudgetMinor()
	_u.mutation.SetBudgetMinor(v)
	return _u
}

// SetNillableBudgetMinor sets the "budget_minor" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableBudgetMinor(v *int64) *RuleUpdate {
	if v != nil {
		_u.SetBudgetMinor(*v)
	}
	return _u
}

// AddBudgetMinor adds value to the "budget_minor" field.
func (_u *RuleUpdate) AddBudgetMinor(v int64) *RuleUpdate {
	_u.mutation.AddBudgetMinor(v)
	return _u
}

// ClearBudgetMinor clears the value of the "budget_minor" field.
func (_u *RuleUpdate) ClearBudgetMinor() *RuleUpdate {
	_u.mutation.ClearBudgetMinor()
	return _u
}

// SetBudgetCurrency sets the "budget_currency" field.
func (_u *RuleUpdate) SetBudgetCurrency(v string) *RuleUpdate {
	_u.mutation.SetBudgetCurrency(v)
	return _u
}

// SetNillableBudgetCurrency sets the "budget_currency" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableBudgetCurrency(v *string) *RuleUpdate {
	if v != nil {
		_u.SetBudgetCurrency(*v)
	}
	return _u
}

// SetRecurring sets the "recurring" field.
func (_u *RuleUpdate) SetRecurring(v bool) *RuleUpdate {
	_u.mutation.SetRecurring(v)
	return _u
}

// SetNillableRecurring sets the "recurring" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableRecurring(v *bool) *RuleUpdate {
	if v != nil {
		_u.SetRecurring(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RuleUpdate) SetEnabled(v bool) *RuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableEnabled(v *bool) *RuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLatched sets the "latched" field.
func (_u *RuleUpdate) SetLatched(v bool) *RuleUpdate {
	_u.mutation.SetLatched(v)
	return _u
}

// SetNillableLatched sets the "latched" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableLatched(v *bool) *RuleUpdate {
	if v != nil {
		_u.SetLatched(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RuleUpdate) SetUpdatedAt(v time.Time) *RuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTarget sets the "target" edge to the Target entity.
func (_u *RuleUpdate) SetTarget(v *Target) *RuleUpdate {
	return _u.SetTargetID(v.ID)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *RuleUpdate) AddEventIDs(ids ...string) *RuleUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *RuleUpdate) AddEvents(v ...*Event) *RuleUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the RuleMutation object of the builder.
func (_u *RuleUpdate) Mutation() *RuleMutation {
	return _u.mutation
}

// ClearTarget clears the "target" edge to the Target entity.
func (_u *RuleUpdate) ClearTarget() *RuleUpdate {
	_u.mutation.ClearTarget()
	return _u
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *RuleUpdate) ClearEvents() *RuleUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *RuleUpdate) RemoveEventIDs(ids ...string) *RuleUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *RuleUpdate) RemoveEvents(v ...*Event) *RuleUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuleUpdate) check() error {
	if v, ok := _u.mutation.OwnerID(); ok {
		if err := rule.OwnerIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_id", err: fmt.Errorf(`ent: validator failed for field "Rule.owner_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Condition(); ok {
		if err := rule.ConditionValidator(v); err != nil {
			return &ValidationError{Name: "condition", err: fmt.Errorf(`ent: validator failed for field "Rule.condition": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BudgetMinor(); ok {
		if err := rule.BudgetMinorValidator(v); err != nil {
			return &ValidationError{Name: "budget_minor", err: fmt.Errorf(`ent: validator failed for field "Rule.budget_minor": %w`, err)}
		}
	}
	if _u.mutation.TargetCleared() && len(_u.mutation.TargetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Rule.target"`)
	}
	return nil
}

func (_u *RuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rule.Table, rule.Columns, sqlgraph.NewFieldSpec(rule.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(rule.FieldOwnerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(rule.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(rule.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Condition(); ok {
		_spec.SetField(rule.FieldCondition, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BudgetMinor(); ok {
		_spec.SetField(rule.FieldBudgetMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBudgetMinor(); ok {
		_spec.AddField(rule.FieldBudgetMinor, field.TypeInt64, value)
	}
	if _u.mutation.BudgetMinorCleared() {
		_spec.ClearField(rule.FieldBudgetMinor, field.TypeInt64)
	}
	if value, ok := _u.mutation.BudgetCurrency(); ok {
		_spec.SetField(rule.FieldBudgetCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recurring(); ok {
		_spec.SetField(rule.FieldRecurring, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(rule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Latched(); ok {
		_spec.SetField(rule.FieldLatched, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.TargetTable,
			Columns: []string{rule.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.TargetTable,
			Columns: []string{rule.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rule.EventsTable,
			Columns: []string{rule.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rule.EventsTable,
			Columns: []string{rule.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rule.EventsTable,
			Columns: []string{rule.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RuleUpdateOne is the builder for updating a single Rule entity.
type RuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RuleMutation
}

// SetTargetID sets the "target_id" field.
func (_u *RuleUpdateOne) SetTargetID(v string) *RuleUpdateOne {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableTargetID(v *string) *RuleUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *RuleUpdateOne) SetOwnerID(v string) *RuleUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableOwnerID(v *string) *RuleUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RuleUpdateOne) SetRequestID(v string) *RuleUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableRequestID(v *string) *RuleUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *RuleUpdateOne) ClearRequestID() *RuleUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetCondition sets the "condition" field.
func (_u *RuleUpdateOne) SetCondition(v rule.Condition) *RuleUpdateOne {
	_u.mutation.SetCondition(v)
	return _u
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableCondition(v *rule.Condition) *RuleUpdateOne {
	if v != nil {
		_u.SetCondition(*v)
	}
	return _u
}

// SetBudgetMinor sets the "budget_minor" field.
func (_u *RuleUpdateOne) SetBudgetMinor(v int64) *RuleUpdateOne {
	_u.mutation.ResetBudgetMinor()
	_u.mutation.SetBudgetMinor(v)
	return _u
}

// SetNillableBudgetMinor sets the "budget_minor" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableBudgetMinor(v *int64) *RuleUpdateOne {
	if v != nil {
		_u.SetBudgetMinor(*v)
	}
	return _u
}

// AddBudgetMinor adds value to the "budget_minor" field.
func (_u *RuleUpdateOne) AddBudgetMinor(v int64) *RuleUpdateOne {
	_u.mutation.AddBudgetMinor(v)
	return _u
}

// ClearBudgetMinor clears the value of the "budget_minor" field.
func (_u *RuleUpdateOne) ClearBudgetMinor() *RuleUpdateOne {
	_u.mutation.ClearBudgetMinor()
	return _u
}

// SetBudgetCurrency sets the "budget_currency" field.
func (_u *RuleUpdateOne) SetBudgetCurrency(v string) *RuleUpdateOne {
	_u.mutation.SetBudgetCurrency(v)
	return _u
}

// SetNillableBudgetCurrency sets the "budget_currency" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableBudgetCurrency(v *string) *RuleUpdateOne {
	if v != nil {
		_u.SetBudgetCurrency(*v)
	}
	return _u
}

// SetRecurring sets the "recurring" field.
func (_u *RuleUpdateOne) SetRecurring(v bool) *RuleUpdateOne {
	_u.mutation.SetRecurring(v)
	return _u
}

// SetNillableRecurring sets the "recurring" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableRecurring(v *bool) *RuleUpdateOne {
	if v != nil {
		_u.SetRecurring(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RuleUpdateOne) SetEnabled(v bool) *RuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableEnabled(v *bool) *RuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLatched sets the "latched" field.
func (_u *RuleUpdateOne) SetLatched(v bool) *RuleUpdateOne {
	_u.mutation.SetLatched(v)
	return _u
}

// SetNillableLatched sets the "latched" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableLatched(v *bool) *RuleUpdateOne {
	if v != nil {
		_u.SetLatched(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RuleUpdateOne) SetUpdatedAt(v time.Time) *RuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTarget sets the "target" edge to the Target entity.
func (_u *RuleUpdateOne) SetTarget(v *Target) *RuleUpdateOne {
	return _u.SetTargetID(v.ID)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *RuleUpdateOne) AddEventIDs(ids ...string) *RuleUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *RuleUpdateOne) AddEvents(v ...*Event) *RuleUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the RuleMutation object of the builder.
func (_u *RuleUpdateOne) Mutation() *RuleMutation {
	return _u.mutation
}

// ClearTarget clears the "target" edge to the Target entity.
func (_u *RuleUpdateOne) ClearTarget() *RuleUpdateOne {
	_u.mutation.ClearTarget()
	return _u
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *RuleUpdateOne) ClearEvents() *RuleUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *RuleUpdateOne) RemoveEventIDs(ids ...string) *RuleUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *RuleUpdateOne) RemoveEvents(v ...*Event) *RuleUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the RuleUpdate builder.
func (_u *RuleUpdateOne) Where(ps ...predicate.Rule) *RuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RuleUpdateOne) Select(field string, fields ...string) *RuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Rule entity.
func (_u *RuleUpdateOne) Save(ctx context.Context) (*Rule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuleUpdateOne) SaveX(ctx context.Context) *Rule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuleUpdateOne) check() error {
	if v, ok := _u.mutation.OwnerID(); ok {
		if err := rule.OwnerIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_id", err: fmt.Errorf(`ent: validator failed for field "Rule.owner_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Condition(); ok {
		if err := rule.ConditionValidator(v); err != nil {
			return &ValidationError{Name: "condition", err: fmt.Errorf(`ent: validator failed for field "Rule.condition": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BudgetMinor(); ok {
		if err := rule.BudgetMinorValidator(v); err != nil {
			return &ValidationError{Name: "budget_minor", err: fmt.Errorf(`ent: validator failed for field "Rule.budget_minor": %w`, err)}
		}
	}
	if _u.mutation.TargetCleared() && len(_u.mutation.TargetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Rule.target"`)
	}
	return nil
}

func (_u *RuleUpdateOne) sqlSave(ctx context.Context) (_node *Rule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rule.Table, rule.Columns, sqlgraph.NewFieldSpec(rule.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Rule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rule.FieldID)
		for _, f := range fields {
			if !rule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(rule.FieldOwnerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(rule.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(rule.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Condition(); ok {
		_spec.SetField(rule.FieldCondition, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BudgetMinor(); ok {
		_spec.SetField(rule.FieldBudgetMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBudgetMinor(); ok {
		_spec.AddField(rule.FieldBudgetMinor, field.TypeInt64, value)
	}
	if _u.mutation.BudgetMinorCleared() {
		_spec.ClearField(rule.FieldBudgetMinor, field.TypeInt64)
	}
	if value, ok := _u.mutation.BudgetCurrency(); ok {
		_spec.SetField(rule.FieldBudgetCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recurring(); ok {
		_spec.SetField(rule.FieldRecurring, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(rule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Latched(); ok {
		_spec.SetField(rule.FieldLatched, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.TargetTable,
			Columns: []string{rule.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.TargetTable,
			Columns: []string{rule.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rule.EventsTable,
			Columns: []string{rule.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rule.EventsTable,
			Columns: []string{rule.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rule.EventsTable,
			Columns: []string{rule.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Rule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
