// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/depthbomb/dealfox/ent/app"
	"github.com/depthbomb/dealfox/ent/delivery"
	"github.com/depthbomb/dealfox/ent/event"
	"github.com/depthbomb/dealfox/ent/freedelivery"
	"github.com/depthbomb/dealfox/ent/freemonitor"
	"github.com/depthbomb/dealfox/ent/freeoffer"
	"github.com/depthbomb/dealfox/ent/freesubscription"
	"github.com/depthbomb/dealfox/ent/observation"
	"github.com/depthbomb/dealfox/ent/rule"
	"github.com/depthbomb/dealfox/ent/schema"
	"github.com/depthbomb/dealfox/ent/target"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescName is the schema descriptor for name field.
	appDescName := appFields[1].Descriptor()
	// app.NameValidator is a validator for the "name" field. It is called by the builders before save.
	app.NameValidator = appDescName.Validators[0].(func(string) error)
	// appDescLastModified is the schema descriptor for last_modified field.
	appDescLastModified := appFields[3].Descriptor()
	// app.DefaultLastModified holds the default value on creation for the last_modified field.
	app.DefaultLastModified = appDescLastModified.Default.(int64)
	// appDescPriceChangeNumber is the schema descriptor for price_change_number field.
	appDescPriceChangeNumber := appFields[4].Descriptor()
	// app.DefaultPriceChangeNumber holds the default value on creation for the price_change_number field.
	app.DefaultPriceChangeNumber = appDescPriceChangeNumber.Default.(int64)
	// appDescUpdatedAt is the schema descriptor for updated_at field.
	appDescUpdatedAt := appFields[5].Descriptor()
	// app.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	app.DefaultUpdatedAt = appDescUpdatedAt.Default.(func() time.Time)
	// app.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	app.UpdateDefaultUpdatedAt = appDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appDescID is the schema descriptor for id field.
	appDescID := appFields[0].Descriptor()
	// app.IDValidator is a validator for the "id" field. It is called by the builders before save.
	app.IDValidator = appDescID.Validators[0].(func(int64) error)
	deliveryMixin := schema.Delivery{}.Mixin()
	deliveryMixinFields0 := deliveryMixin[0].Fields()
	_ = deliveryMixinFields0
	deliveryFields := schema.Delivery{}.Fields()
	_ = deliveryFields
	// deliveryDescDestinationID is the schema descriptor for destination_id field.
	deliveryDescDestinationID := deliveryFields[1].Descriptor()
	// delivery.DestinationIDValidator is a validator for the "destination_id" field. It is called by the builders before save.
	delivery.DestinationIDValidator = deliveryDescDestinationID.Validators[0].(func(string) error)
	// deliveryDescAttemptCount is the schema descriptor for attempt_count field.
	deliveryDescAttemptCount := deliveryFields[3].Descriptor()
	// delivery.DefaultAttemptCount holds the default value on creation for the attempt_count field.
	delivery.DefaultAttemptCount = deliveryDescAttemptCount.Default.(int)
	// delivery.AttemptCountValidator is a validator for the "attempt_count" field. It is called by the builders before save.
	delivery.AttemptCountValidator = deliveryDescAttemptCount.Validators[0].(func(int) error)
	// deliveryDescNextAttemptAt is the schema descriptor for next_attempt_at field.
	deliveryDescNextAttemptAt := deliveryFields[4].Descriptor()
	// delivery.DefaultNextAttemptAt holds the default value on creation for the next_attempt_at field.
	delivery.DefaultNextAttemptAt = deliveryDescNextAttemptAt.Default.(func() time.Time)
	// deliveryDescMessageID is the schema descriptor for message_id field.
	deliveryDescMessageID := deliveryFields[5].Descriptor()
	// delivery.DefaultMessageID holds the default value on creation for the message_id field.
	delivery.DefaultMessageID = deliveryDescMessageID.Default.(string)
	// deliveryDescLastError is the schema descriptor for last_error field.
	deliveryDescLastError := deliveryFields[6].Descriptor()
	// delivery.DefaultLastError holds the default value on creation for the last_error field.
	delivery.DefaultLastError = deliveryDescLastError.Default.(string)
	// deliveryDescCreatedAt is the schema descriptor for created_at field.
	deliveryDescCreatedAt := deliveryFields[7].Descriptor()
	// delivery.DefaultCreatedAt holds the default value on creation for the created_at field.
	delivery.DefaultCreatedAt = deliveryDescCreatedAt.Default.(func() time.Time)
	// deliveryDescUpdatedAt is the schema descriptor for updated_at field.
	deliveryDescUpdatedAt := deliveryFields[8].Descriptor()
	// delivery.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	delivery.DefaultUpdatedAt = deliveryDescUpdatedAt.Default.(func() time.Time)
	// delivery.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	delivery.UpdateDefaultUpdatedAt = deliveryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// deliveryDescID is the schema descriptor for id field.
	deliveryDescID := deliveryMixinFields0[0].Descriptor()
	// delivery.DefaultID holds the default value on creation for the id field.
	delivery.DefaultID = deliveryDescID.Default.(func() string)
	// delivery.IDValidator is a validator for the "id" field. It is called by the builders before save.
	delivery.IDValidator = deliveryDescID.Validators[0].(func(string) error)
	eventMixin := schema.Event{}.Mixin()
	eventMixinFields0 := eventMixin[0].Fields()
	_ = eventMixinFields0
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventFields[3].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() time.Time)
	// eventDescID is the schema descriptor for id field.
	eventDescID := eventMixinFields0[0].Descriptor()
	// event.DefaultID holds the default value on creation for the id field.
	event.DefaultID = eventDescID.Default.(func() string)
	// event.IDValidator is a validator for the "id" field. It is called by the builders before save.
	event.IDValidator = eventDescID.Validators[0].(func(string) error)
	freedeliveryMixin := schema.FreeDelivery{}.Mixin()
	freedeliveryMixinFields0 := freedeliveryMixin[0].Fields()
	_ = freedeliveryMixinFields0
	freedeliveryFields := schema.FreeDelivery{}.Fields()
	_ = freedeliveryFields
	// freedeliveryDescOfferID is the schema descriptor for offer_id field.
	freedeliveryDescOfferID := freedeliveryFields[0].Descriptor()
	// freedelivery.OfferIDValidator is a validator for the "offer_id" field. It is called by the builders before save.
	freedelivery.OfferIDValidator = freedeliveryDescOfferID.Validators[0].(func(string) error)
	// freedeliveryDescSubscriptionID is the schema descriptor for subscription_id field.
	freedeliveryDescSubscriptionID := freedeliveryFields[1].Descriptor()
	// freedelivery.SubscriptionIDValidator is a validator for the "subscription_id" field. It is called by the builders before save.
	freedelivery.SubscriptionIDValidator = freedeliveryDescSubscriptionID.Validators[0].(func(string) error)
	// freedeliveryDescOfferGeneration is the schema descriptor for offer_generation field.
	freedeliveryDescOfferGeneration := freedeliveryFields[2].Descriptor()
	// freedelivery.DefaultOfferGeneration holds the default value on creation for the offer_generation field.
	freedelivery.DefaultOfferGeneration = freedeliveryDescOfferGeneration.Default.(int)
	// freedelivery.OfferGenerationValidator is a validator for the "offer_generation" field. It is called by the builders before save.
	freedelivery.OfferGenerationValidator = freedeliveryDescOfferGeneration.Validators[0].(func(int) error)
	// freedeliveryDescDestinationID is the schema descriptor for destination_id field.
	freedeliveryDescDestinationID := freedeliveryFields[4].Descriptor()
	// freedelivery.DestinationIDValidator is a validator for the "destination_id" field. It is called by the builders before save.
	freedelivery.DestinationIDValidator = freedeliveryDescDestinationID.Validators[0].(func(string) error)
	// freedeliveryDescAttemptCount is the schema descriptor for attempt_count field.
	freedeliveryDescAttemptCount := freedeliveryFields[7].Descriptor()
	// freedelivery.DefaultAttemptCount holds the default value on creation for the attempt_count field.
	freedelivery.DefaultAttemptCount = freedeliveryDescAttemptCount.Default.(int)
	// freedelivery.AttemptCountValidator is a validator for the "attempt_count" field. It is called by the builders before save.
	freedelivery.AttemptCountValidator = freedeliveryDescAttemptCount.Validators[0].(func(int) error)
	// freedeliveryDescNextAttemptAt is the schema descriptor for next_attempt_at field.
	freedeliveryDescNextAttemptAt := freedeliveryFields[8].Descriptor()
	// freedelivery.DefaultNextAttemptAt holds the default value on creation for the next_attempt_at field.
	freedelivery.DefaultNextAttemptAt = freedeliveryDescNextAttemptAt.Default.(func() time.Time)
	// freedeliveryDescMessageID is the schema descriptor for message_id field.
	freedeliveryDescMessageID := freedeliveryFields[9].Descriptor()
	// freedelivery.DefaultMessageID holds the default value on creation for the message_id field.
	freedelivery.DefaultMessageID = freedeliveryDescMessageID.Default.(string)
	// freedeliveryDescLastError is the schema descriptor for last_error field.
	freedeliveryDescLastError := freedeliveryFields[10].Descriptor()
	// freedelivery.DefaultLastError holds the default value on creation for the last_error field.
	freedelivery.DefaultLastError = freedeliveryDescLastError.Default.(string)
	// freedeliveryDescCreatedAt is the schema descriptor for created_at field.
	freedeliveryDescCreatedAt := freedeliveryFields[11].Descriptor()
	// freedelivery.DefaultCreatedAt holds the default value on creation for the created_at field.
	freedelivery.DefaultCreatedAt = freedeliveryDescCreatedAt.Default.(func() time.Time)
	// freedeliveryDescUpdatedAt is the schema descriptor for updated_at field.
	freedeliveryDescUpdatedAt := freedeliveryFields[12].Descriptor()
	// freedelivery.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	freedelivery.DefaultUpdatedAt = freedeliveryDescUpdatedAt.Default.(func() time.Time)
	// freedelivery.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	freedelivery.UpdateDefaultUpdatedAt = freedeliveryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// freedeliveryDescID is the schema descriptor for id field.
	freedeliveryDescID := freedeliveryMixinFields0[0].Descriptor()
	// freedelivery.DefaultID holds the default value on creation for the id field.
	freedelivery.DefaultID = freedeliveryDescID.Default.(func() string)
	// freedelivery.IDValidator is a validator for the "id" field. It is called by the builders before save.
	freedelivery.IDValidator = freedeliveryDescID.Validators[0].(func(string) error)
	freemonitorFields := schema.FreeMonitor{}.Fields()
	_ = freemonitorFields
	// freemonitorDescNextCheckAt is the schema descriptor for next_check_at field.
	freemonitorDescNextCheckAt := freemonitorFields[2].Descriptor()
	// freemonitor.DefaultNextCheckAt holds the default value on creation for the next_check_at field.
	freemonitor.DefaultNextCheckAt = freemonitorDescNextCheckAt.Default.(func() time.Time)
	// freemonitorDescStatus is the schema descriptor for status field.
	freemonitorDescStatus := freemonitorFields[3].Descriptor()
	// freemonitor.DefaultStatus holds the default value on creation for the status field.
	freemonitor.DefaultStatus = freemonitorDescStatus.Default.(string)
	// freemonitorDescFailures is the schema descriptor for failures field.
	freemonitorDescFailures := freemonitorFields[5].Descriptor()
	// freemonitor.DefaultFailures holds the default value on creation for the failures field.
	freemonitor.DefaultFailures = freemonitorDescFailures.Default.(int)
	freeofferMixin := schema.FreeOffer{}.Mixin()
	freeofferMixinFields0 := freeofferMixin[0].Fields()
	_ = freeofferMixinFields0
	freeofferFields := schema.FreeOffer{}.Fields()
	_ = freeofferFields
	// freeofferDescSource is the schema descriptor for source field.
	freeofferDescSource := freeofferFields[1].Descriptor()
	// freeoffer.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	freeoffer.SourceValidator = freeofferDescSource.Validators[0].(func(string) error)
	// freeofferDescEligible is the schema descriptor for eligible field.
	freeofferDescEligible := freeofferFields[3].Descriptor()
	// freeoffer.DefaultEligible holds the default value on creation for the eligible field.
	freeoffer.DefaultEligible = freeofferDescEligible.Default.(bool)
	// freeofferDescClosed is the schema descriptor for closed field.
	freeofferDescClosed := freeofferFields[4].Descriptor()
	// freeoffer.DefaultClosed holds the default value on creation for the closed field.
	freeoffer.DefaultClosed = freeofferDescClosed.Default.(bool)
	// freeofferDescGeneration is the schema descriptor for generation field.
	freeofferDescGeneration := freeofferFields[5].Descriptor()
	// freeoffer.DefaultGeneration holds the default value on creation for the generation field.
	freeoffer.DefaultGeneration = freeofferDescGeneration.Default.(int)
	// freeoffer.GenerationValidator is a validator for the "generation" field. It is called by the builders before save.
	freeoffer.GenerationValidator = freeofferDescGeneration.Validators[0].(func(int) error)
	// freeofferDescFirstSeenAt is the schema descriptor for first_seen_at field.
	freeofferDescFirstSeenAt := freeofferFields[6].Descriptor()
	// freeoffer.DefaultFirstSeenAt holds the default value on creation for the first_seen_at field.
	freeoffer.DefaultFirstSeenAt = freeofferDescFirstSeenAt.Default.(func() time.Time)
	// freeofferDescLastSeenAt is the schema descriptor for last_seen_at field.
	freeofferDescLastSeenAt := freeofferFields[7].Descriptor()
	// freeoffer.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	freeoffer.DefaultLastSeenAt = freeofferDescLastSeenAt.Default.(func() time.Time)
	// freeofferDescID is the schema descriptor for id field.
	freeofferDescID := freeofferMixinFields0[0].Descriptor()
	// freeoffer.DefaultID holds the default value on creation for the id field.
	freeoffer.DefaultID = freeofferDescID.Default.(func() string)
	// freeoffer.IDValidator is a validator for the "id" field. It is called by the builders before save.
	freeoffer.IDValidator = freeofferDescID.Validators[0].(func(string) error)
	freesubscriptionMixin := schema.FreeSubscription{}.Mixin()
	freesubscriptionMixinFields0 := freesubscriptionMixin[0].Fields()
	_ = freesubscriptionMixinFields0
	freesubscriptionFields := schema.FreeSubscription{}.Fields()
	_ = freesubscriptionFields
	// freesubscriptionDescScope is the schema descriptor for scope field.
	freesubscriptionDescScope := freesubscriptionFields[0].Descriptor()
	// freesubscription.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	freesubscription.ScopeValidator = freesubscriptionDescScope.Validators[0].(func(string) error)
	// freesubscriptionDescSource is the schema descriptor for source field.
	freesubscriptionDescSource := freesubscriptionFields[1].Descriptor()
	// freesubscription.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	freesubscription.SourceValidator = freesubscriptionDescSource.Validators[0].(func(string) error)
	// freesubscriptionDescDestinationID is the schema descriptor for destination_id field.
	freesubscriptionDescDestinationID := freesubscriptionFields[3].Descriptor()
	// freesubscription.DestinationIDValidator is a validator for the "destination_id" field. It is called by the builders before save.
	freesubscription.DestinationIDValidator = freesubscriptionDescDestinationID.Validators[0].(func(string) error)
	// freesubscriptionDescManagedBy is the schema descriptor for managed_by field.
	freesubscriptionDescManagedBy := freesubscriptionFields[4].Descriptor()
	// freesubscription.ManagedByValidator is a validator for the "managed_by" field. It is called by the builders before save.
	freesubscription.ManagedByValidator = freesubscriptionDescManagedBy.Validators[0].(func(string) error)
	// freesubscriptionDescEnabled is the schema descriptor for enabled field.
	freesubscriptionDescEnabled := freesubscriptionFields[5].Descriptor()
	// freesubscription.DefaultEnabled holds the default value on creation for the enabled field.
	freesubscription.DefaultEnabled = freesubscriptionDescEnabled.Default.(bool)
	// freesubscriptionDescCreatedAt is the schema descriptor for created_at field.
	freesubscriptionDescCreatedAt := freesubscriptionFields[6].Descriptor()
	// freesubscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	freesubscription.DefaultCreatedAt = freesubscriptionDescCreatedAt.Default.(func() time.Time)
	// freesubscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	freesubscriptionDescUpdatedAt := freesubscriptionFields[7].Descriptor()
	// freesubscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	freesubscription.DefaultUpdatedAt = freesubscriptionDescUpdatedAt.Default.(func() time.Time)
	// freesubscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	freesubscription.UpdateDefaultUpdatedAt = freesubscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// freesubscriptionDescID is the schema descriptor for id field.
	freesubscriptionDescID := freesubscriptionMixinFields0[0].Descriptor()
	// freesubscription.DefaultID holds the default value on creation for the id field.
	freesubscription.DefaultID = freesubscriptionDescID.Default.(func() string)
	// freesubscription.IDValidator is a validator for the "id" field. It is called by the builders before save.
	freesubscription.IDValidator = freesubscriptionDescID.Validators[0].(func(string) error)
	observationMixin := schema.Observation{}.Mixin()
	observationMixinFields0 := observationMixin[0].Fields()
	_ = observationMixinFields0
	observationFields := schema.Observation{}.Fields()
	_ = observationFields
	// observationDescID is the schema descriptor for id field.
	observationDescID := observationMixinFields0[0].Descriptor()
	// observation.DefaultID holds the default value on creation for the id field.
	observation.DefaultID = observationDescID.Default.(func() string)
	// observation.IDValidator is a validator for the "id" field. It is called by the builders before save.
	observation.IDValidator = observationDescID.Validators[0].(func(string) error)
	ruleMixin := schema.Rule{}.Mixin()
	ruleMixinFields0 := ruleMixin[0].Fields()
	_ = ruleMixinFields0
	ruleFields := schema.Rule{}.Fields()
	_ = ruleFields
	// ruleDescOwnerID is the schema descriptor for owner_id field.
	ruleDescOwnerID := ruleFields[1].Descriptor()
	// rule.OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	rule.OwnerIDValidator = ruleDescOwnerID.Validators[0].(func(string) error)
	// ruleDescBudgetMinor is the schema descriptor for budget_minor field.
	ruleDescBudgetMinor := ruleFields[4].Descriptor()
	// rule.BudgetMinorValidator is a validator for the "budget_minor" field. It is called by the builders before save.
	rule.BudgetMinorValidator = ruleDescBudgetMinor.Validators[0].(func(int64) error)
	// ruleDescBudgetCurrency is the schema descriptor for budget_currency field.
	ruleDescBudgetCurrency := ruleFields[5].Descriptor()
	// rule.DefaultBudgetCurrency holds the default value on creation for the budget_currency field.
	rule.DefaultBudgetCurrency = ruleDescBudgetCurrency.Default.(string)
	// ruleDescRecurring is the schema descriptor for recurring field.
	ruleDescRecurring := ruleFields[6].Descriptor()
	// rule.DefaultRecurring holds the default value on creation for the recurring field.
	rule.DefaultRecurring = ruleDescRecurring.Default.(bool)
	// ruleDescEnabled is the schema descriptor for enabled field.
	ruleDescEnabled := ruleFields[7].Descriptor()
	// rule.DefaultEnabled holds the default value on creation for the enabled field.
	rule.DefaultEnabled = ruleDescEnabled.Default.(bool)
	// ruleDescLatched is the schema descriptor for latched field.
	ruleDescLatched := ruleFields[8].Descriptor()
	// rule.DefaultLatched holds the default value on creation for the latched field.
	rule.DefaultLatched = ruleDescLatched.Default.(bool)
	// ruleDescCreatedAt is the schema descriptor for created_at field.
	ruleDescCreatedAt := ruleFields[9].Descriptor()
	// rule.DefaultCreatedAt holds the default value on creation for the created_at field.
	rule.DefaultCreatedAt = ruleDescCreatedAt.Default.(func() time.Time)
	// ruleDescUpdatedAt is the schema descriptor for updated_at field.
	ruleDescUpdatedAt := ruleFields[10].Descriptor()
	// rule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rule.DefaultUpdatedAt = ruleDescUpdatedAt.Default.(func() time.Time)
	// rule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rule.UpdateDefaultUpdatedAt = ruleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ruleDescID is the schema descriptor for id field.
	ruleDescID := ruleMixinFields0[0].Descriptor()
	// rule.DefaultID holds the default value on creation for the id field.
	rule.DefaultID = ruleDescID.Default.(func() string)
	// rule.IDValidator is a validator for the "id" field. It is called by the builders before save.
	rule.IDValidator = ruleDescID.Validators[0].(func(string) error)
	targetMixin := schema.Target{}.Mixin()
	targetMixinFields0 := targetMixin[0].Fields()
	_ = targetMixinFields0
	targetFields := schema.Target{}.Fields()
	_ = targetFields
	// targetDescCountry is the schema descriptor for country field.
	targetDescCountry := targetFields[1].Descriptor()
	// target.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	target.CountryValidator = func() func(string) error {
		validators := targetDescCountry.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(country string) error {
			for _, fn := range fns {
				if err := fn(country); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// targetDescNextDueAt is the schema descriptor for next_due_at field.
	targetDescNextDueAt := targetFields[2].Descriptor()
	// target.DefaultNextDueAt holds the default value on creation for the next_due_at field.
	target.DefaultNextDueAt = targetDescNextDueAt.Default.(func() time.Time)
	// targetDescFailureCount is the schema descriptor for failure_count field.
	targetDescFailureCount := targetFields[4].Descriptor()
	// target.DefaultFailureCount holds the default value on creation for the failure_count field.
	target.DefaultFailureCount = targetDescFailureCount.Default.(int)
	// target.FailureCountValidator is a validator for the "failure_count" field. It is called by the builders before save.
	target.FailureCountValidator = targetDescFailureCount.Validators[0].(func(int) error)
	// targetDescLastError is the schema descriptor for last_error field.
	targetDescLastError := targetFields[5].Descriptor()
	// target.DefaultLastError holds the default value on creation for the last_error field.
	target.DefaultLastError = targetDescLastError.Default.(string)
	// targetDescID is the schema descriptor for id field.
	targetDescID := targetMixinFields0[0].Descriptor()
	// target.DefaultID holds the default value on creation for the id field.
	target.DefaultID = targetDescID.Default.(func() string)
	// target.IDValidator is a validator for the "id" field. It is called by the builders before save.
	target.IDValidator = targetDescID.Validators[0].(func(string) error)
}
