// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/depthbomb/dealfox/ent/app"
	"github.com/depthbomb/dealfox/ent/observation"
	"github.com/depthbomb/dealfox/ent/rule"
	"github.com/depthbomb/dealfox/ent/target"
)

// TargetCreate is the builder for creating a Target entity.
type TargetCreate struct {
	config
	mutation *TargetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAppID sets the "app_id" field.
func (_c *TargetCreate) SetAppID(v int64) *TargetCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetCountry sets the "country" field.
func (_c *TargetCreate) SetCountry(v string) *TargetCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNextDueAt sets the "next_due_at" field.
func (_c *TargetCreate) SetNextDueAt(v time.Time) *TargetCreate {
	_c.mutation.SetNextDueAt(v)
	return _c
}

// SetNillableNextDueAt sets the "next_due_at" field if the given value is not nil.
func (_c *TargetCreate) SetNillableNextDueAt(v *time.Time) *TargetCreate {
	if v != nil {
		_c.SetNextDueAt(*v)
	}
	return _c
}

// SetLastObservedAt sets the "last_observed_at" field.
func (_c *TargetCreate) SetLastObservedAt(v time.Time) *TargetCreate {
	_c.mutation.SetLastObservedAt(v)
	return _c
}

// SetNillableLastObservedAt sets the "last_observed_at" field if the given value is not nil.
func (_c *TargetCreate) SetNillableLastObservedAt(v *time.Time) *TargetCreate {
	if v != nil {
		_c.SetLastObservedAt(*v)
	}
	return _c
}

// SetFailureCount sets the "failure_count" field.
func (_c *TargetCreate) SetFailureCount(v int) *TargetCreate {
	_c.mutation.SetFailureCount(v)
	return _c
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (_c *TargetCreate) SetNillableFailureCount(v *int) *TargetCreate {
	if v != nil {
		_c.SetFailureCount(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *TargetCreate) SetLastError(v string) *TargetCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *TargetCreate) SetNillableLastError(v *string) *TargetCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TargetCreate) SetID(v string) *TargetCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TargetCreate) SetNillableID(v *string) *TargetCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetApp sets the "app" edge to the App entity.
func (_c *TargetCreate) SetApp(v *App) *TargetCreate {
	return _c.SetAppID(v.ID)
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (_c *TargetCreate) AddRuleIDs(ids ...string) *TargetCreate {
	_c.mutation.AddRuleIDs(ids...)
	return _c
}

// AddRules adds the "rules" edges to the Rule entity.
func (_c *TargetCreate) AddRules(v ...*Rule) *TargetCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRuleIDs(ids...)
}

// AddObservationIDs adds the "observations" edge to the Observation entity by IDs.
func (_c *TargetCreate) AddObservationIDs(ids ...string) *TargetCreate {
	_c.mutation.AddObservationIDs(ids...)
	return _c
}

// AddObservations adds the "observations" edges to the Observation entity.
func (_c *TargetCreate) AddObservations(v ...*Observation) *TargetCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddObservationIDs(ids...)
}

// Mutation returns the TargetMutation object of the builder.
func (_c *TargetCreate) Mutation() *TargetMutation {
	return _c.mutation
}

// Save creates the Target in the database.
func (_c *TargetCreate) Save(ctx context.Context) (*Target, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TargetCreate) SaveX(ctx context.Context) *Target {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TargetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TargetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TargetCreate) defaults() {
	if _, ok := _c.mutation.NextDueAt(); !ok {
		v := target.DefaultNextDueAt()
		_c.mutation.SetNextDueAt(v)
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		v := target.DefaultFailureCount
		_c.mutation.SetFailureCount(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := target.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := target.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TargetCreate) check() error {
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "Target.app_id"`)}
	}
	if _, ok := _c.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "Target.country"`)}
	}
	if v, ok := _c.mutation.Country(); ok {
		if err := target.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Target.country": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NextDueAt(); !ok {
		return &ValidationError{Name: "next_due_at", err: errors.New(`ent: missing required field "Target.next_due_at"`)}
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		return &ValidationError{Name: "failure_count", err: errors.New(`ent: missing required field "Target.failure_count"`)}
	}
	if v, ok := _c.mutation.FailureCount(); ok {
		if err := target.FailureCountValidator(v); err != nil {
			return &ValidationError{Name: "failure_count", err: fmt.Errorf(`ent: validator failed for field "Target.failure_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "Target.last_error"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := target.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Target.id": %w`, err)}
		}
	}
	if len(_c.mutation.AppIDs()) == 0 {
		return &ValidationError{Name: "app", err: errors.New(`ent: missing required edge "Target.app"`)}
	}
	return nil
}

func (_c *TargetCreate) sqlSave(ctx context.Context) (*Target, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Target.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TargetCreate) createSpec() (*Target, *sqlgraph.CreateSpec) {
	var (
		_node = &Target{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(target.Table, sqlgraph.NewFieldSpec(target.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(target.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.NextDueAt(); ok {
		_spec.SetField(target.FieldNextDueAt, field.TypeTime, value)
		_node.NextDueAt = value
	}
	if value, ok := _c.mutation.LastObservedAt(); ok {
		_spec.SetField(target.FieldLastObservedAt, field.TypeTime, value)
		_node.LastObservedAt = &value
	}
	if value, ok := _c.mutation.FailureCount(); ok {
		_spec.SetField(target.FieldFailureCount, field.TypeInt, value)
		_node.FailureCount = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(target.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if nodes := _c.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   target.AppTable,
			Columns: []string{target.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AppID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   target.RulesTable,
			Columns: []string{target.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ObservationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   target.ObservationsTable,
			Columns: []string{target.ObservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(observation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Target.Create().
//		SetAppID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TargetUpsert) {
//			SetAppID(v+v).
//		}).
//		Exec(ctx)
func (_c *TargetCreate) OnConflict(opts ...sql.ConflictOption) *TargetUpsertOne {
	_c.conflict = opts
	return &TargetUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Target.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TargetCreate) OnConflictColumns(columns ...string) *TargetUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TargetUpsertOne{
		create: _c,
	}
}

type (
	// TargetUpsertOne is the builder for "upsert"-ing
	//  one Target node.
	TargetUpsertOne struct {
		create *TargetCreate
	}

	// TargetUpsert is the "OnConflict" setter.
	TargetUpsert struct {
		*sql.UpdateSet
	}
)

// SetAppID sets the "app_id" field.
func (u *TargetUpsert) SetAppID(v int64) *TargetUpsert {
	u.Set(target.FieldAppID, v)
	return u
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *TargetUpsert) UpdateAppID() *TargetUpsert {
	u.SetExcluded(target.FieldAppID)
	return u
}

// SetCountry sets the "country" field.
func (u *TargetUpsert) SetCountry(v string) *TargetUpsert {
	u.Set(target.FieldCountry, v)
	return u
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *TargetUpsert) UpdateCountry() *TargetUpsert {
	u.SetExcluded(target.FieldCountry)
	return u
}

// SetNextDueAt sets the "next_due_at" field.
func (u *TargetUpsert) SetNextDueAt(v time.Time) *TargetUpsert {
	u.Set(target.FieldNextDueAt, v)
	return u
}

// UpdateNextDueAt sets the "next_due_at" field to the value that was provided on create.
func (u *TargetUpsert) UpdateNextDueAt() *TargetUpsert {
	u.SetExcluded(target.FieldNextDueAt)
	return u
}

// SetLastObservedAt sets the "last_observed_at" field.
func (u *TargetUpsert) SetLastObservedAt(v time.Time) *TargetUpsert {
	u.Set(target.FieldLastObservedAt, v)
	return u
}

// UpdateLastObservedAt sets the "last_observed_at" field to the value that was provided on create.
func (u *TargetUpsert) UpdateLastObservedAt() *TargetUpsert {
	u.SetExcluded(target.FieldLastObservedAt)
	return u
}

// ClearLastObservedAt clears the value of the "last_observed_at" field.
func (u *TargetUpsert) ClearLastObservedAt() *TargetUpsert {
	u.SetNull(target.FieldLastObservedAt)
	return u
}

// SetFailureCount sets the "failure_count" field.
func (u *TargetUpsert) SetFailureCount(v int) *TargetUpsert {
	u.Set(target.FieldFailureCount, v)
	return u
}

// UpdateFailureCount sets the "failure_count" field to the value that was provided on create.
func (u *TargetUpsert) UpdateFailureCount() *TargetUpsert {
	u.SetExcluded(target.FieldFailureCount)
	return u
}

// AddFailureCount adds v to the "failure_count" field.
func (u *TargetUpsert) AddFailureCount(v int) *TargetUpsert {
	u.Add(target.FieldFailureCount, v)
	return u
}

// SetLastError sets the "last_error" field.
func (u *TargetUpsert) SetLastError(v string) *TargetUpsert {
	u.Set(target.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *TargetUpsert) UpdateLastError() *TargetUpsert {
	u.SetExcluded(target.FieldLastError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Target.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(target.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TargetUpsertOne) UpdateNewValues() *TargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(target.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Target.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TargetUpsertOne) Ignore() *TargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TargetUpsertOne) DoNothing() *TargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TargetCreate.OnConflict
// documentation for more info.
func (u *TargetUpsertOne) Update(set func(*TargetUpsert)) *TargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TargetUpsert{UpdateSet: update})
	}))
	return u
}

// SetAppID sets the "app_id" field.
func (u *TargetUpsertOne) SetAppID(v int64) *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *TargetUpsertOne) UpdateAppID() *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.UpdateAppID()
	})
}

// SetCountry sets the "country" field.
func (u *TargetUpsertOne) SetCountry(v string) *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *TargetUpsertOne) UpdateCountry() *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.UpdateCountry()
	})
}

// SetNextDueAt sets the "next_due_at" field.
func (u *TargetUpsertOne) SetNextDueAt(v time.Time) *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.SetNextDueAt(v)
	})
}

// UpdateNextDueAt sets the "next_due_at" field to the value that was provided on create.
func (u *TargetUpsertOne) UpdateNextDueAt() *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.UpdateNextDueAt()
	})
}

// SetLastObservedAt sets the "last_observed_at" field.
func (u *TargetUpsertOne) SetLastObservedAt(v time.Time) *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.SetLastObservedAt(v)
	})
}

// UpdateLastObservedAt sets the "last_observed_at" field to the value that was provided on create.
func (u *TargetUpsertOne) UpdateLastObservedAt() *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.UpdateLastObservedAt()
	})
}

// ClearLastObservedAt clears the value of the "last_observed_at" field.
func (u *TargetUpsertOne) ClearLastObservedAt() *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.ClearLastObservedAt()
	})
}

// SetFailureCount sets the "failure_count" field.
func (u *TargetUpsertOne) SetFailureCount(v int) *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.SetFailureCount(v)
	})
}

// AddFailureCount adds v to the "failure_count" field.
func (u *TargetUpsertOne) AddFailureCount(v int) *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.AddFailureCount(v)
	})
}

// UpdateFailureCount sets the "failure_count" field to the value that was provided on create.
func (u *TargetUpsertOne) UpdateFailureCount() *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.UpdateFailureCount()
	})
}

// SetLastError sets the "last_error" field.
func (u *TargetUpsertOne) SetLastError(v string) *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *TargetUpsertOne) UpdateLastError() *TargetUpsertOne {
	return u.Update(func(s *TargetUpsert) {
		s.UpdateLastError()
	})
}

// Exec executes the query.
func (u *TargetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TargetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TargetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TargetUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TargetUpsertOne.ID is not supported by MySQL driver. Use TargetUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TargetUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TargetCreateBulk is the builder for creating many Target entities in bulk.
type TargetCreateBulk struct {
	config
	err      error
	builders []*TargetCreate
	conflict []sql.ConflictOption
}

// Save creates the Target entities in the database.
func (_c *TargetCreateBulk) Save(ctx context.Context) ([]*Target, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Target, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TargetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TargetCreateBulk) SaveX(ctx context.Context) []*Target {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TargetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TargetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Target.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TargetUpsert) {
//			SetAppID(v+v).
//		}).
//		Exec(ctx)
func (_c *TargetCreateBulk) OnConflict(opts ...sql.ConflictOption) *TargetUpsertBulk {
	_c.conflict = opts
	return &TargetUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Target.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TargetCreateBulk) OnConflictColumns(columns ...string) *TargetUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TargetUpsertBulk{
		create: _c,
	}
}

// TargetUpsertBulk is the builder for "upsert"-ing
// a bulk of Target nodes.
type TargetUpsertBulk struct {
	create *TargetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Target.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(target.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TargetUpsertBulk) UpdateNewValues() *TargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(target.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Target.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TargetUpsertBulk) Ignore() *TargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TargetUpsertBulk) DoNothing() *TargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TargetCreateBulk.OnConflict
// documentation for more info.
func (u *TargetUpsertBulk) Update(set func(*TargetUpsert)) *TargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TargetUpsert{UpdateSet: update})
	}))
	return u
}

// SetAppID sets the "app_id" field.
func (u *TargetUpsertBulk) SetAppID(v int64) *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *TargetUpsertBulk) UpdateAppID() *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.UpdateAppID()
	})
}

// SetCountry sets the "country" field.
func (u *TargetUpsertBulk) SetCountry(v string) *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *TargetUpsertBulk) UpdateCountry() *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.UpdateCountry()
	})
}

// SetNextDueAt sets the "next_due_at" field.
func (u *TargetUpsertBulk) SetNextDueAt(v time.Time) *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.SetNextDueAt(v)
	})
}

// UpdateNextDueAt sets the "next_due_at" field to the value that was provided on create.
func (u *TargetUpsertBulk) UpdateNextDueAt() *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.UpdateNextDueAt()
	})
}

// SetLastObservedAt sets the "last_observed_at" field.
func (u *TargetUpsertBulk) SetLastObservedAt(v time.Time) *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.SetLastObservedAt(v)
	})
}

// UpdateLastObservedAt sets the "last_observed_at" field to the value that was provided on create.
func (u *TargetUpsertBulk) UpdateLastObservedAt() *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.UpdateLastObservedAt()
	})
}

// ClearLastObservedAt clears the value of the "last_observed_at" field.
func (u *TargetUpsertBulk) ClearLastObservedAt() *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.ClearLastObservedAt()
	})
}

// SetFailureCount sets the "failure_count" field.
func (u *TargetUpsertBulk) SetFailureCount(v int) *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.SetFailureCount(v)
	})
}

// AddFailureCount adds v to the "failure_count" field.
func (u *TargetUpsertBulk) AddFailureCount(v int) *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.AddFailureCount(v)
	})
}

// UpdateFailureCount sets the "failure_count" field to the value that was provided on create.
func (u *TargetUpsertBulk) UpdateFailureCount() *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.UpdateFailureCount()
	})
}

// SetLastError sets the "last_error" field.
func (u *TargetUpsertBulk) SetLastError(v string) *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *TargetUpsertBulk) UpdateLastError() *TargetUpsertBulk {
	return u.Update(func(s *TargetUpsert) {
		s.UpdateLastError()
	})
}

// Exec executes the query.
func (u *TargetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TargetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TargetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TargetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
