// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// App is the predicate function for app builders.
type App func(*sql.Selector)

// Delivery is the predicate function for delivery builders.
type Delivery func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// FreeDelivery is the predicate function for freedelivery builders.
type FreeDelivery func(*sql.Selector)

// FreeMonitor is the predicate function for freemonitor builders.
type FreeMonitor func(*sql.Selector)

// FreeOffer is the predicate function for freeoffer builders.
type FreeOffer func(*sql.Selector)

// FreeSubscription is the predicate function for freesubscription builders.
type FreeSubscription func(*sql.Selector)

// Observation is the predicate function for observation builders.
type Observation func(*sql.Selector)

// Rule is the predicate function for rule builders.
type Rule func(*sql.Selector)

// Target is the predicate function for target builders.
type Target func(*sql.Selector)
